In [111]:
import pandas as pd
import linguistica as lxa

In [133]:
fLex4="Lexique4/Lexique4.tsv"
dfLex4=pd.read_csv(fLex4,sep="\t")
dfLex4

,1_Mot,2_Phono,3_Phono_IPA,4_Lemme,5_Cgram,6_CgramOrtho,7_Genre,8_Nombre,9_InfoVER,10_FreqMot,...,28_PUOrtho,29_PUPhon,30_MorphoBase,31_MorphoStruct,32_MorphoDecomp,33_Preval,34_PrevalNb,35_RT_FLP,36_zRT_FLP,37_Err_FLP
0,pollacks,pOlak,pɔlak,pollacks,NOM,NOM,e,p,NaN,0.003,...,8,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,disproportionnées,dispRopORsjone,dispʁopɔʁsjone,disproportionner,VER,"VER,ADJ",f,p,par:pas:,0.041,...,0,12,NaN,NaN,NaN,100.0,26.0,NaN,NaN,NaN
2,marger,maRZe,maʁʒe,marger,VER,VER,NaN,NaN,inf,0.006,...,6,5,marge,0-1-1,/marg(e).er,60.0,25.0,NaN,NaN,NaN
3,cybernéticien,sibERnetisj5,sibɛʁnetisjɛ̃,cybernéticien,NOM,"NOM,ADJ",m,s,NaN,0.016,...,11,10,NaN,1-0-2,_cyber.éti(que)/c.ien,72.0,18.0,NaN,NaN,NaN
4,accusons,akyz§,akyzɔ̃,accuser,VER,VER,NaN,p,"ind:pre:1,imp:pre:1",0.294,...,0,0,NaN,NaN,NaN,100.0,28.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189858,décrété,dekRete,dekʁete,décréter,VER,VER,m,s,par:pas:,1.180,...,0,5,NaN,NaN,NaN,94.0,18.0,707.916667,0.075223,0.0
189859,généralisais,ZeneRalizE,ʒeneʁalizɛ,généraliser,VER,VER,NaN,s,"ind:imp:2,ind:imp:1",0.009,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
189860,briefera,bRif°Ra,bʁifəʁa,briefer,VER,VER,NaN,s,ind:fut:3,0.130,...,0,0,NaN,NaN,NaN,76.0,30.0,NaN,NaN,NaN
189861,phénoménologiquement,fenOmenOlOZikm@,fenɔmenɔlɔʒikmɑ̃,phénoménologiquement,ADV,ADV,NaN,NaN,NaN,0.006,...,19,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
189862,éteignirent,etENiR,etɛɲiʁ,éteindre,VER,VER,NaN,p,ind:pas:3,0.066,...,0,0,NaN,NaN,NaN,100.0,34.0,839.520000,0.364618,0.0

# Tests sur Lexique4 complet

In [162]:
phon2Lex={}
for d in dfLex4[["3_Phono_IPA","4_Lemme"]].to_dict(orient="records"):
    k=d["3_Phono_IPA"]
    v=d["4_Lemme"]
    if k not in phon2Lex:
        phon2Lex[k]=set()
    phon2Lex[k].add(v)
phon2Lex

{'pɔlak': {'polak', 'pollack', 'pollacks'},
 'dispʁopɔʁsjone': {'disproportionner', 'disproportionné'},
 'maʁʒe': {'marger'},
 'sibɛʁnetisjɛ̃': {'cybernéticien'},
 'akyzɔ̃': {'accuser'},
 'fɛʁlaʒ': {'ferlage'},
 'sezaʁjɛ̃': {'césarien'},
 'ofisjɑ̃': {'officiant', 'officier'},
 'ɛ̃kyltivabl': {'incultivable'},
 'apsɔʁbje': {'absorber'},
 'puʁɔ̃': {'pouvoir'},
 'ɑ̃tʁətyʁɛ': {'entretuer'},
 'dezeʁitɛ': {'déshériter'},
 'duv': {'douve'},
 'atiz': {'attiser'},
 'ʒap': {'jap', 'japper'},
 'desule': {'dessaouler', 'dessouler', 'dessoûler', 'désaouler'},
 'kniboʁd': {'kneeboard'},
 'adubje': {'adouber'},
 'efɛktɥe': {'effectuer'},
 'ebʁɥit': {'ébruiter'},
 'ʁəsɛʁ': {'reservir', 'resserre', 'resserrer', 'resservir'},
 'ʁesit': {'réciter'},
 'mizɛ': {'miser'},
 'ʁəkupe': {'recouper'},
 'neʁeis': {'néréis'},
 'fɔ̃səʁɛ': {'foncer'},
 'dula': {'doula', 'doulas'},
 'ʁədiʁiʒe': {'rediriger'},
 'fɛso': {'faisceau'},
 'agʁavəʁa': {'aggraver'},
 'nitʃeɛn': {'nietzschéen', 'nietzschéenne'},
 'dezɔkyltɑ̃': {'désoccultant'},
 'dekuvʁiʁɛ': {'découvrir'},
 'kɔ̃tuʁne': {'contourner', 'contourné'},
 'dekuvʁ': {'découvrir'},
 'ʁətɑ̃dy': {'retendre'},
 'dekole': {'décoller'},
 'depɔzɑ̃': {'déposant'},
 'djeʒɛz': {'diégèse'},
 'tyʁʒesɑ̃': {'turgescent'},
 'ʁapœʁ': {'rapeur', 'rapeurs', 'rappeur'},
 'desy': {'décevoir', 'déçu'},
 'gʁɑ̃tɔ̃kl': {'grand-oncle'},
 'pozitif': {'positif'},
 'seʁigʁafi': {'sérigraphie', 'sérigraphié', 'sérigraphiés'},
 'ʁəseziʁe': {'ressaisir'},
 'kono': {'conneau'},
 'bosɥe': {'bossuer'},
 'fjɛlø': {'fielleux'},
 'abatʁɛ': {'abattre'},
 'klwazɔnəʁɛ': {'cloisonner'},
 'pylyle': {'pulluler'},
 'kakawɛt': {'cacahouète', 'cacahuète'},
 'ekaʁte': {'écarter', 'écarté'},
 'ʁezɛʁv': {'réserve', 'réserver'},
 'mɔnɔdimɑ̃sjɔnɛl': {'monodimensionnel'},
 'bikaʁe': {'bicarré'},
 'asɛje': {'assayez', 'assayé', 'asseoir', 'asseyez'},
 'istɔʁi': {'historier'},
 'kalsɔ̃': {'caleçon', 'calçons'},
 'deniʃam': {'dénicher'},
 'bʁoʃɛt': {'brochette'},
 'nonaʒenɛʁ': {'nonagénaire'},
 'leʒɛʁəte': {'légèreté'},
 'atɑ̃sjɔna': {'attentionner'},
 'sɛʁvɔ̃': {'servir'},
 'paʁɑ̃t': {'parent'},
 'depʁesje': {'déprécier'},
 'peplɔm': {'peplum', 'péplum'},
 'ɛgmaʁin': {'aigue-marine'},
 'dezeʁite': {'déshériter', 'déshérité'},
 'psikɔmɛtʁ': {'psychomètre'},
 'buʁiko': {'bourricot'},
 'ʁaʃɛtəʁɛ': {'racheter'},
 'kavɛʁnøz': {'caverneux'},
 'kʁijoʒenize': {'cryogéniser', 'cryogénisé', 'cryogénisée', 'cryogénisés'},
 'mytine': {'mutiner', 'mutiné'},
 'dʁap': {'draper'},
 'ʁəpɛ̃tyʁ': {'repeinture', 'repeinturer'},
 'kopʁɔdɥi': {'co-produit', 'coproduire'},
 'mazinjɛ̃': {'mazzinien'},
 'tyʁlypinɛ': {'turlupiner'},
 'mɔtilite': {'motilité'},
 'pʁezɑ̃tasjɔ̃': {'présentation'},
 'fʁɛsk': {'fresque'},
 'ɔʁlɔ̃': {'orlon'},
 'epinø': {'épineux'},
 'bum': {'boom', 'boum', 'boumer'},
 'ɑ̃ʃɑ̃təmɑ̃': {'enchantement'},
 'fʁijɑ̃': {'friand', 'friant'},
 'fʁaktyʁe': {'fracturer', 'fracturé'},
 'vilipɑ̃de': {'vilipender', 'vilipendé'},
 'kaʁnatik': {'carnatique'},
 'bɛɲ': {'baigner', 'beigne'},
 'peizaʒɛʁ': {'paysager'},
 'pɔlitɔlɔg': {'politologue'},
 'pwasɔ̃klun': {'poisson-clown', 'poissons-clown'},
 'paʁiʁɛ': {'parier'},
 'vizjɔnəʁa': {'visionner'},
 'ʁəlɔkalize': {'relocaliser', 'relocalisé'},
 'utʁe': {'outrer', 'outré'},
 'aleʒe': {'alléger'},
 'ɛskabo': {'escabeau'},
 'dʁagəʁje': {'draguer'},
 'nøʁɔpʁɔtɛksjɔ̃': {'neuroprotection'},
 'distɑ̃se': {'distancer'},
 'ʃasəʁa': {'chasser'},
 'ʁuj': {'rouille', 'rouiller'},
 'ɛ̃pʁesjonabl': {'impressionnable'},
 'dezilyzjɔne': {'désillusionner'},
 'debaʁa': {'débarras', 'débarrer'},
 'syzidike': {'susindiquée'},
 'temwaɲe': {'témoigner'},
 'ɑ̃kɛte': {'enquêter', 'enquêté'},
 'pɛləte': {'pelleter', 'pelletée'},
 'ɛgzɛʁsɛʁ': {'exercer'},
 'ʁevɔlysjɔnaʁist': {'révolutionnariste'},
 'ɑ̃deɑ̃': {'endéans'},
 'atatɔ̃': {'à tâtons'},
 'kɔsmos': {'cosmos'},
 'ekʁulje': {'écrouler'},
 'aʁozɛ': {'arroser'},
 'metafɔʁizəʁe': {'métaphoriser'},
 'nɛtʁɛ': {'naitraient', 'naitrais', 'naitrait', 'naître'},
 'ʒyt': {'jute', 'juter'},
 'mɛ̃tna': {'maintenant'},
 'ʃiʃa': {'chicha'},
 'kɔ̃bativ': {'combatif', 'combattif'},
 'tɛʁminɛʁ': {'terminer'},
 'ʁədizɑ̃': {'redire'},
 'filipɛ̃': {'philippin'},
 'ɛ̃sybɔʁdɔne': {'insubordonné'},
 'pɔgɔt': {'pogote', 'pogotent', 'pogotte'},
 'bufəʁɛ': {'bouffer'},
 'modyle': {'moduler'},
 'deʃaʁʒɛ': {'décharger'},
 'favoʁizɛ': {'favoriser'},
 'inyksyk': {'inuksuk'},
 'kɔ̃paʁɛs': {'comparaître'},
 'vjabl': {'viable'},
 'sinefilik': {'cinéphilique'},
 'bʁakonɛ': {'braconner'},
 'kedival': {'khédival'},
 'skalpəʁa': {'scalper'},
 'ɛskaʁp': {'escarpe'},
 'efɛʁvɛsɑ̃': {'effervescent'},
 'ʒɔʁdanjɛ̃': {'jordanien'},
 'kalifikatif': {'qualificatif'},
 'kʁijɛ': {'crier'},
 'paʁadəʁje': {'parader'},
 'makʁoekɔnɔmik': {'macro-économique', 'macroéconomique'},
 'lɛtʁin': {'lettrine'},
 'najtklœb': {'night-club', 'nightclub', 'nightclubs'},
 'leʒislatœʁ': {'législateur'},
 'lɛmiŋ': {'lemming'},
 'ʁevɛjɔnəʁe': {'réveillonner'},
 'sitɔkʁom': {'cytochrome'},
 'vɛ̃': {'vain', 'venir', 'vin', 'vingt', 'vingts'},
 'apsɔʁbe': {'absorber', 'absorbé'},
 'bʁɑ̃t': {'brante'},
 'sud': {'soude', 'souder'},
 'telefaks': {'téléfax', 'téléfaxer'},
 'pufjas': {'pouffiasse', 'poufiasse'},
 'badiʒɔnje': {'badigeonner'},
 'vizitɛ': {'visiter'},
 'wuʃu': {'wushu'},
 'buzijəʁɛ': {'bousiller'},
 'dɑ̃təle': {'denteler', 'dentelé'},
 'sijɔnəʁɔ̃': {'sillonner'},
 'etydje': {'étudier', 'étudié'},
 'ʁədɔnəʁɛ': {'redonner'},
 'minim': {'minime'},
 'gobɑ̃': {'gober'},
 'ʁɛptil': {'reptile'},
 'pʁezyme': {'présumer', 'présumé'},
 'ʁəmiks': {'remixer'},
 'mask': {'masque', 'masquer'},
 'ɑ̃bʁasɛʁ': {'embrasser'},
 'gatəʁɔ̃': {'gâter'},
 'ʁəmɔ̃tɛ': {'remonter'},
 'kɔ̃sɔməʁɛ': {'consommer'},
 'syksedɛʁ': {'succéder'},
 'degene': {'dégainer'},
 'bavaʁd': {'bavard', 'bavarder'},
 'telɛskopik': {'télescopique'},
 'otoʁize': {'autoriser', 'autorisé'},
 'ɛ̃tɛʁsɛpsjɔ̃': {'interception'},
 'peʃɛ': {'pécher'},
 'kɔ̃fyzjɔne': {'confusionné'},
 'elɑ̃sɛ': {'élancer'},
 'pilote': {'piloter'},
 'ʁəpɑ̃tiʁ': {'repentir'},
 'koɛ̃sida': {'coïncider'},
 'pɔʁtəfœj': {'portefeuille'},
 'lu': {'louer', 'loup'},
 'olɛ̃p': {'olympe'},
 'wo': {'wau', 'waus'},
 'dezagʁeʒʁɔ̃': {'désagréger'},
 'ovœʁklokɑ̃': {'overclocker'},
 'dedikas': {'dédicace', 'dédicacer'},
 'emɔstatik': {'hémostatique'},
 'ɑ̃tifeminist': {'anti-féministe', 'antiféministe'},
 'buʁ': {'bour', 'boure', 'bourg', 'bourre', 'bourrer'},
 'idʁoelɛktʁik': {'hydro-électrique', 'hydroélectrique'},
 'batəlje': {'batelier'},
 'deʃɛnɔ̃': {'déchaîner'},
 'nikɛ': {'niquer'},
 'ʒyʁam': {'jurer'},
 'aleʃɑ̃': {'alléchant', 'allécher'},
 'sivilize': {'civiliser', 'civilisé'},
 'ʃaviʁ': {'chavirer'},
 'bloke': {'bloquer', 'bloqué'},
 'ɛ̃stʁɥiʁe': {'instruire'},
 'tasit': {'tacite'},
 'aida': {'haïda'},
 'kɑ̃bʁijɔləʁɔ̃': {'cambrioler'},
 'otistik': {'autistique'},
 'ɔʁganizm': {'organisme'},
 'ʁefleʃiʁ': {'réfléchir'},
 'ɑ̃pʁœtœʁ': {'emprunteur'},
 'ɛ̃tybe': {'intuber'},
 'degutɛ': {'dégoutaient', 'dégoutais', 'dégoutait', 'dégoutter', 'dégoûter'},
 'dʁɛsœʁ': {'dresseur'},
 'ʁəstʁyktyʁe': {'restructurer'},
 'tʁab': {'trabe'},
 'blɛ̃de': {'blinder', 'blindé'},
 'sɥivi': {'suivi', 'suivre'},
 'swaɲɑ̃': {'soignant', 'soigner'},
 'lakanjɛ̃': {'lacanien'},
 'mikto': {'michto'},
 'kaʁa': {'cara', 'carat', 'carrer', 'quarrer'},
 'dezɛʁbəʁe': {'désherber'},
 'luʃœʁ': {'loucheur'},
 'ɔksiʒenɑ̃': {'oxygéner'},
 'kɔ̃disjonɛ': {'conditionner'},
 'tʁotinəmɑ̃': {'trottinement'},
 'pɔlaʁizɑ̃': {'polarisant', 'polariser'},
 'nevys': {'naevus', 'nævus'},
 'oʁoʁal': {'auroral'},
 'ekut': {'écoute', 'écouter'},
 'ʁeedykatœʁ': {'rééducateur'},
 'bʁɑ̃ʃəʁɔ̃': {'brancher'},
 'ajaj': {'aye-aye'},
 'fʁɑ̃size': {'franciser'},
 'seʁonegatif': {'séronégatif'},
 'sɛʁtifiʁɔ̃': {'certifier'},
 'kɔʁsɛʁ': {'corsaire', 'corser'},
 'ʁəliʒjø': {'religieux'},
 'ʁɥisəle': {'ruisseler'},
 'glapisɑ̃t': {'glapissant'},
 'ʁatifje': {'ratifier'},
 'sɔʁ': {'saur', 'sore', 'sors', 'sort', 'sortir'},
 'ʁeasiɲ': {'réassigner'},
 'datje': {'dater', 'dattier'},
 'disimyle': {'dissimuler', 'dissimulé'},
 'ʁyʁal': {'rural'},
 'ɑ̃ʁobe': {'enrober', 'enrobé'},
 'tʁezoʁjepɛjœʁ': {'trésorier-payeur'},
 'debʁujɔ̃': {'débrouiller'},
 'dʒɔgɛ': {'jogger'},
 'kato': {'catho', 'cato'},
 'imynoloʒi': {'immunologie'},
 'ʁɔdjɔm': {'rhodium'},
 'avuʁa': {'avouer'},
 'degutɑ̃t': {'dégoutante', 'dégoutantes', 'dégouttant', 'dégoûtant'},
 'akɔ̃pli': {'accompli', 'accomplir'},
 'paʁafudʁ': {'parafoudre'},
 'depəsɑ̃': {'dépecer'},
 'ʃwaz': {'choises'},
 'ʁədate': {'redater'},
 'pɛ̃tyʁlyʁ': {'peinturlurer'},
 'ʁakɔʁdɑ̃': {'raccorder'},
 'kateʃɛz': {'catéchèse'},
 'aleluja': {'alleluia', 'alleluias', 'alléluia'},
 'twit': {'tweet',
  'tweete',
  'tweetent',
  'tweetes',
  'tweets',
  'twit',
  'twitte',
  'twittent',
  'twittes'},
 'kɔ̃sym': {'consume', 'consumer'},
 'paʁəmɑ̃': {'parement'},
 'meteɔʁɔlɔʒikmɑ̃': {'météorologiquement'},
 'fotogʁafi': {'photographie', 'photographier'},
 'tʁɔ̃pɛt': {'trompeter', 'trompette', 'trompète'},
 'kuvʁiʁɛ': {'couvrir'},
 'djatome': {'diatomée'},
 'diskylpəʁɛ': {'disculper'},
 'vjɛ̃dʁijɔ̃': {'venir'},
 'apaʁɛs': {'apparaître', 'apparesse'},
 'dekolɔʁ': {'décolorer'},
 'sotijəʁe': {'sautiller'},
 'apaʁɛtʁɛ': {'apparaitraient', 'apparaitrais', 'apparaitrait', 'apparaître'},
 'maɲ': {'magner'},
 'tuʁmɑ̃təʁɛ': {'tourmenter'},
 'mizəʁɔ̃': {'miser'},
 'dɑ̃ta': {'denter'},
 'abyze': {'abuser', 'abusé'},
 'dezɑ̃lize': {'désenliser'},
 'ɑ̃pɔʁtɛ': {'emporter'},
 'nasjɔnalsɔsjalist': {'national-socialistes'},
 'ʁɛ̃gaʁdiz': {'ringardise', 'ringardiser'},
 'destʁyktibl': {'destructible'},
 'koteʁizje': {'cautériser'},
 'tənaje': {'tenailler'},
 'dɑ̃ti': {'denti'},
 'nykleɔtid': {'nucléotide'},
 'ʃaʁətɔ̃': {'charreton'},
 'tɑ̃te': {'tenter', 'tenté'},
 'ʃɛlti': {'sheltie'},
 'bʁuje': {'brouiller', 'brouillé'},
 'anyle': {'annuler', 'annulé'},
 'fasɔnabl': {'façonnable'},
 'my': {'mouvoir', 'mu', 'mue', 'muer', 'mû', 'mûe', 'mûs'},
 'kɔ̃fiʁmɛʁ': {'confirmer'},
 'degulinəʁe': {'dégouliner'},
 'sinonim': {'synonyme'},
 'seksolɔg': {'sexologue'},
 'ʁaləbɔl': {'ras-le-bol'},
 'ʁegʁɛs': {'régresser'},
 'tiʁəʁɔ̃': {'tirer'},
 'eklataʒ': {'éclatage'},
 'kaʃətɔ̃': {'cacheton'},
 'dəvizɛ': {'deviser'},
 'tako': {'tacaud', 'tacco', 'taco', 'tacot'},
 'ʃuʁe': {'chourer', 'chourrer', 'chourré'},
 'pedaləʁa': {'pédaler'},
 'dinɛ': {'dinaient', 'dinais', 'dinait', 'dîner'},
 'afaləʁe': {'affaler'},
 'devalize': {'dévaliser'},
 'kɔ̃fiʁɛ': {'confier', 'confire'},
 'kʁapyləʁi': {'crapulerie'},
 'ɛgzɔsa': {'exaucer'},
 'ɔʁbit': {'orbite', 'orbiter'},
 'flo': {'flo', 'floe', 'flot', 'flow', 'flows'},
 'njɛs': {'nièce'},
 'ʁəgɑ̃bad': {'regambade'},
 'defigyʁasjɔ̃': {'défiguration'},
 'atʁapwaʁ': {'attrapoire'},
 'sufʁɑ̃t': {'souffrant'},
 'dezidʁate': {'déshydrater', 'déshydraté'},
 'plɛdabl': {'plaidable'},
 'kɔ̃plis': {'complice'},
 'apʁete': {'apprêter', 'apprêté'},
 'nɔʁm': {'norme'},
 'tɛʁe': {'taire', 'terrer'},
 'titylaʁize': {'titulariser', 'titularisé'},
 'petʁodɔlaʁ': {'pétro-dollar'},
 'buʁlɛ̃gœʁ': {'bourlingueur'},
 'ɛ̃sɛstyøzmɑ̃': {'incestueusement'},
 'pɛʁmyt': {'permuter'},
 'ʁetʁɔstɛʁnal': {'rétrosternal', 'rétrosternale', 'rétrosternales'},
 'aksidɑ̃te': {'accidenter', 'accidenté'},
 'buma': {'boumer'},
 'dʒam': {'jam', 'jamme', 'jammes'},
 'kategɔʁizasjɔ̃': {'catégorisation'},
 'ʃapaʁde': {'chaparder'},
 'ɔsteokaʁtilaʒinøz': {'ostéo-cartilagineuse'},
 'asfiksjɑ̃': {'asphyxiant', 'asphyxier'},
 'petɔ̃kl': {'pétoncle'},
 'vɛ̃ky': {'vaincre', 'vaincu'},
 'aʒiʁa': {'agir'},
 'bɔjkɔta': {'boycotter'},
 'ʁɛspiʁasjɔ̃': {'respiration'},
 'savwaʁfɛʁ': {'savoir-faire'},
 'elaʁʒisɛ': {'élargir'},
 'pɛʁ': {'pair', 'paire', 'perdre', 'pers', 'père'},
 'mɑ̃sɔ̃ʒ': {'mensonge'},
 'gaʃəʁɔ̃': {'gâcher'},
 'tolɥɛn': {'toluène'},
 'pʁɛstatɛʁ': {'prestataire'},
 'iʁepaʁabl': {'irréparable'},
 'ʁəpaʁti': {'repartie', 'repartir'},
 'abʁytisɑ̃': {'abrutir', 'abrutissant'},
 'ʁeɛ̃seʁe': {'réinsérer'},
 'kloʃaʁ': {'clochard'},
 'sybʒɛktiv': {'subjectif', 'subjectiver'},
 'dezaktive': {'désactiver', 'désactivée'},
 'ne': {'naître', 'ne', 'ney', 'nez', 'né'},
 'komis': {'comice'},
 'ɔ̃biliko': {'ombilical'},
 'damaʒ': {'damage'},
 'pilonœʁ': {'pilonneur'},
 'kʁɔkœʁ': {'croqueur'},
 'blakliste': {'blacklister',
  'blacklistez',
  'blacklisté',
  'blacklistée',
  'blacklistées',
  'blacklistés'},
 'ʁetʁofyze': {'rétrofusée'},
 'apœʁe': {'apeurer', 'apeuré'},
 'pnømɔnɛktɔmi': {'pneumonectomie'},
 'pʁesɑ̃te': {'pressentir'},
 'mɑ̃dʃu': {'mandchou'},
 'kɔ̃tʁibɥe': {'contribuer'},
 'paʁaʃytəʁɛ': {'parachuter'},
 'gɑ̃gʁɛn': {'gangrener', 'gangrène'},
 'taʁt': {'tarte', 'tartent'},
 'videoklip': {'vidéo-clip', 'vidéoclip'},
 'aʒɑ̃se': {'agencer'},
 'epaʁ': {'épare', 'épars', 'épart'},
 'kalifiʁje': {'qualifier'},
 'plɑ̃ke': {'planquer', 'planquè', 'planqué', 'planquées'},
 'ʒɑ̃tijɔm': {'gentilhomme', 'gentilhommes'},
 'lav': {'lav', 'lave', 'laver'},
 'kɔ̃tʁmɛtʁ': {'contremaitre', 'contremaitres'},
 'kɔ̃kyʁɑ̃s': {'concurrence', 'concurrencer'},
 'twɛʁk': {'twerk', 'twerke', 'twerkes'},
 'gʁɛ̃pɛ': {'grimper'},
 'gɛ': {'gai', 'gay', 'guet'},
 'ʃosəʁɛ': {'chausser'},
 'ɛ̃tɛʁpoze': {'interposer', 'interposé'},
 'ɛ̃tɛʁvju': {'interview', 'interviewer'},
 'ɔ̃gʁwa': {'hongrois'},
 'ʃizɛl': {'chisel'},
 'deboʃe': {'débaucher', 'débauché'},
 'koite': {'coïter'},
 'diplomatik': {'diplomatique'},
 'laʁmwa': {'larmoyer'},
 'sekstɑ̃': {'sextant'},
 'negʁijɔ̃': {'négrillon'},
 'aʒiʁɔ̃': {'agir'},
 'sityʁɛ': {'situer'},
 'fɛsɔ̃': {'fesser'},
 'ʁeɛ̃sɛʁsjɔ̃': {'réinsertion'},
 'ɛ̃sonoʁize': {'insonoriser'},
 'ɛtnɔlɛ̃gɥistik': {'ethnolinguistique'},
 'pʁomɛnəʁɛ': {'promener'},
 'imynodepʁime': {'immunodéprimé'},
 'eteʁoʒeneite': {'hétérogénéité'},
 'epaʁɲe': {'épargner'},
 'evolɥe': {'évoluer', 'évolué'},
 'pʁɛskʁi': {'prescrire'},
 'ʁevizɑ̃': {'réviser'},
 'bɛtifi': {'bêtifier'},
 'ɛ̃tɛʁpʁetɔ̃': {'interpréter'},
 'makijəʁɛ': {'maquiller'},
 'kalifiʁɛ': {'qualifier'},
 'bʁɑ̃': {'bran', 'brand'},
 'kɔstaʁikɛn': {'costaricain'},
 'diskylpəʁa': {'disculper'},
 'bʁosɛ': {'brosser'},
 'lise': {'lisser', 'lissé', 'lycée'},
 'kɔ̃fli': {'conflit'},
 'fɔʁʒəʁjɔ̃': {'forger'},
 'ɛskiʁ': {'esquire'},
 'ɔʁnəmɑ̃te': {'ornementer'},
 'paʁtaʒ': {'partage', 'partager'},
 'komɛʁsjal': {'commercial'},
 'pʁepaʁəʁɛ': {'préparer'},
 'ɛ̃dolɑ̃': {'indolent'},
 'soliv': {'solive'},
 'kɔlimate': {'collimater'},
 'mɛnəʁɛ': {'mener'},
 'dɛsalmɑ̃': {'dessalement'},
 'balɑ̃': {'badlands', 'balan', 'balants', 'ballant', 'baller'},
 'liminal': {'liminal'},
 'kʁaʃɛ': {'cracher', 'crasher'},
 'ʁaʁefjɛ': {'raréfier'},
 'pʁodɥizjɔ̃': {'produire'},
 'pwavʁɑ̃': {'poivrer'},
 'ʃiʁe': {'chier', 'chirai', 'chirer', 'chiré'},
 'kadʁij': {'quadrille', 'quadriller'},
 'maʁmonɛ': {'marmonner'},
 'niktalɔp': {'nyctalope'},
 'demoʁalizɛ': {'démoraliser'},
 'devwalɛ': {'dévoiler'},
 'puʁisɛ': {'pourrir'},
 'etɛʁnɥɛ': {'éternuer'},
 'ɛgzɑ̃plaʁite': {'exemplarité'},
 'pʁijɔʁizasjɔ̃': {'priorisation'},
 'benefisjɛ': {'bénéficier'},
 'ɛksit': {'exciter'},
 'spymø': {'spumeux'},
 'fʁətɛ̃': {'fretin'},
 'miləfœj': {'millefeuille'},
 'epʁiz': {'éprendre', 'épris'},
 'kɑ̃tifje': {'quantifier', 'quantifié'},
 'pyʁitɛn': {'puritain'},
 'kaʁaktɛʁ': {'caractere',
  'caracteres',
  'caractère',
  'charactère',
  'charactères'},
 'asɑ̃blɛ': {'assembler'},
 'ɛ̃kɔ̃sjɑ̃': {'inconscient'},
 'anaʁkosɛ̃dikalizm': {'anarcho-syndicalisme'},
 'pʁepaʁasjɔ̃': {'préparation'},
 'ʁadjogʁafje': {'radiographier'},
 'piʁoman': {'pyromane'},
 'sapœʁpɔ̃pje': {'sapeur-pompier'},
 'asasina': {'assassinat', 'assassiner'},
 'dømiveʁite': {'demi-vérité'},
 'ʁetʁosedʁe': {'rétrocéder'},
 'suɑ̃plwaje': {'sous-employer'},
 'ɔtofekɔ̃de': {'autofécondé'},
 'sœl': {'seul', 'seule'},
 'bylbø': {'bulbeux'},
 'ɛkstʁovɛʁti': {'extroverti'},
 'bagaʁøz': {'bagarreur'},
 'epɥize': {'épuiser', 'épuisé'},
 'ʁɛsplɑ̃dis': {'resplendir'},
 'eʁode': {'éroder', 'érodé'},
 'ʁafin': {'raffiner'},
 'abetisəmɑ̃': {'abêtissement'},
 'ɛ̃spiʁe': {'inspirer', 'inspiré'},
 'ʁɑ̃fɔʁ': {'renfort'},
 'tapin': {'tapiner'},
 'tɑ̃tin': {'tantine'},
 'gʁomɛləmɑ̃': {'grommellement'},
 'ɑ̃kuʁaʒəʁɛ': {'encourager'},
 'sutʁɛt': {'sous-traiter'},
 'laseʁe': {'lacérer', 'lacéré'},
 'ob': {'aube'},
 'aʁkadjɛ̃': {'arcadien'},
 'ɛ̃pʁesjonɑ̃': {'impressionnant', 'impressionner'},
 'ʁund': {'round'},
 'nekʁoz': {'nécrose', 'nécroser'},
 'delatʁis': {'délateur'},
 'tʁagɔpɑ̃': {'tragopan'},
 'ʃinuk': {'chinook'},
 'ɑ̃d': {'andes', 'hand'},
 'ʁeʒjonal': {'régional'},
 'kʁisɑ̃': {'crissants', 'crisser'},
 'faʃist': {'fasciste'},
 'lemyʁjɛ̃': {'lémurien'},
 'manigɑ̃sɛ': {'manigancer'},
 'fwinaʁ': {'fouinard'},
 'basɛt': {'bassette'},
 'detɛʁɔ̃': {'déterrer'},
 'ʁamɛn': {'ramen', 'ramener'},
 'ʁəkɔfʁ': {'recoffre'},
 'ipokʁit': {'hypocrite'},
 'detʁɛs': {'détresse', 'détresser'},
 'bagaʒist': {'bagagiste'},
 'ʁəkɛ̃kəʁɛ': {'requinquer'},
 'paʁaʃəve': {'parachever'},
 'stilɔid': {'styloïde'},
 'eʃɑ̃tijɔnɛ': {'échantillonner'},
 'matøz': {'mateur', 'matheux'},
 'baʁde': {'barder'},
 'senogʁafik': {'scénographique'},
 'ʁigɔl': {'rigole', 'rigoler'},
 'kik': {'kick', 'quick'},
 'sodomizɛ': {'sodomiser'},
 'dɛkstʁəmɑ̃': {'dextrement'},
 'ɛ̃dy': {'indu'},
 'pœnʃiŋbɔl': {'punching-ball'},
 'dyʁsisœʁ': {'durcisseur'},
 'pozisjɔn': {'positionner'},
 'ymidje': {'humidié'},
 'ʁapsodi': {'rapsodie', 'rhapsodie'},
 'ʒoni': {'jauni', 'jaunir'},
 'sysyʁɛ': {'susurrer'},
 'naftalɛn': {'naphtalène'},
 'ɛkspɔʁtəʁɔ̃': {'exporter'},
 'ameljɔʁəʁɔ̃': {'améliorer'},
 'gʁivətɔ̃': {'griveton'},
 'fʁɔ̃tjɛʁ': {'frontière'},
 'tɔʁd': {'tordre'},
 'koɑ̃tʁəpʁiz': {'coentreprise'},
 'kuʁjɛl': {'courriel'},
 'ʁapɔʁte': {'rapporter', 'rapporté'},
 'vasij': {'vaciller'},
 'baʁak': {'baraque', 'baraquer', 'barraque', 'barraques'},
 'venjɛl': {'véniel'},
 'ly': {'lire', 'lu', 'lut'},
 'kolostomi': {'colostomie'},
 'pɑ̃səʁɔ̃': {'panser', 'penser'},
 'bʁɔk': {'broque'},
 'plije': {'plier', 'plié'},
 'akɔ̃paɲəʁa': {'accompagner'},
 'gaɲɑ̃': {'gagnant', 'gagner'},
 'ɛgzɛʁsəʁje': {'exercer'},
 'menisk': {'ménisque'},
 'ɑ̃titɛz': {'antithèse'},
 'polɛn': {'pollen'},
 'ʃɔvɛ̃': {'chauvin'},
 'ɛgzilɛ': {'exiler'},
 'anaeʁɔbi': {'anaérobie'},
 'fʁatɛʁnizje': {'fraterniser'},
 'ʁesidivɑ̃': {'récidivant'},
 'avɑ̃t': {'avante'},
 'ʁədʁesje': {'redresser'},
 'ʁevɛje': {'réveiller'},
 'ʁəsezisje': {'ressaisir'},
 'gʁɔ̃dəʁɛ': {'gronder'},
 'detaje': {'détailler', 'détaillé'},
 'aglytine': {'agglutiner', 'aglutinés'},
 'ʁavalɛ': {'ravaler'},
 'atɛst': {'attester'},
 'epʁɑ̃dʁɛ': {'éprendre'},
 'tʁɔle': {'trollé'},
 'gʁifwaʁ': {'griffoir', 'griffoirs'},
 'pɔmade': {'pommader', 'pommadé'},
 'ʁələvœʁ': {'releveur'},
 'ʃəminəʁɔ̃': {'cheminer'},
 'kulak': {'koulak'},
 'pɑ̃sy': {'pansu'},
 'diktatœʁ': {'dictateur'},
 'dezɔnɔʁəʁje': {'déshonorer'},
 'ʁɔ̃fləʁɛ': {'ronfler'},
 'ʃaʁbɔn': {'charbonner'},
 'sɔ̃dam': {'sonder'},
 'bœge': {'bugger', 'buggé', 'buguer', 'bugué'},
 'aeʁɔdinamikmɑ̃': {'aérodynamiquement'},
 'emiptɛʁ': {'hémiptère'},
 'ʁətapise': {'retapisser'},
 'ʁəkony': {'reconnaître', 'reconnu'},
 'tʁijɔ̃fɛʁ': {'triompher'},
 'ʁam': {'ram', 'rame', 'ramer', 'rams'},
 'bɛta': {'bêta'},
 'fʁit': {'frite', 'friter', 'fritte', 'fritter', 'frîtes'},
 'anɔksemi': {'anoxémie'},
 'pastœʁizəʁa': {'pasteuriser'},
 'kɔʒita': {'cogiter'},
 'lɑ̃ga': {'lengua'},
 'dəʁəʃɛf': {'derechef'},
 'ɑ̃bʁwazi': {'ambroisie'},
 'ʁədəmɑ̃de': {'redemander'},
 'sjeʁɛ': {'seoir'},
 'adɔptəʁje': {'adopter'},
 'dɛsuʃaʒ': {'dessouchage'},
 'aksɛdəʁa': {'accèdera', 'accèderas'},
 'ʁəmiʁ': {'remettre'},
 'sɔnəʁɔ̃': {'sonner'},
 'ɑ̃pilɔ̃': {'empiler'},
 'apaʁtjɛ̃dʁɛ': {'appartenir'},
 'ʁəbwaʁ': {'reboire'},
 'pasjətəʁe': {'patienter'},
 'gygys': {'gugusse'},
 'ʁavaʒ': {'ravage', 'ravager'},
 'kɔ̃siste': {'consister'},
 'diʁiʒəʁje': {'diriger'},
 'gʁafit': {'graphite', 'graphiter'},
 'alege': {'alléguer'},
 'ʁəbulɔne': {'reboulonner'},
 'adipozite': {'adiposité'},
 'dəmikø': {'demi-queue'},
 'kude': {'couder', 'coudé', 'coudée'},
 'ʁadjogɔnjometʁik': {'radiogoniométrique'},
 'skizɔfʁeni': {'schizophrénie'},
 'djamɑ̃': {'diamans', 'diamant'},
 'gaɲəʁa': {'gagner'},
 'vwale': {'voiler', 'voilé'},
 'delisjøz': {'délicieux'},

In [113]:
words=dfLex4["3_Phono_IPA"].tolist()
words=[str(w) for w in words]
words

['pɔlak',
 'dispʁopɔʁsjone',
 'maʁʒe',
 'sibɛʁnetisjɛ̃',
 'akyzɔ̃',
 'fɛʁlaʒ',
 'sezaʁjɛ̃',
 'ofisjɑ̃',
 'ɛ̃kyltivabl',
 'apsɔʁbje',
 'puʁɔ̃',
 'ɑ̃tʁətyʁɛ',
 'dezeʁitɛ',
 'duv',
 'atiz',
 'ʒap',
 'desule',
 'kniboʁd',
 'adubje',
 'efɛktɥe',
 'ebʁɥit',
 'ʁəsɛʁ',
 'ʁesit',
 'mizɛ',
 'ʁəkupe',
 'neʁeis',
 'fɔ̃səʁɛ',
 'dula',
 'ʁədiʁiʒe',
 'fɛso',
 'agʁavəʁa',
 'nitʃeɛn',
 'dezɔkyltɑ̃',
 'dekuvʁiʁɛ',
 'kɔ̃tuʁne',
 'dekuvʁ',
 'ʁətɑ̃dy',
 'dekole',
 'depɔzɑ̃',
 'djeʒɛz',
 'tyʁʒesɑ̃',
 'ʁapœʁ',
 'desy',
 'gʁɑ̃tɔ̃kl',
 'pozitif',
 'seʁigʁafi',
 'ʁəseziʁe',
 'kono',
 'bosɥe',
 'fjɛlø',
 'abatʁɛ',
 'klwazɔnəʁɛ',
 'pylyle',
 'kakawɛt',
 'ekaʁte',
 'ʁezɛʁv',
 'mɔnɔdimɑ̃sjɔnɛl',
 'bikaʁe',
 'asɛje',
 'istɔʁi',
 'kalsɔ̃',
 'deniʃam',
 'bʁoʃɛt',
 'nonaʒenɛʁ',
 'leʒɛʁəte',
 'atɑ̃sjɔna',
 'sɛʁvɔ̃',
 'paʁɑ̃t',
 'depʁesje',
 'peplɔm',
 'ɛgmaʁin',
 'dezeʁite',
 'psikɔmɛtʁ',
 'buʁiko',
 'ʁaʃɛtəʁɛ',
 'kavɛʁnøz',
 'kʁijoʒenize',
 'mytine',
 'dʁap',
 'ʁəpɛ̃tyʁ',
 'kopʁɔdɥi',
 'mazinjɛ̃',
 'tyʁlypinɛ',
 'mɔtilite',
 'pʁezɑ̃tasjɔ̃',
 'fʁɛsk',
 'ɔʁlɔ̃',
 'epinø',
 'bum',
 'ɑ̃ʃɑ̃təmɑ̃',
 'fʁijɑ̃',
 'fʁaktyʁe',
 'vilipɑ̃de',
 'kaʁnatik',
 'bɛɲ',
 'peizaʒɛʁ',
 'pɔlitɔlɔg',
 'pwasɔ̃klun',
 'paʁiʁɛ',
 'vizjɔnəʁa',
 'ʁəlɔkalize',
 'utʁe',
 'aleʒe',
 'ɛskabo',
 'dʁagəʁje',
 'nøʁɔpʁɔtɛksjɔ̃',
 'distɑ̃se',
 'ʃasəʁa',
 'ʁuj',
 'ɛ̃pʁesjonabl',
 'dezilyzjɔne',
 'debaʁa',
 'syzidike',
 'temwaɲe',
 'ɑ̃kɛte',
 'pɛləte',
 'ɛgzɛʁsɛʁ',
 'ʁevɔlysjɔnaʁist',
 'ɑ̃deɑ̃',
 'atatɔ̃',
 'kɔsmos',
 'ekʁulje',
 'aʁozɛ',
 'metafɔʁizəʁe',
 'nɛtʁɛ',
 'ʒyt',
 'mɛ̃tna',
 'ʃiʃa',
 'kɔ̃bativ',
 'tɛʁminɛʁ',
 'ʁədizɑ̃',
 'filipɛ̃',
 'ɛ̃sybɔʁdɔne',
 'pɔgɔt',
 'bufəʁɛ',
 'modyle',
 'deʃaʁʒɛ',
 'favoʁizɛ',
 'inyksyk',
 'kɔ̃paʁɛs',
 'vjabl',
 'sinefilik',
 'bʁakonɛ',
 'kedival',
 'skalpəʁa',
 'ɛskaʁp',
 'efɛʁvɛsɑ̃',
 'ʒɔʁdanjɛ̃',
 'kalifikatif',
 'kʁijɛ',
 'paʁadəʁje',
 'makʁoekɔnɔmik',
 'lɛtʁin',
 'najtklœb',
 'leʒislatœʁ',
 'lɛmiŋ',
 'ʁevɛjɔnəʁe',
 'sitɔkʁom',
 'vɛ̃',
 'apsɔʁbe',
 'bʁɑ̃t',
 'sud',
 'telefaks',
 'pufjas',
 'badiʒɔnje',
 'vizitɛ',
 'wuʃu',
 'buzijəʁɛ',
 'dɑ̃təle',
 'sijɔnəʁɔ̃',
 'etydje',
 'ʁədɔnəʁɛ',
 'minim',
 'gobɑ̃',
 'ʁɛptil',
 'pʁezyme',
 'ʁəmiks',
 'mask',
 'ɑ̃bʁasɛʁ',
 'gatəʁɔ̃',
 'ʁəmɔ̃tɛ',
 'kɔ̃sɔməʁɛ',
 'syksedɛʁ',
 'degene',
 'bavaʁd',
 'telɛskopik',
 'otoʁize',
 'ɛ̃tɛʁsɛpsjɔ̃',
 'peʃɛ',
 'kɔ̃fyzjɔne',
 'elɑ̃sɛ',
 'pilote',
 'ʁəpɑ̃tiʁ',
 'koɛ̃sida',
 'pɔʁtəfœj',
 'lu',
 'olɛ̃p',
 'wo',
 'dezagʁeʒʁɔ̃',
 'ovœʁklokɑ̃',
 'dedikas',
 'emɔstatik',
 'ɑ̃tifeminist',
 'buʁ',
 'idʁoelɛktʁik',
 'batəlje',
 'deʃɛnɔ̃',
 'nikɛ',
 'ʒyʁam',
 'aleʃɑ̃',
 'sivilize',
 'ʃaviʁ',
 'bloke',
 'ɛ̃stʁɥiʁe',
 'tasit',
 'aida',
 'kɑ̃bʁijɔləʁɔ̃',
 'otistik',
 'ɔʁganizm',
 'ʁefleʃiʁ',
 'ɑ̃pʁœtœʁ',
 'ɛ̃tybe',
 'degutɛ',
 'dʁɛsœʁ',
 'ʁəstʁyktyʁe',
 'tʁab',
 'blɛ̃de',
 'sɥivi',
 'swaɲɑ̃',
 'lakanjɛ̃',
 'mikto',
 'kaʁa',
 'dezɛʁbəʁe',
 'luʃœʁ',
 'ɔksiʒenɑ̃',
 'kɔ̃disjonɛ',
 'tʁotinəmɑ̃',
 'pɔlaʁizɑ̃',
 'nevys',
 'oʁoʁal',
 'ekut',
 'ʁeedykatœʁ',
 'bʁɑ̃ʃəʁɔ̃',
 'ajaj',
 'fʁɑ̃size',
 'seʁonegatif',
 'sɛʁtifiʁɔ̃',
 'kɔʁsɛʁ',
 'ʁəliʒjø',
 'ʁɥisəle',
 'glapisɑ̃t',
 'ʁatifje',
 'sɔʁ',
 'ʁeasiɲ',
 'datje',
 'disimyle',
 'ʁyʁal',
 'ɑ̃ʁobe',
 'tʁezoʁjepɛjœʁ',
 'debʁujɔ̃',
 'dʒɔgɛ',
 'kato',
 'imynoloʒi',
 'ʁɔdjɔm',
 'avuʁa',
 'degutɑ̃t',
 'akɔ̃pli',
 'paʁafudʁ',
 'depəsɑ̃',
 'ʃwaz',
 'ʁədate',
 'pɛ̃tyʁlyʁ',
 'ʁakɔʁdɑ̃',
 'kateʃɛz',
 'aleluja',
 'twit',
 'kɔ̃sym',
 'paʁəmɑ̃',
 'meteɔʁɔlɔʒikmɑ̃',
 'fotogʁafi',
 'tʁɔ̃pɛt',
 'kuvʁiʁɛ',
 'djatome',
 'diskylpəʁɛ',
 'vjɛ̃dʁijɔ̃',
 'apaʁɛs',
 'dekolɔʁ',
 'sotijəʁe',
 'apaʁɛtʁɛ',
 'maɲ',
 'tuʁmɑ̃təʁɛ',
 'mizəʁɔ̃',
 'dɑ̃ta',
 'abyze',
 'dezɑ̃lize',
 'ɑ̃pɔʁtɛ',
 'nasjɔnalsɔsjalist',
 'ʁɛ̃gaʁdiz',
 'destʁyktibl',
 'koteʁizje',
 'tənaje',
 'dɑ̃ti',
 'nykleɔtid',
 'ʃaʁətɔ̃',
 'tɑ̃te',
 'ʃɛlti',
 'bʁuje',
 'anyle',
 'fasɔnabl',
 'my',
 'kɔ̃fiʁmɛʁ',
 'degulinəʁe',
 'sinonim',
 'seksolɔg',
 'ʁaləbɔl',
 'ʁegʁɛs',
 'tiʁəʁɔ̃',
 'eklataʒ',
 'kaʃətɔ̃',
 'dəvizɛ',
 'tako',
 'ʃuʁe',
 'pedaləʁa',
 'dinɛ',
 'afaləʁe',
 'devalize',
 'kɔ̃fiʁɛ',
 'kʁapyləʁi',
 'ɛgzɔsa',
 'ɔʁbit',
 'flo',
 'njɛs',
 'ʁəgɑ̃bad',
 'defigyʁasjɔ̃',
 'atʁapwaʁ',
 'sufʁɑ̃t',
 'dezidʁate',
 'plɛdabl',
 'kɔ̃plis',
 'apʁete',
 'nɔʁm',
 'tɛʁe',
 'titylaʁize',
 'petʁodɔlaʁ',
 'buʁlɛ̃gœʁ',
 'ɛ̃sɛstyøzmɑ̃',
 'pɛʁmyt',
 'ʁetʁɔstɛʁnal',
 'aksidɑ̃te',
 'buma',
 'dʒam',
 'kategɔʁizasjɔ̃',
 'ʃapaʁde',
 'ɔsteokaʁtilaʒinøz',
 'asfiksjɑ̃',
 'petɔ̃kl',
 'vɛ̃ky',
 'aʒiʁa',
 'bɔjkɔta',
 'ʁɛspiʁasjɔ̃',
 'savwaʁfɛʁ',
 'elaʁʒisɛ',
 'pɛʁ',
 'mɑ̃sɔ̃ʒ',
 'gaʃəʁɔ̃',
 'tolɥɛn',
 'pʁɛstatɛʁ',
 'iʁepaʁabl',
 'ʁəpaʁti',
 'abʁytisɑ̃',
 'ʁeɛ̃seʁe',
 'kloʃaʁ',
 'sybʒɛktiv',
 'dezaktive',
 'ne',
 'komis',
 'ɔ̃biliko',
 'damaʒ',
 'pilonœʁ',
 'kʁɔkœʁ',
 'blakliste',
 'ʁetʁofyze',
 'apœʁe',
 'pnømɔnɛktɔmi',
 'pʁesɑ̃te',
 'mɑ̃dʃu',
 'kɔ̃tʁibɥe',
 'paʁaʃytəʁɛ',
 'gɑ̃gʁɛn',
 'taʁt',
 'videoklip',
 'aʒɑ̃se',
 'epaʁ',
 'kalifiʁje',
 'plɑ̃ke',
 'ʒɑ̃tijɔm',
 'lav',
 'kɔ̃tʁmɛtʁ',
 'kɔ̃kyʁɑ̃s',
 'twɛʁk',
 'gʁɛ̃pɛ',
 'gɛ',
 'ʃosəʁɛ',
 'ɛ̃tɛʁpoze',
 'ɛ̃tɛʁvju',
 'ɔ̃gʁwa',
 'ʃizɛl',
 'deboʃe',
 'koite',
 'diplomatik',
 'laʁmwa',
 'sekstɑ̃',
 'negʁijɔ̃',
 'aʒiʁɔ̃',
 'sityʁɛ',
 'fɛsɔ̃',
 'ʁeɛ̃sɛʁsjɔ̃',
 'ɛ̃sonoʁize',
 'ɛtnɔlɛ̃gɥistik',
 'pʁomɛnəʁɛ',
 'imynodepʁime',
 'eteʁoʒeneite',
 'epaʁɲe',
 'evolɥe',
 'pʁɛskʁi',
 'ʁevizɑ̃',
 'bɛtifi',
 'ɛ̃tɛʁpʁetɔ̃',
 'makijəʁɛ',
 'kalifiʁɛ',
 'bʁɑ̃',
 'kɔstaʁikɛn',
 'diskylpəʁa',
 'bʁosɛ',
 'lise',
 'kɔ̃fli',
 'fɔʁʒəʁjɔ̃',
 'ɛskiʁ',
 'ɔʁnəmɑ̃te',
 'paʁtaʒ',
 'komɛʁsjal',
 'pʁepaʁəʁɛ',
 'ɛ̃dolɑ̃',
 'soliv',
 'kɔlimate',
 'mɛnəʁɛ',
 'dɛsalmɑ̃',
 'balɑ̃',
 'liminal',
 'kʁaʃɛ',
 'ʁaʁefjɛ',
 'pʁodɥizjɔ̃',
 'pwavʁɑ̃',
 'ʃiʁe',
 'kadʁij',
 'maʁmonɛ',
 'niktalɔp',
 'demoʁalizɛ',
 'devwalɛ',
 'puʁisɛ',
 'etɛʁnɥɛ',
 'ɛgzɑ̃plaʁite',
 'pʁijɔʁizasjɔ̃',
 'benefisjɛ',
 'ɛksit',
 'spymø',
 'fʁətɛ̃',
 'miləfœj',
 'epʁiz',
 'kɑ̃tifje',
 'pyʁitɛn',
 'kaʁaktɛʁ',
 'asɑ̃blɛ',
 'ɛ̃kɔ̃sjɑ̃',
 'anaʁkosɛ̃dikalizm',
 'pʁepaʁasjɔ̃',
 'ʁadjogʁafje',
 'piʁoman',
 'sapœʁpɔ̃pje',
 'asasina',
 'dømiveʁite',
 'ʁetʁosedʁe',
 'suɑ̃plwaje',
 'ɔtofekɔ̃de',
 'sœl',
 'bylbø',
 'ɛkstʁovɛʁti',
 'bagaʁøz',
 'epɥize',
 'ʁɛsplɑ̃dis',
 'eʁode',
 'ʁafin',
 'abetisəmɑ̃',
 'ɛ̃spiʁe',
 'ʁɑ̃fɔʁ',
 'tapin',
 'tɑ̃tin',
 'gʁomɛləmɑ̃',
 'ɑ̃kuʁaʒəʁɛ',
 'sutʁɛt',
 'laseʁe',
 'ob',
 'aʁkadjɛ̃',
 'ɛ̃pʁesjonɑ̃',
 'ʁund',
 'nekʁoz',
 'delatʁis',
 'tʁagɔpɑ̃',
 'ʃinuk',
 'ɑ̃d',
 'ʁeʒjonal',
 'kʁisɑ̃',
 'faʃist',
 'lemyʁjɛ̃',
 'manigɑ̃sɛ',
 'fwinaʁ',
 'basɛt',
 'detɛʁɔ̃',
 'ʁamɛn',
 'ʁəkɔfʁ',
 'ipokʁit',
 'detʁɛs',
 'bagaʒist',
 'ʁəkɛ̃kəʁɛ',
 'paʁaʃəve',
 'stilɔid',
 'eʃɑ̃tijɔnɛ',
 'matøz',
 'baʁde',
 'senogʁafik',
 'ʁigɔl',
 'kik',
 'sodomizɛ',
 'dɛkstʁəmɑ̃',
 'ɛ̃dy',
 'pœnʃiŋbɔl',
 'dyʁsisœʁ',
 'pozisjɔn',
 'ymidje',
 'ʁapsodi',
 'ʒoni',
 'sysyʁɛ',
 'naftalɛn',
 'ɛkspɔʁtəʁɔ̃',
 'ameljɔʁəʁɔ̃',
 'gʁivətɔ̃',
 'fʁɔ̃tjɛʁ',
 'tɔʁd',
 'koɑ̃tʁəpʁiz',
 'kuʁjɛl',
 'ʁapɔʁte',
 'vasij',
 'baʁak',
 'venjɛl',
 'ly',
 'kolostomi',
 'pɑ̃səʁɔ̃',
 'bʁɔk',
 'plije',
 'akɔ̃paɲəʁa',
 'gaɲɑ̃',
 'ɛgzɛʁsəʁje',
 'menisk',
 'ɑ̃titɛz',
 'polɛn',
 'ʃɔvɛ̃',
 'ɛgzilɛ',
 'anaeʁɔbi',
 'fʁatɛʁnizje',
 'ʁesidivɑ̃',
 'avɑ̃t',
 'ʁədʁesje',
 'ʁevɛje',
 'ʁəsezisje',
 'gʁɔ̃dəʁɛ',
 'detaje',
 'aglytine',
 'ʁavalɛ',
 'atɛst',
 'epʁɑ̃dʁɛ',
 'tʁɔle',
 'gʁifwaʁ',
 'pɔmade',
 'ʁələvœʁ',
 'ʃəminəʁɔ̃',
 'kulak',
 'pɑ̃sy',
 'diktatœʁ',
 'dezɔnɔʁəʁje',
 'ʁɔ̃fləʁɛ',
 'ʃaʁbɔn',
 'sɔ̃dam',
 'bœge',
 'aeʁɔdinamikmɑ̃',
 'emiptɛʁ',
 'ʁətapise',
 'ʁəkony',
 'tʁijɔ̃fɛʁ',
 'ʁam',
 'bɛta',
 'fʁit',
 'anɔksemi',
 'pastœʁizəʁa',
 'kɔʒita',
 'lɑ̃ga',
 'dəʁəʃɛf',
 'ɑ̃bʁwazi',
 'ʁədəmɑ̃de',
 'sjeʁɛ',
 'adɔptəʁje',
 'dɛsuʃaʒ',
 'aksɛdəʁa',
 'ʁəmiʁ',
 'sɔnəʁɔ̃',
 'ɑ̃pilɔ̃',
 'apaʁtjɛ̃dʁɛ',
 'ʁəbwaʁ',
 'pasjətəʁe',
 'gygys',
 'ʁavaʒ',
 'kɔ̃siste',
 'diʁiʒəʁje',
 'gʁafit',
 'alege',
 'ʁəbulɔne',
 'adipozite',
 'dəmikø',
 'kude',
 'ʁadjogɔnjometʁik',
 'skizɔfʁeni',
 'djamɑ̃',
 'gaɲəʁa',
 'vwale',
 'delisjøz',
 'ajlɑ̃d',
 'ʁɑ̃vɛʁsəʁɛ',
 'ʃaʁtist',
 'syʁnaʒɑ̃',
 'nɛʁvyʁ',
 'fɔjl',
 'ʁøvɔle',
 'pʁolo',
 'fʁeʁo',
 'validɑ̃',
 'aline',
 'djalɔgəʁa',
 'syʁpʁɑ̃dʁa',
 'ʒoniʁ',
 'kɔ̃syltasjɔ̃',
 'sulɑ̃t',
 'ʁeevalɥe',
 'aʁyspis',
 'delɔkalizəʁɔ̃',
 'pozisjɔnəmɑ̃',
 'fʁize',
 'ʃiʁyʁʒi',
 'sɑ̃gle',
 'gaʁnityʁ',
 'ɛ̃tɛʁsybʒɛktif',
 'klɛʁɔpskyʁ',
 'kɔmynotaʁist',
 'gloʁifi',
 'kɔ̃siljɑ̃t',
 'deminœʁ',
 'ipɛʁbɔl',
 'aleʒe',
 'aneɑ̃tisje',
 'abolisɑ̃',
 'gʁɑ̃d',
 'ɔ̃gl',
 'muʁɛ',
 'meʃɑ̃t',
 'ɑ̃kuʁ',
 'pynisjɔ̃',
 'bleomisin',
 'ebɔʁɲ',
 'tʁɑ̃spaʁɑ̃s',
 'ɛgziʒe',
 'fwaʁɔ̃',
 'ʃiʃitøz',
 'ʁəbyte',
 'kʁonik',
 'nɔbl',
 'gavəʁa',
 'imynizəʁa',
 'ɛksplɔʁəʁje',
 'ɑ̃tidulœʁ',
 'ʁadikalize',
 'kɛlkəʃoz',
 'ʒelifi',
 'pʁeistoʁik',
 'aisɛ',
 'dekupe',
 'ʃaʁpɑ̃te',
 'epuvɑ̃t',
 'kono',
 'asɔ̃bʁise',
 'deb',
 'obwa',
 'kɔ̃tʁaʁgymɑ̃',
 'tɛkstil',
 'dezastʁ',
 'bazɔ̃sɛlylɛʁ',
 'pʁogʁɛsəʁɛ',
 'ɑ̃timɔ̃djalizasjɔ̃',
 'pɔstijonœʁ',
 'deviʁɔ̃',
 'pʁedi',
 'pinaje',
 'swiŋgɛ',
 'tʁyfəʁɛ',
 'deziʁəʁɛ',
 'aktivəʁɔ̃',
 'lwajaləmɑ̃',
 'ʁəkɔ̃pləle',
 'savonɛ',
 'ekaje',
 'plɑ̃tɛʁ',
 'bɛsɛ',
 'plasɛʁ',
 'dəvɑ̃sje',
 'ɑ̃tɑ̃',
 'kɛtzal',
 'kadɛ',
 'listəʁe',
 'yməʁe',
 'lɛtʁɔ̃',
 'alteʁofil',
 'apaʁtəny',
 'meteɔʁizasjɔ̃',
 'deglytisjɔ̃',
 'anɔt',
 'ɛkspɑ̃sjonist',
 'klɔmifɛn',
 'ɛksɑ̃ginotʁɑ̃sfyzjɔ̃',
 'kaʃɛ',
 'anɔbliʁa',
 'laʃ',
 'puʁsɥive',
 'bɔʁde',
 'kɔ̃disjɔnɛl',
 'destʁyktœʁ',
 'sɥe',
 'liʁɔ̃',
 'ʁeɑ̃pʁœ̃te',
 'sɛʁpɑ̃tɛ̃',
 'ʁɛvas',
 'kozɛ',
 'fʁenetik',
 'siɲifikativ',
 'ʁənymeʁizɛ',
 'ʁeʃofəʁa',
 'stɔkəʁɔ̃',
 'laʁgaʒ',
 'kujɔn',
 'klasifje',
 'ʃyʃɔtmɑ̃',
 'ynjɔnist',
 'oʁjɑ̃tal',
 'disɔsjativ',
 'n',
 'evɛjɛʁ',
 'kɔ̃t',
 'vɑ̃piʁize',
 'konɛks',
 'mitʁaje',
 'sɛlɛ',
 'kɔdkle',
 'kɔlɔ̃bina',
 'egalitaʁist',
 'ɛ̃kalkylabl',
 'abɛs',
 'neozelɑ̃dɛ',
 'suzekipe',
 'fuʁʃɛt',
 'ʁədutɛ',
 'melodjøz',
 'niʃɔ̃',
 'lɛʃky',
 'pikolœʁ',
 'defʁoke',
 'ɛ̃flɛksjɔ̃',
 'alkoliz',
 'tetʁaɔdɔ̃',
 'aləmɑ̃d',
 'buləvɛʁsəʁɛ',
 'ɛ̃sasjabilite',
 'ʁəʃɛʁʃəʁɛ',
 'fɔtɔsɛ̃tetik',
 'baʁbaʁɛsk',
 'kɔlmatəʁa',
 'pʁekɔlɔnjal',
 'ʒeʁəʁɛ',
 'pɔ̃pɔnɛ',
 'pɛʁsonalize',
 'fil',
 'pʁɛspapje',
 'evanwis',
 'ʃaʁibd',
 'detʁɥizim',
 'kɔ̃gʁegasjɔnalist',
 'pineal',
 'tɛ̃tyʁje',
 'ʁasinɛʁ',
 'ɑ̃pəze',
 'sulɛ',
 'kʁysifjɔ̃',
 'abʁœvɔ̃',
 'gʁavimetʁik',
 'vag',
 'ʁəfyzɑ̃',
 'seʁeal',
 'bwazɔ̃',
 'lɑ̃giʁɔ̃',
 'ʁənuvəljɔ̃',
 'fotoliz',
 'divɔʁsəʁe',
 'idɑ̃tifjɛ',
 'pikoʁe',
 'spame',
 'dilatwaʁ',
 'lɔʒistisjɛ̃',
 'pyni',
 'dezoʁjɑ̃təʁɛ',
 'denyde',
 'ɛ̃vite',
 'ɛskʁim',
 'ɛ̃tɑ̃sifjɑ̃',
 'tisʁɛ̃',
 'gʁatuj',
 'sɛʁmɔn',
 'degɔməʁɛ',
 'ɛ̃sɛstɥø',
 'fuʁaʒ',
 'ɛkstʁɛməmɑ̃',
 'kʁepit',
 'maʁeʃaləʁi',
 'pʁɔstɛʁnəʁɛ',
 'akʁ',
 'apəzɑ̃tisɛ',
 'bɑ̃tu',
 'ʁɛskij',
 'syksedɛ',
 'tyb',
 'ʁoti',
 'piliŋ',
 'selebʁəʁɛ',
 'ɛ̃syltɑ̃',
 'akselɛʁəʁɔ̃',
 'fɔsfɔsʁik',
 'kɔ̃tʁe',
 'gɔʁfu',
 'utʁəpase',
 'ɛ̃pasjatəʁa',
 'etɛ̃dʁije',
 'pʁedomin',
 'pase',
 'ʁyze',
 'kɔʁvide',
 'daktilogʁafje',
 'polip',
 'pwɛ̃',
 'apotʁ',
 'syʁegy',
 'malavize',
 's',
 'deteine',
 'tatu',
 'najtklœb',
 'pɛʁsəvɛ',
 'ajø',
 'ʁeʃofe',
 'tʁɑ̃sfɔʁmist',
 'tʁenəʁe',
 'sabote',
 'tab',
 'ʁɑ̃fɔʁse',
 'fwɛ̃',
 'ʁəfɔ̃de',
 'kyʁatif',
 'batifole',
 'tablɔid',
 'pjezɔelɛktʁik',
 'pʁostɛʁnɔ̃',
 'ɛ̃digotin',
 'ʁɛjɔn',
 'ɑ̃viʁɔnəmɑ̃to',
 'balata',
 'tɛɲø',
 'ɑ̃bɛte',
 'iɲifyʒɑ̃',
 'ʒeogʁaf',
 'ʁəfujəʁa',
 'ɑ̃tʁəpɔ̃',
 'bɔnisœʁ',
 'maʁmɔne',
 'paʁtisipəʁɔ̃',
 'demaskəʁɔ̃',
 'stʁidylasjɔ̃',
 'tʁɑ̃sfɔʁməʁɔ̃',
 'bʁikɛ',
 'ɑ̃glopɔʁtygɛ',
 'tizone',
 'tonitʁy',
 'tɛʁjɛn',
 'kʁøzəʁɔ̃',
 'iɲifyʒe',
 'ɑ̃vizaʒɔ̃',
 'sypozəʁje',
 'ajwɛ',
 'ɑ̃ʁiʃiʁa',
 'əmeləʁe',
 'ɛ̃ʃɑ̃ʒe',
 'okyltizm',
 'pipi',
 'sjɛ̃',
 'ʁeekilibʁəʁe',
 'ɑ̃bɔʃəʁɔ̃',
 'psikɔsɛksyɛl',
 'adoʁabl',
 'syʁvivɛ',
 'bulguʁ',
 'maʁʃøz',
 'pɛʁlo',
 'disfɔ̃ksjɔn',
 'glisəʁɔ̃',
 'ʁədoze',
 'suləʁɛ',
 'syʁvønɑ̃s',
 'malnytʁi',
 'blœf',
 'ʒɥif',
 'damase',
 'pwaɲaʁdje',
 'abazuʁdi',
 'likefi',
 'tɔfi',
 'posesif',
 'apotikɛʁ',
 'afliʒe',
 'dezakse',
 'limite',
 'ʃapəlje',
 'ɛgzɛʁs',
 'pɛʁsɛptyɛl',
 'ɛ̃pozɛʁ',
 'aspiʁɑ̃',
 'tabl',
 'tybipɔʁ',
 'tɔʁbwajo',
 'ʃlɛ̃g',
 'pɛʁsɥadɛ',
 'aeʁe',
 'tʁavɛsti',
 'ʁabwin',
 'ʁɑ̃pəʁɛ',
 'ʁabijəʁɔ̃',
 'maʁʃmalo',
 'ɛ̃desi',
 'vuly',
 'myskyløz',
 'peʒoʁativəmɑ̃',
 'polaʁize',
 'skutœʁ',
 'gʁijəʁɛ',
 'kʁupisɛ',
 'sisyʁ',
 'ebʁɥitɛ',
 'ɑ̃ʒɑ̃dʁa',
 'puʁvwajɑ̃',
 'anaplazik',
 'kaplɑ̃',
 'tsaʁɛvna',
 'bɔ̃binɛt',
 'nikab',
 'deplɑ̃t',
 'klaməse',
 'tʁiʃɛ',
 'ʃɑ̃səla',
 'siʁys',
 'asɔʁtisɛ',
 'telepɔʁtœʁ',
 'degaʒjɔ̃',
 'tɑ̃tal',
 'aʃətɛ',
 'pʁovɛʁb',
 'favoʁiz',
 'tʁɛ̃bale',
 'ɛ̃dekʁɔʃabl',
 'ɛkstɔʁsjɔ̃',
 'buʁsufl',
 'sotmutɔ̃',
 'fɔʁ',
 'petʁisɛ',
 'adɔpta',
 'taʁod',
 'bʁife',
 'ɑ̃baʁase',
 'aʁagonɛz',
 'sɔti',
 ...]

In [114]:
verbs=dfLex4.loc[dfLex4["5_Cgram"]=="VER"]["3_Phono_IPA"].tolist()
verbs=[str(w) for w in verbs]
verbs

['dispʁopɔʁsjone',
 'maʁʒe',
 'akyzɔ̃',
 'apsɔʁbje',
 'puʁɔ̃',
 'ɑ̃tʁətyʁɛ',
 'dezeʁitɛ',
 'atiz',
 'ʒap',
 'desule',
 'adubje',
 'efɛktɥe',
 'ebʁɥit',
 'ʁəsɛʁ',
 'ʁesit',
 'mizɛ',
 'ʁəkupe',
 'fɔ̃səʁɛ',
 'ʁədiʁiʒe',
 'agʁavəʁa',
 'dekuvʁiʁɛ',
 'dekuvʁ',
 'ʁətɑ̃dy',
 'dekole',
 'ʁəseziʁe',
 'bosɥe',
 'abatʁɛ',
 'klwazɔnəʁɛ',
 'pylyle',
 'ʁezɛʁv',
 'asɛje',
 'istɔʁi',
 'deniʃam',
 'atɑ̃sjɔna',
 'sɛʁvɔ̃',
 'depʁesje',
 'dezeʁite',
 'ʁaʃɛtəʁɛ',
 'dʁap',
 'tyʁlypinɛ',
 'fʁaktyʁe',
 'bɛɲ',
 'paʁiʁɛ',
 'vizjɔnəʁa',
 'utʁe',
 'aleʒe',
 'dʁagəʁje',
 'distɑ̃se',
 'ʃasəʁa',
 'dezilyzjɔne',
 'temwaɲe',
 'ɛgzɛʁsɛʁ',
 'ekʁulje',
 'aʁozɛ',
 'metafɔʁizəʁe',
 'tɛʁminɛʁ',
 'ʁədizɑ̃',
 'bufəʁɛ',
 'modyle',
 'deʃaʁʒɛ',
 'favoʁizɛ',
 'kɔ̃paʁɛs',
 'bʁakonɛ',
 'skalpəʁa',
 'kʁijɛ',
 'paʁadəʁje',
 'ʁevɛjɔnəʁe',
 'apsɔʁbe',
 'telefaks',
 'badiʒɔnje',
 'vizitɛ',
 'buzijəʁɛ',
 'dɑ̃təle',
 'sijɔnəʁɔ̃',
 'etydje',
 'ʁədɔnəʁɛ',
 'gobɑ̃',
 'pʁezyme',
 'ʁəmiks',
 'mask',
 'ɑ̃bʁasɛʁ',
 'gatəʁɔ̃',
 'ʁəmɔ̃tɛ',
 'kɔ̃sɔməʁɛ',
 'syksedɛʁ',
 'degene',
 'otoʁize',
 'peʃɛ',
 'elɑ̃sɛ',
 'pilote',
 'ʁəpɑ̃tiʁ',
 'koɛ̃sida',
 'lu',
 'dezagʁeʒʁɔ̃',
 'ovœʁklokɑ̃',
 'dedikas',
 'deʃɛnɔ̃',
 'nikɛ',
 'ʒyʁam',
 'ʃaviʁ',
 'ɛ̃stʁɥiʁe',
 'kɑ̃bʁijɔləʁɔ̃',
 'ʁefleʃiʁ',
 'ɛ̃tybe',
 'degutɛ',
 'ʁəstʁyktyʁe',
 'blɛ̃de',
 'sɥivi',
 'dezɛʁbəʁe',
 'ɔksiʒenɑ̃',
 'kɔ̃disjonɛ',
 'pɔlaʁizɑ̃',
 'ekut',
 'bʁɑ̃ʃəʁɔ̃',
 'fʁɑ̃size',
 'sɛʁtifiʁɔ̃',
 'ʁɥisəle',
 'ʁatifje',
 'ʁeasiɲ',
 'datje',
 'disimyle',
 'debʁujɔ̃',
 'dʒɔgɛ',
 'avuʁa',
 'depəsɑ̃',
 'ʁədate',
 'pɛ̃tyʁlyʁ',
 'ʁakɔʁdɑ̃',
 'kɔ̃sym',
 'tʁɔ̃pɛt',
 'kuvʁiʁɛ',
 'diskylpəʁɛ',
 'vjɛ̃dʁijɔ̃',
 'apaʁɛs',
 'dekolɔʁ',
 'sotijəʁe',
 'maɲ',
 'tuʁmɑ̃təʁɛ',
 'mizəʁɔ̃',
 'dɑ̃ta',
 'dezɑ̃lize',
 'ɑ̃pɔʁtɛ',
 'koteʁizje',
 'tənaje',
 'tɑ̃te',
 'bʁuje',
 'kɔ̃fiʁmɛʁ',
 'degulinəʁe',
 'ʁegʁɛs',
 'tiʁəʁɔ̃',
 'dəvizɛ',
 'ʃuʁe',
 'pedaləʁa',
 'dinɛ',
 'afaləʁe',
 'devalize',
 'kɔ̃fiʁɛ',
 'ɛgzɔsa',
 'dezidʁate',
 'apʁete',
 'tɛʁe',
 'pɛʁmyt',
 'buma',
 'ʃapaʁde',
 'asfiksjɑ̃',
 'aʒiʁa',
 'bɔjkɔta',
 'elaʁʒisɛ',
 'gaʃəʁɔ̃',
 'ʁəpaʁti',
 'ʁeɛ̃seʁe',
 'apœʁe',
 'pʁesɑ̃te',
 'kɔ̃tʁibɥe',
 'paʁaʃytəʁɛ',
 'gɑ̃gʁɛn',
 'aʒɑ̃se',
 'kalifiʁje',
 'gʁɛ̃pɛ',
 'ʃosəʁɛ',
 'ɛ̃tɛʁpoze',
 'ɛ̃tɛʁvju',
 'deboʃe',
 'koite',
 'laʁmwa',
 'aʒiʁɔ̃',
 'sityʁɛ',
 'fɛsɔ̃',
 'ɛ̃sonoʁize',
 'pʁomɛnəʁɛ',
 'epaʁɲe',
 'pʁɛskʁi',
 'ʁevizɑ̃',
 'bɛtifi',
 'ɛ̃tɛʁpʁetɔ̃',
 'makijəʁɛ',
 'kalifiʁɛ',
 'diskylpəʁa',
 'bʁosɛ',
 'lise',
 'fɔʁʒəʁjɔ̃',
 'ɔʁnəmɑ̃te',
 'paʁtaʒ',
 'pʁepaʁəʁɛ',
 'mɛnəʁɛ',
 'kʁaʃɛ',
 'ʁaʁefjɛ',
 'pʁodɥizjɔ̃',
 'pwavʁɑ̃',
 'maʁmonɛ',
 'demoʁalizɛ',
 'devwalɛ',
 'puʁisɛ',
 'etɛʁnɥɛ',
 'benefisjɛ',
 'ɛksit',
 'epʁiz',
 'asɑ̃blɛ',
 'ʁadjogʁafje',
 'ʁetʁosedʁe',
 'suɑ̃plwaje',
 'ʁɛsplɑ̃dis',
 'ʁafin',
 'tapin',
 'ɑ̃kuʁaʒəʁɛ',
 'sutʁɛt',
 'laseʁe',
 'ɛ̃pʁesjonɑ̃',
 'manigɑ̃sɛ',
 'detɛʁɔ̃',
 'ʁamɛn',
 'ʁəkɛ̃kəʁɛ',
 'paʁaʃəve',
 'eʃɑ̃tijɔnɛ',
 'baʁde',
 'sodomizɛ',
 'pozisjɔn',
 'sysyʁɛ',
 'ɛkspɔʁtəʁɔ̃',
 'ameljɔʁəʁɔ̃',
 'tɔʁd',
 'vasij',
 'baʁak',
 'pɑ̃səʁɔ̃',
 'plije',
 'akɔ̃paɲəʁa',
 'ɛgzɛʁsəʁje',
 'ɛgzilɛ',
 'fʁatɛʁnizje',
 'ʁədʁesje',
 'ʁevɛje',
 'ʁəsezisje',
 'gʁɔ̃dəʁɛ',
 'detaje',
 'aglytine',
 'ʁavalɛ',
 'atɛst',
 'epʁɑ̃dʁɛ',
 'pɔmade',
 'ʃəminəʁɔ̃',
 'dezɔnɔʁəʁje',
 'ʁɔ̃fləʁɛ',
 'ʃaʁbɔn',
 'sɔ̃dam',
 'ʁətapise',
 'ʁəkony',
 'tʁijɔ̃fɛʁ',
 'pastœʁizəʁa',
 'kɔʒita',
 'ʁədəmɑ̃de',
 'sjeʁɛ',
 'adɔptəʁje',
 'ʁəmiʁ',
 'sɔnəʁɔ̃',
 'ɑ̃pilɔ̃',
 'apaʁtjɛ̃dʁɛ',
 'ʁəbwaʁ',
 'pasjətəʁe',
 'kɔ̃siste',
 'diʁiʒəʁje',
 'gʁafit',
 'alege',
 'ʁəbulɔne',
 'gaɲəʁa',
 'ʁɑ̃vɛʁsəʁɛ',
 'ʁøvɔle',
 'validɑ̃',
 'djalɔgəʁa',
 'syʁpʁɑ̃dʁa',
 'ʒoniʁ',
 'ʁeevalɥe',
 'delɔkalizəʁɔ̃',
 'fʁize',
 'sɑ̃gle',
 'gloʁifi',
 'aleʒe',
 'aneɑ̃tisje',
 'abolisɑ̃',
 'muʁɛ',
 'ɑ̃kuʁ',
 'ebɔʁɲ',
 'ɛgziʒe',
 'ʁəbyte',
 'gavəʁa',
 'imynizəʁa',
 'ɛksplɔʁəʁje',
 'ʁadikalize',
 'ʒelifi',
 'aisɛ',
 'dekupe',
 'epuvɑ̃t',
 'asɔ̃bʁise',
 'pʁogʁɛsəʁɛ',
 'deviʁɔ̃',
 'pinaje',
 'swiŋgɛ',
 'tʁyfəʁɛ',
 'deziʁəʁɛ',
 'aktivəʁɔ̃',
 'ʁəkɔ̃pləle',
 'savonɛ',
 'ekaje',
 'plɑ̃tɛʁ',
 'bɛsɛ',
 'ɑ̃tɑ̃',
 'listəʁe',
 'yməʁe',
 'apaʁtəny',
 'anɔt',
 'kaʃɛ',
 'anɔbliʁa',
 'puʁsɥive',
 'bɔʁde',
 'liʁɔ̃',
 'ʁeɑ̃pʁœ̃te',
 'ʁɛvas',
 'kozɛ',
 'ʁənymeʁizɛ',
 'ʁeʃofəʁa',
 'stɔkəʁɔ̃',
 'kujɔn',
 'klasifje',
 'evɛjɛʁ',
 'kɔ̃t',
 'vɑ̃piʁize',
 'mitʁaje',
 'sɛlɛ',
 'abɛs',
 'ʁədutɛ',
 'niʃɔ̃',
 'defʁoke',
 'alkoliz',
 'buləvɛʁsəʁɛ',
 'ʁəʃɛʁʃəʁɛ',
 'kɔlmatəʁa',
 'ʒeʁəʁɛ',
 'pɔ̃pɔnɛ',
 'pɛʁsonalize',
 'fil',
 'evanwis',
 'detʁɥizim',
 'ɑ̃pəze',
 'sulɛ',
 'kʁysifjɔ̃',
 'abʁœvɔ̃',
 'ʁəfyzɑ̃',
 'bwazɔ̃',
 'lɑ̃giʁɔ̃',
 'ʁənuvəljɔ̃',
 'divɔʁsəʁe',
 'idɑ̃tifjɛ',
 'pikoʁe',
 'spame',
 'pyni',
 'dezoʁjɑ̃təʁɛ',
 'ɛskʁim',
 'ɛ̃tɑ̃sifjɑ̃',
 'gʁatuj',
 'sɛʁmɔn',
 'degɔməʁɛ',
 'fuʁaʒ',
 'kʁepit',
 'pʁɔstɛʁnəʁɛ',
 'apəzɑ̃tisɛ',
 'ʁɛskij',
 'syksedɛ',
 'tyb',
 'ʁoti',
 'selebʁəʁɛ',
 'ɛ̃syltɑ̃',
 'kɔ̃tʁe',
 'utʁəpase',
 'ɛ̃pasjatəʁa',
 'etɛ̃dʁije',
 'pʁedomin',
 'pwɛ̃',
 'tatu',
 'pɛʁsəvɛ',
 'ʁeʃofe',
 'sabote',
 'ʁɑ̃fɔʁse',
 'ʁəfɔ̃de',
 'batifole',
 'pʁostɛʁnɔ̃',
 'ʁɛjɔn',
 'ɑ̃bɛte',
 'ʁəfujəʁa',
 'maʁmɔne',
 'paʁtisipəʁɔ̃',
 'demaskəʁɔ̃',
 'tʁɑ̃sfɔʁməʁɔ̃',
 'tonitʁy',
 'kʁøzəʁɔ̃',
 'iɲifyʒe',
 'ɑ̃vizaʒɔ̃',
 'sypozəʁje',
 'ɑ̃ʁiʃiʁa',
 'əmeləʁe',
 'ʁeekilibʁəʁe',
 'ɑ̃bɔʃəʁɔ̃',
 'syʁvivɛ',
 'disfɔ̃ksjɔn',
 'glisəʁɔ̃',
 'ʁədoze',
 'suləʁɛ',
 'blœf',
 'pwaɲaʁdje',
 'abazuʁdi',
 'likefi',
 'limite',
 'ɛgzɛʁs',
 'ɛ̃pozɛʁ',
 'tabl',
 'ʃlɛ̃g',
 'pɛʁsɥadɛ',
 'aeʁe',
 'tʁavɛsti',
 'ʁɑ̃pəʁɛ',
 'ʁabijəʁɔ̃',
 'polaʁize',
 'gʁijəʁɛ',
 'kʁupisɛ',
 'ebʁɥitɛ',
 'ɑ̃ʒɑ̃dʁa',
 'puʁvwajɑ̃',
 'deplɑ̃t',
 'klaməse',
 'tʁiʃɛ',
 'ʃɑ̃səla',
 'asɔʁtisɛ',
 'degaʒjɔ̃',
 'aʃətɛ',
 'favoʁiz',
 'tʁɛ̃bale',
 'buʁsufl',
 'petʁisɛ',
 'adɔpta',
 'taʁod',
 'bʁife',
 'ɑ̃baʁase',
 'ɛkspɛʁtize',
 'ʁamasa',
 'abitəʁɛ',
 'ɑ̃glɥe',
 'ɑ̃fɑ̃tɑ̃ʁɔ̃',
 'syʁvjɛ̃',
 'ɑ̃tɛ',
 'ʁəmɔdəle',
 'gʁifonɑ̃',
 'ʁeɲəʁɔ̃',
 'sɔlysjɔnɑ̃',
 'kɔ̃sɔməʁa',
 'ʁɑ̃pɔte',
 'susijɔ̃',
 'emɛʁvɛj',
 'pjøte',
 'epɥiza',
 'tʁɛʁe',
 'flɛ̃gɛ',
 'asimiləʁa',
 'aʁkbute',
 'iʁadje',
 'atɑ̃dʁi',
 'pʁodɥi',
 'puʁʃasəʁɛ',
 'tɛʁminəʁe',
 'swiŋge',
 'ʃɑ̃stik',
 'idɔlatʁe',
 'kɔ̃vwaje',
 'tʁɑ̃pe',
 'flykty',
 'pʁostɛʁnəʁa',
 'ɛ̃tɛʁvɛ̃',
 'ɛ̃teʁjoʁize',
 'apɥiʁɛ',
 'ʁədemenaʒe',
 'pije',
 'ʁəkomɑ̃de',
 'geʁisjɔ̃',
 'emuse',
 'ʁəpœplɔ̃',
 'adʁɛsjɔ̃',
 'gʁosisɛ',
 'titʁa',
 'ɑ̃bwatəʁɛ',
 'buji',
 'kɔ̃fiska',
 'ʁikanɛ',
 'faktyʁɑ̃',
 'kaʁe',
 'ʁetʁogʁade',
 'ɑ̃tuʁ',
 'ʁakləʁe',
 'ʁakɔ̃təʁɔ̃',
 'detʁɥiʁjɔ̃',
 'devəlope',
 'fɔʁtifje',
 'ɛksfɔljɑ̃',
 'ʁepɛʁkytəʁɔ̃',
 'ʁətuʃɛ',
 'demɑ̃təle',
 'ɑ̃nɥije',
 'pʁodɥizɔ̃',
 'fʁejʁɛ',
 'blaze',
 'fuʁmij',
 'ʁəkazəʁɛ',
 'bafwɛ',
 'ɔbnybile',
 'depɑ̃sɑ̃',
 'ʁøfutʁe',
 'ʁətʁɑ̃sfɔʁme',
 'ekʁazɛ',
 'ɑ̃paje',
 'fokalize',
 'ʁɑ̃buʁe',
 'gʁibuje',
 'ɑ̃byske',
 'sapəʁɛ',
 'kɔ̃pylse',
 'sɛ̃patizəʁɛ',
 'sijona',
 'alaʁməʁɛ',
 'gɛ̃ʃ',
 'li',
 'bɔ̃baʁdəʁje',
 'dekʁase',
 'ɑ̃ʁolɔ̃',
 'tʁuɑ̃',
 'ʁefyʒijɔ̃',
 'aʁpɔn',
 'distɛ̃gje',
 'anyləʁɔ̃',
 'ʁəkʁytəʁa',
 'gloʁifjɛ',
 'kylpabilizɑ̃',
 'ʁeʒɑ̃tɑ̃',
 'pʁɔmuvɛ',
 'ʁəvizitəʁa',
 'ʁeinisjalize',
 'lisɑ̃si',
 'fɛse',
 'ɑ̃boməʁɔ̃',
 'fisjone',
 'tus',
 'vɑ̃te',
 'elaʁʒis',
 'skyltəʁa',
 'ɛgzymɑ̃',
 'ʃjalɛ',
 'ʁəpʁɔʃəʁɛ',
 'opʁime',
 'pʁije',
 'veje',
 'koʁɔd',
 'tɔʁpije',
 'boni',
 'onɔʁ',
 'kozɑ̃',
 'ʁediʒɛ',
 'kaʒɔl',
 'ɛ̃titylɑ̃',
 'avwɛ',
 'deʒwɛ',
 'dyʁɑ̃',
 'deliʁɛ',
 'metamɔʁfɔzəʁa',
 'tʁemuse',
 'mate',
 'pøzɑ̃',
 'zipe',
 'sɛ̃gylaʁiz',
 'ɑ̃ʁuləʁa',
 'amenaʒɛ',
 'defiʁɛ',
 'ɑ̃pale',
 'ɑ̃tʁəlas',
 'ʁəʃaʁʒɔ̃',
 'vuʁɛ',
 'aeʁe',
 'etydje',
 'ʁəkylɛ',
 'ɛ̃tɛʁoʒe',
 'ɑ̃tonɑ̃',
 'ʁətʁɑ̃ʃjɔ̃',
 'mize',
 'ʁɑ̃məne',
 'plɑ̃ʃe',
 'aniile',
 'etufɛ',
 'ʁipɔstəʁɛ',
 'atablɛ',
 'bytəʁjɔ̃',
 'denɔ̃bʁa',
 'ɛgzasɛʁbe',
 'mənɔtəʁɔ̃',
 'sodomiz',
 'sedɥize',
 'ʁeʃofje',
 'pʁatike',
 'ʁəseʁe',
 'ɛ̃tɛʁpɛla',
 'ʁəʃaʁʒ',
 'ʁitme',
 'poʃe',
 'ʁədəvʁe',
 'ɛstima',
 'epaʁpije',
 'banis',
 'kaʃe',
 'kɔ̃təʁɛ',
 'ʁepʁimɑ̃dɑ̃',
 'ʁeɛksplikəʁe',
 'ʁəbif',
 'ʁasjɔnalizəʁɛ',
 'pʁevjɛ̃',
 'ɛ̃plɔʁəʁɛ',
 'maʁmɔn',
 'tjɛ̃dʁijɔ̃',
 'ɑ̃vnimje',
 'paʁke',
 'ɛkspozɛ',
 'ʁəplasɔ̃',
 'pʁezyməʁa',
 'kutəʁɔ̃',
 'plisəʁe',
 'ʁəpʁize',
 'defeke',
 'pɔlitiz',
 'ʁɑ̃vɛʁjɔ̃',
 'ʁapɛləʁa',
 'komynike',
 'pikote',
 'paʁ',
 'eʒakyl',
 'ʃozifje',
 'ʁepɔ̃',
 'amwɛ̃dʁi',
 'blasfemʁa',
 'ʁegyʁʒitəʁa',
 'katastʁofe',
 'sɛʁnəʁje',
 'desidəʁa',
 'afinɔ̃',
 'ʁaze',
 'debɔʁdɛ',
 'sedɑ̃taʁiz',
 'pœtɛ',
 'ɑ̃plafone',
 'bul',
 'abɛʁɑ̃',
 'ʁəmuləʁe',
 'sɛ̃plifiʁɔ̃',
 'plɛ̃dʁa',
 'avɑ̃tyʁəʁɛ',
 'ʁətʁɑ̃smɛtʁɔ̃',
 'ʁəbuʃe',
 'vɔlatilize',
 'smaʃɛ',
 'kuvʁe',
 'syplɑ̃te',
 'føtʁe',
 'ɑ̃magazin',
 'ʁətuʃe',
 'bʁajəʁa',
 'balbysje',
 'ʁealizɛ',
 'tʁysidəʁɛ',
 'bɛkɛtʁa',
 'ɑ̃tas',
 'amɑ̃dəʁa',
 'ʁədemaʁ',
 'ɛgzɛʁsɛ',
 'epuzəʁje',
 'ɛ̃vɔkəʁɔ̃',
 'ɑ̃tʁəkupɛ',
 'aʃa',
 'kɔ̃ʒyge',
 'dɛɲ',
 'ɛ̃tityle',
 'etydjɛ',
 'ʁeɛ̃skʁi',
 'ɔʁbitɑ̃',
 'eklipsəʁɔ̃',
 'iʁitjɔ̃',
 'plakɛ',
 'pɛ̃sa',
 'toleʁɛ',
 'atiʁɛ',
 'ɑ̃fuʁʃɔ̃',
 'ɑ̃kadʁɔ̃',
 'pɔstdate',
 'tisɔ̃',
 'ɛ̃sɑ̃djɛ',
 'gʁezije',
 'kavaləʁa',
 'ʁɑ̃fɔʁsiʁ',
 'sufle',
 'ɑ̃guʁdi',
 'bʁɛze',
 'sutʁete',
 'ɛ̃tɛʁvɛ̃ʁ',
 'polisɔne',
 'ogyʁɛ',
 'aʒitɛ',
 'amoli',
 'sulwɛ',
 'ɑ̃bɛtəʁɛ',
 'ʁeabityʁe',
 'ɑ̃peʃe',
 'ʁɑ̃buʁsəʁa',
 'emɑ̃sipe',
 'bʁɑ̃dise',
 'makəʁa',
 'ipoteke',
 'devɛʁsɔ̃',
 'tʁɛ̃bal',
 'buʃɛ',
 'flɑ̃ʃ',
 'ʁəmatəʁe',
 'siviliz',
 'ʁydwaje',
 'meditəʁɔ̃',
 'diminɥɔ̃',
 'ʁagajaʁdi',
 'delimite',
 'delɔʒəʁe',
 'ɛstime',
 'ʁeʒɑ̃te',
 'etʁɑ̃gləʁɛ',
 'vwazinəʁa',
 'ɑ̃dyʁsi',
 'ʁədistʁibyʁa',
 'ɛgzɔʁsiz',
 'tete',
 'adɔʁəʁɛ',
 'pʁefase',
 'ʁətiʁe',
 'ɔpte',
 'ɑ̃seɲɔ̃',
 'ɑ̃plifi',
 'depɑ̃se',
 'bʁyləʁjɔ̃',
 'ʁikan',
 'altɛʁnəʁa',
 'deʒivʁɑ̃',
 'ʁəkɔ̃takt',
 'nɥizɛ',
 'pløvʁa',
 'ʁepɑ̃dʁɛ',
 'falsifiʁje',
 'bekɔtəʁɛ',
 'kwafəʁa',
 'ɛ̃pylse',
 'fiʃe',
 'ɑ̃pajɑ̃',
 'ʁɔmɑ̃se',
 'akɔ̃pliʁ',
 'fuʁʃe',
 'fɔʁtifjɑ̃',
 'kaʁikatyʁa',
 'kɔitəʁe',
 'ɛgzaltɔ̃',
 'kʁɛɲiʁ',
 'ɑ̃pwasɔn',
 'ʁaliʁɛ',
 'ɑ̃flame',
 'tʁɑ̃sfyze',
 'ʁəkole',
 'ɛkspje',
 'ʁamifje',
 'ɑ̃bʁaza',
 'ʁəbatʁ',
 'eʃwɛ',
 'kabanɔ̃',
 'mwazisɛ',
 'dəmœʁəʁɛ',
 'pʁotɛst',
 'demateʁjaliz',
 'pavanəʁje',
 'fysje',
 'ɑ̃pwazɔnəʁɛ',
 'syʁmənɛ',
 'aʒənujɛ',
 'amɛgʁiʁ',
 'ɑ̃gʁesɔ̃',
 'ɑ̃kʁute',
 'ʁenɔvɔ̃',
 'kuʁsiʁkɥitʁa',
 'dezɔbeiʁɛ',
 'ʒwɛ̃t',
 'ʁəkeʁe',
 'kɔ̃ble',
 'blœf',
 'apaʁɛsɔ̃',
 'pʁostɛʁnəʁɛ',
 'syʁvɛjəʁɛ',
 'suʁiʁe',
 'defɛʁle',
 'sy',
 'ʁeɛ̃vɛstiʁe',
 'ɑ̃vwaje',
 'ɛ̃tʁodɥizɛ',
 'ʁavitaje',
 'asjeʒe',
 'elagəʁa',
 'alɛ',
 'ʁəlɥiz',
 'ɑ̃gølɔ̃',
 'ʁøkɔ̃sideʁʁa',
 'ʁotɛ',
 'sɛ̃bɔlize',
 'debaʁasəʁɔ̃',
 'ɑ̃ʁu',
 'ʁeeliz',
 'ʃematizɛ',
 'note',
 'kalkyl',
 'ɑ̃kanaje',
 'dezɑ̃paʁe',
 'ɛgzɑ̃plifjɛ',
 'paʁɔdje',
 'vɛjɛʁ',
 'kɛstjonɔ̃',
 'ʒaʁdinɛ',
 'ɑ̃dɑ̃t',
 'ɛkspjɛ',
 'ʁədefɛʁ',
 'ale',
 'mas',
 'pɛʁsɑ̃',
 'pɛʁmɛt',
 'dekɔ̃pɔzɔ̃',
 'ʁezistəʁa',
 'disfɔ̃ksjɔna',
 'some',
 'depanɛ',
 'tu',
 'pyʁyl',
 'ɑ̃bwate',
 'apɑ̃dʁɔ̃',
 'ligatyʁ',
 'afɛksjonɛ',
 'ʁime',
 'ʁeysisɑ̃',
 'aksjɔn',
 'demɔliʁa',
 'ɑ̃kaʒe',
 'pynisɛ',
 'aʁɔ̃disɔ̃',
 'ʁɔk',
 'fʁemi',
 'ʁənɔ̃sɛ',
 'kɔ̃dɑ̃se',
 'manadʒe',
 'domɛstikɛ',
 'fajim',
 'asɛʁmɑ̃te',
 'fele',
 'amuʁaʃəʁa',
 'pjɛʒ',
 'laʁgəʁje',
 'efʁejɛ',
 'emɛʁʒɔ̃',
 'divylgəʁɔ̃',
 'fʁetijɛ',
 'ʁəpɑ̃sje',
 'dekoleʁɛ',
 'ɑ̃dɛtəʁɛ',
 'sɑ̃ti',
 'kʁɛ̃t',
 'skɑ̃dalize',
 'ɛ̃teʁese',
 'otodetʁɥit',
 'myʒiʁje',
 'mat',
 'apɥiʁɛ',
 'ɛsɥije',
 'ʁɥisɛl',
 'ʁəlykje',
 'tʁœstɛ',
 'ʁəʒwɛ̃t',
 'ʁetʁogʁad',
 'siʁote',
 'ʁɛktifjɔ̃',
 'disimyljɔ̃',
 'kʁɑ̃pɔn',
 'gɔ̃da',
 'ɛ̃kɔʁpoʁɛ',
 'admiʁjɔ̃',
 'afiʁməʁɛ',
 'ʁezistəʁɔ̃',
 'anyle',
 'ʁapʁoʃe',
 'klue',
 'epise',
 'ɑ̃tʁavɛ',
 'flate',
 'bakla',
 'apʁuv',
 'iɲoʁɛ',
 'laseʁa',
 'apeze',
 'altɛʁnəʁɔ̃',
 'sɛ̃kʁonizɛ',
 'ʃuʁ',
 'ʁekypeʁɔ̃',
 'ʁəpʁize',
 'lystʁ',
 'fʁekɑ̃təʁɔ̃',
 'tʁɑ̃ʃɛ',
 'tɑ̃tjɔ̃',
 'ʁəmaʁkjɔ̃',
 'aktɥalizəʁɔ̃',
 'demake',
 'buʁd',
 'amɔʁsəʁa',
 'kʁwaʁɛ',
 'kymyla',
 'ʁəkanalize',
 'ɑ̃tuʁəʁe',
 'apstjɛ̃dʁɛ',
 'zigzagje',
 'gʁezij',
 'inalɛ',
 'kɔ̃sɑ̃tʁəʁe',
 'ʁəpejʁe',
 'ʁəkalibʁe',
 'demɑ̃te',
 'apostʁofe',
 'kupaje',
 'abatʁ',
 'tʁavɛʁsɛ',
 'gupije',
 'fɔʁfɛ',
 'bʁigɑ̃',
 'eplyʃɛ',
 'ɛ̃plikəʁa',
 'pʁezyməʁɛ',
 'gaʁdɛʁ',
 'ʁøgaʁni',
 'dekʁiptɑ̃',
 'ʁɔɲɛ',
 'ʁeɑ̃kɔde',
 'syse',
 'paʁaʃytɑ̃',
 'tʁɑ̃sfɔʁm',
 'ɑ̃majote',
 'ʁəsikləʁɔ̃',
 'lɥiʁe',
 'ytilizɛ',
 'kame',
 'dizɛ',
 'eliminəʁɛ',
 'metabolizəʁa',
 'tʁebyʃəʁjɔ̃',
 'difɛʁ',
 'abutiʁɛ',
 'sufle',
 'ɑ̃ʒɥive',
 'detaʃɛ',
 'aneɑ̃tisɔ̃',
 'epwɛ̃te',
 'ɑ̃kadʁəʁɔ̃',
 'aleʃe',
 'faktyʁəʁje',
 'fleʃiʁɛ',
 'tʁepas',
 'flɑ̃bɑ̃',
 'vɛtis',
 'bajɔnɛ',
 'difyzəʁɔ̃',
 'ɑ̃dɔʁmi',
 'ʁəfaktyʁe',
 'ɑ̃lɛdi',
 'sɔ̃ʒəʁɛ',
 'deʒeneʁɛ',
 'degizəʁɛ',
 'aspiʁɛ',
 ...]

In [115]:
# 2. Load the list into Linguistica
# 'morpheme_min_len' and 'affix_min_len' can be adjusted based on word length
dLxa = lxa.from_wordlist(words)

# 3. Run morphological analysis
# Extract signatures (prefix/suffix patterns like NULL-ed-ing-s)
signatures = dLxa.signatures()
# signatures

In [171]:
dfLex4.columns

Index(['1_Mot', '2_Phono', '3_Phono_IPA', '4_Lemme', '5_Cgram', '6_CgramOrtho',
       '7_Genre', '8_Nombre', '9_InfoVER', '10_FreqMot', '11_FreqOrtho',
       '12_FreqLemme', '13_CDOrtho', '14_IsLem', '15_NbLettres', '16_NbPhons',
       '17_OLD20', '18_PLD20', '19_CVOrtho', '20_CVPhono', '21_VoisOrtho',
       '22_VoisPhono', '23_NbHomog', '24_NbHomoph', '25_SyllPhono',
       '26_SyllNb', '27_SyllCV', '28_PUOrtho', '29_PUPhon', '30_MorphoBase',
       '31_MorphoStruct', '32_MorphoDecomp', '33_Preval', '34_PrevalNb',
       '35_RT_FLP', '36_zRT_FLP', '37_Err_FLP'],
      dtype='object')

In [118]:
lWords=dLxa.wordlist()
affixs=dLxa.affixes()
stems=dLxa.stems()

In [170]:
word="ʒapəʁa"
if word in lWords:
    print(word,"is in the lexicon")
else:
    print(word,"is not in the lexicon")

for s in stems:
    if s in word:
        affixes=[a for a in word.split(s) if a!=""]
        print(s,affixes)
        analysable=True
        for affixe in affixes:
            if affixe not in affixs:
                analysable=False
                break
        if analysable:
            print("=>",s,affixes)
            # print("stem in",dLxa.stems_to_words()[s])
            print("stem in",", ".join(set.union(*[phon2Lex[x] for x in dLxa.stems_to_words()[s]])))
            # for affixe in affixes:
            #     print("affix in",dLxa.affixes_to_signatures()[affixe])

ʒapəʁa is not in the lexicon
apəʁ ['ʒ', 'a']
=> apəʁ ['ʒ', 'a']
stem in happer
ʒapə ['ʁa']
=> ʒapə ['ʁa']
stem in jappement, japper
ʒapəʁ ['a']
=> ʒapəʁ ['a']
stem in japper

In [167]:
", ".join(set.union(*[phon2Lex[x] for x in dLxa.stems_to_words()[s]]))

'happer'

In [98]:
cAffixs={}
for w,s in dLxa.words_to_signatures().items():
    affs=list(s)[0]
    for aff in affs:
        if aff not in cAffixs:
            cAffixs[aff]=[]
        cAffixs[aff].append(w)
for k,v in sorted(cAffixs.items(),key=lambda item: len(item[1]),reverse=True):
    print(k,len(v))

NULL 21638
e 18546
ɛ 13718
ɔ̃ 13213
a 12354
je 6263
t 3266
jɔ̃ 3221
ɑ̃ 3172
ʁ 2754
əmɑ̃ 1776
mɑ̃ 1770
̃ 1583
ɛʁ 1574
əʁa 1405
ʁa 1329
ʁɛ 1281
əʁɛ 1260
n 1175
sjɔ̃ 1140
ʁɔ̃ 1092
s 1089
əʁe 1076
k 1047
z 1006
ʁe 1001
əʁɔ̃ 993
œʁ 983
ʒ 880
i 826
bl 669
əʁje 658
m 589
st 568
tœʁ 555
f 508
o 507
v 506
al 487
ʁis 473
l 423
ɑ̃t 417
zm 416
ik 383
aʒ 361
ite 333
d 323
abl 270
te 259
ɛ̃ 244
tʁis 238
jɛ̃ 186
ɛn 183
øz 176
if 160
ʁjɔ̃ 154
jɛn 154
ze 153
ije 146
iv 146
ʁje 144
dʁa 135
dʁe 135
dʁɔ̃ 135
dʁɛ 135
əʁi 119
jɛʁ 117
ist 117
in 116
tik 109
ø 99
ne 98
am 92
ɑ̃s 91
ijɔ̃ 90
g 90
atœʁ 89
vite 86
tif 85
twaʁ 80
izm 80
ɔm 80
ʁi 79
dʁ 78
yʁ 76
tiv 75
waʁ 72
oʒi 71
ɔg 71
an 69
nɛl 64
ɛl 58
ize 58
sjɛ̃ 56
ɛs 54
si 51
sm 50
j 48
iʁ 45
onɛl 45
it 43
ɛt 43
ʒi 42
zɔ̃ 41
id 41
se 40
oʒik 38
ømɑ̃ 37
əte 36
ʒik 36
̃dʁa 35
̃dʁe 35
̃dʁɛ 35
ʃ 33
sjɛn 32
ɛtʁ 31
ɔnɛl 30
jɛl 29
kmɑ̃ 28
is 28
site 28
jɛm 27
onɛʁ 26
vmɑ̃ 25
jɑ̃ 24
zmɑ̃ 24
nist 24
ma 22
etʁi 22
zjɛm 22
amɑ̃ 21
iŋ 20
oz 20
fi 19
ʒist 19
atik 19
u 19
atif 18
ativ 18
iz 18
at 18
ism 18
øt 18
ɛ̃k 18
iliz 17
tɛʁ 16
nik 16
aʁ 16
kle 16
asjɔ 15
eʁe 15
tɛs 15
la 15
il 14
ɔn 14
kyl 14
tʁ 14
mi 14
etik 14
ɛz 14
zi 14
de 13
one 13
ɔne 13
sjɛl 12
ʁo 12
yɛl 12
ɥɛl 12
ja 12
ə 12
na 12
aʁja 12
ɔt 12
ɔs 11
onik 11
ɔnik 11
jø 11
jøz 11
jɔm 11
yn 11
œ̃ 11
ka 10
opi 10
ɔp 10
nɛʁ 10
ɛsk 10
ta 10
tje 10
lɔg 10
ad 10
do 10
mɛtʁ 10
njɛ̃ 10
b 10
fɔn 10
ks 10
lik 10
sjɔ 10
y 10
ylɛʁ 9
on 9
ʁam 9
etʁe 9
tal 8
to 8
enik 8
ibl 7
aliz 6
jɛ 6
diz 6
wa 6
waz 6
loʒi 5
ʁd 4

# Tests sur les mots attestés de Lexique4

In [206]:
dfHead4=dfLex4.loc[dfLex4["10_FreqMot"]>dfLex4["10_FreqMot"].median()]
headPhons=dfHead4["3_Phono_IPA"].tolist()
dfTail4=dfLex4.loc[dfLex4["10_FreqMot"]<=dfLex4["10_FreqMot"].median()]
dfTail4.loc[(dfTail4["5_Cgram"]=="VER")&(~dfTail4["3_Phono_IPA"].isin(headPhons))]

,1_Mot,2_Phono,3_Phono_IPA,4_Lemme,5_Cgram,6_CgramOrtho,7_Genre,8_Nombre,9_InfoVER,10_FreqMot,...,28_PUOrtho,29_PUPhon,30_MorphoBase,31_MorphoStruct,32_MorphoDecomp,33_Preval,34_PrevalNb,35_RT_FLP,36_zRT_FLP,37_Err_FLP
2,marger,maRZe,maʁʒe,marger,VER,VER,NaN,NaN,inf,0.006,...,6,5,marge,0-1-1,/marg(e).er,60.0,25.0,NaN,NaN,NaN
9,absorbiez,apsORbje,apsɔʁbje,absorber,VER,VER,NaN,p,ind:imp:2,0.009,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,entretueraient,@tR°tyRE,ɑ̃tʁətyʁɛ,entretuer,VER,VER,NaN,p,cnd:pre:3,0.019,...,0,0,NaN,NaN,NaN,93.0,16.0,NaN,NaN,NaN
12,déshéritais,dezeRitE,dezeʁitɛ,déshériter,VER,VER,NaN,s,ind:imp:2,0.003,...,0,0,NaN,NaN,NaN,100.0,19.0,NaN,NaN,NaN
18,adoubiez,adubje,adubje,adouber,VER,VER,NaN,p,ind:imp:2,0.003,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189841,nationalisons,nasjonaliz§,nasjonalizɔ̃,nationaliser,VER,VER,NaN,p,imp:pre:1,0.003,...,0,0,NaN,NaN,NaN,100.0,16.0,NaN,NaN,NaN
189842,ramifiant,Ramifj@,ʁamifjɑ̃,ramifier,VER,VER,m,s,NaN,0.003,...,0,0,rame,0-1-2,/ram(e).ifi.ant,94.0,17.0,NaN,NaN,NaN
189851,étourdirait,etuRdiRE,etuʁdiʁɛ,étourdir,VER,VER,NaN,s,cnd:pre:3,0.003,...,0,0,NaN,NaN,NaN,100.0,16.0,NaN,NaN,NaN
189857,soignèrent,swaNER,swaɲɛʁ,soigner,VER,VER,NaN,p,ind:pas:3,0.003,...,0,0,NaN,NaN,NaN,100.0,24.0,NaN,NaN,NaN
189859,généralisais,ZeneRalizE,ʒeneʁalizɛ,généraliser,VER,VER,NaN,s,"ind:imp:2,ind:imp:1",0.009,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [207]:
head2Lex={}
for d in dfHead4[["3_Phono_IPA","4_Lemme"]].to_dict(orient="records"):
    k=d["3_Phono_IPA"]
    v=d["4_Lemme"]
    if k not in head2Lex:
        head2Lex[k]=set()
    head2Lex[k].add(v)
head2Lex

{'dispʁopɔʁsjone': {'disproportionner', 'disproportionné'},
 'akyzɔ̃': {'accuser'},
 'ofisjɑ̃': {'officiant'},
 'puʁɔ̃': {'pouvoir'},
 'duv': {'douve'},
 'atiz': {'attiser'},
 'desule': {'dessaouler', 'dessouler', 'dessoûler', 'désaouler'},
 'efɛktɥe': {'effectuer'},
 'ʁəsɛʁ': {'resserre', 'resserrer', 'resservir'},
 'ʁesit': {'réciter'},
 'mizɛ': {'miser'},
 'ʁəkupe': {'recouper'},
 'fɔ̃səʁɛ': {'foncer'},
 'ʁədiʁiʒe': {'rediriger'},
 'fɛso': {'faisceau'},
 'agʁavəʁa': {'aggraver'},
 'nitʃeɛn': {'nietzschéenne'},
 'dekuvʁiʁɛ': {'découvrir'},
 'dekuvʁ': {'découvrir'},
 'dekole': {'décoller'},
 'desy': {'décevoir', 'déçu'},
 'pozitif': {'positif'},
 'abatʁɛ': {'abattre'},
 'pylyle': {'pulluler'},
 'kakawɛt': {'cacahouète', 'cacahuète'},
 'ekaʁte': {'écarter', 'écarté'},
 'ʁezɛʁv': {'réserve', 'réserver'},
 'asɛje': {'asseoir', 'asseyez'},
 'istɔʁi': {'historier'},
 'kalsɔ̃': {'caleçon'},
 'bʁoʃɛt': {'brochette'},
 'sɛʁvɔ̃': {'servir'},
 'paʁɑ̃t': {'parent'},
 'ɛgmaʁin': {'aigue-marine'},
 'buʁiko': {'bourricot'},
 'kavɛʁnøz': {'caverneux'},
 'kʁijoʒenize': {'cryogéniser', 'cryogénisé', 'cryogénisée', 'cryogénisés'},
 'mytine': {'mutiner', 'mutiné'},
 'tyʁlypinɛ': {'turlupiner'},
 'mɔtilite': {'motilité'},
 'pʁezɑ̃tasjɔ̃': {'présentation'},
 'fʁɛsk': {'fresque'},
 'epinø': {'épineux'},
 'bum': {'boom', 'boum', 'boumer'},
 'ɑ̃ʃɑ̃təmɑ̃': {'enchantement'},
 'fʁijɑ̃': {'friand'},
 'fʁaktyʁe': {'fracturer', 'fracturé'},
 'bɛɲ': {'baigner', 'beigne'},
 'pwasɔ̃klun': {'poisson-clown', 'poissons-clown'},
 'ʁəlɔkalize': {'relocaliser', 'relocalisé'},
 'aleʒe': {'alléger'},
 'ɛskabo': {'escabeau'},
 'distɑ̃se': {'distancer'},
 'ʃasəʁa': {'chasser'},
 'ʁuj': {'rouille', 'rouiller'},
 'ɛ̃pʁesjonabl': {'impressionnable'},
 'debaʁa': {'débarras'},
 'temwaɲe': {'témoigner'},
 'pɛləte': {'pelleter', 'pelletée'},
 'atatɔ̃': {'à tâtons'},
 'kɔsmos': {'cosmos'},
 'mɛ̃tna': {'maintenant'},
 'tɛʁminɛʁ': {'terminer'},
 'filipɛ̃': {'philippin'},
 'bufəʁɛ': {'bouffer'},
 'modyle': {'moduler'},
 'deʃaʁʒɛ': {'décharger'},
 'favoʁizɛ': {'favoriser'},
 'vjabl': {'viable'},
 'ʒɔʁdanjɛ̃': {'jordanien'},
 'kʁijɛ': {'crier'},
 'najtklœb': {'night-club', 'nightclub'},
 'leʒislatœʁ': {'législateur'},
 'lɛmiŋ': {'lemming'},
 'vɛ̃': {'vain', 'venir', 'vin', 'vingt', 'vingts'},
 'apsɔʁbe': {'absorber', 'absorbé'},
 'pufjas': {'pouffiasse', 'poufiasse'},
 'vizitɛ': {'visiter'},
 'wuʃu': {'wushu'},
 'dɑ̃təle': {'denteler', 'dentelé'},
 'etydje': {'étudier', 'étudié'},
 'minim': {'minime'},
 'ʁɛptil': {'reptile'},
 'pʁezyme': {'présumer', 'présumé'},
 'mask': {'masque', 'masquer'},
 'ɑ̃bʁasɛʁ': {'embrasser'},
 'ʁəmɔ̃tɛ': {'remonter'},
 'syksedɛʁ': {'succéder'},
 'bavaʁd': {'bavard', 'bavarder'},
 'otoʁize': {'autoriser', 'autorisé'},
 'ɛ̃tɛʁsɛpsjɔ̃': {'interception'},
 'pilote': {'piloter'},
 'ʁəpɑ̃tiʁ': {'repentir'},
 'pɔʁtəfœj': {'portefeuille'},
 'lu': {'louer', 'loup'},
 'dedikas': {'dédicace', 'dédicacer'},
 'buʁ': {'bour', 'bourg', 'bourre', 'bourrer'},
 'batəlje': {'batelier'},
 'aleʃɑ̃': {'alléchant'},
 'sivilize': {'civiliser', 'civilisé'},
 'bloke': {'bloquer', 'bloqué'},
 'tasit': {'tacite'},
 'ɔʁganizm': {'organisme'},
 'ʁefleʃiʁ': {'réfléchir'},
 'ɑ̃pʁœtœʁ': {'emprunteur'},
 'ɛ̃tybe': {'intuber'},
 'degutɛ': {'dégoûter'},
 'dʁɛsœʁ': {'dresseur'},
 'blɛ̃de': {'blinder', 'blindé'},
 'sɥivi': {'suivi', 'suivre'},
 'swaɲɑ̃': {'soignant', 'soigner'},
 'kaʁa': {'cara', 'carat'},
 'ekut': {'écoute', 'écouter'},
 'ajaj': {'aye-aye'},
 'kɔʁsɛʁ': {'corsaire'},
 'ʁəliʒjø': {'religieux'},
 'sɔʁ': {'sore', 'sors', 'sort', 'sortir'},
 'disimyle': {'dissimuler', 'dissimulé'},
 'debʁujɔ̃': {'débrouiller'},
 'kato': {'catho', 'cato'},
 'imynoloʒi': {'immunologie'},
 'ʁɔdjɔm': {'rhodium'},
 'avuʁa': {'avouer'},
 'degutɑ̃t': {'dégoutante', 'dégoutantes', 'dégoûtant'},
 'akɔ̃pli': {'accompli', 'accomplir'},
 'aleluja': {'alleluia', 'alléluia'},
 'twit': {'tweet',
  'tweete',
  'tweetent',
  'tweetes',
  'tweets',
  'twit',
  'twitte'},
 'kɔ̃sym': {'consumer'},
 'fotogʁafi': {'photographie', 'photographier'},
 'tʁɔ̃pɛt': {'trompeter', 'trompette'},
 'kuvʁiʁɛ': {'couvrir'},
 'vjɛ̃dʁijɔ̃': {'venir'},
 'apaʁɛs': {'apparaître'},
 'apaʁɛtʁɛ': {'apparaitrait', 'apparaître'},
 'maɲ': {'magner'},
 'abyze': {'abuser', 'abusé'},
 'ɑ̃pɔʁtɛ': {'emporter'},
 'nykleɔtid': {'nucléotide'},
 'tɑ̃te': {'tenter', 'tenté'},
 'bʁuje': {'brouiller', 'brouillé'},
 'anyle': {'annuler', 'annulé'},
 'sinonim': {'synonyme'},
 'seksolɔg': {'sexologue'},
 'ʁaləbɔl': {'ras-le-bol'},
 'ʁegʁɛs': {'régresser'},
 'tiʁəʁɔ̃': {'tirer'},
 'kaʃətɔ̃': {'cacheton'},
 'ʃuʁe': {'chourer'},
 'dinɛ': {'dinais', 'dinait', 'dîner'},
 'devalize': {'dévaliser'},
 'kɔ̃fiʁɛ': {'confier'},
 'ɔʁbit': {'orbite', 'orbiter'},
 'flo': {'flo', 'flot', 'flow'},
 'njɛs': {'nièce'},
 'sufʁɑ̃t': {'souffrant'},
 'kɔ̃plis': {'complice'},
 'nɔʁm': {'norme'},
 'tɛʁe': {'taire', 'terrer'},
 'aksidɑ̃te': {'accidenter', 'accidenté'},
 'buma': {'boumer'},
 'asfiksjɑ̃': {'asphyxiant', 'asphyxier'},
 'petɔ̃kl': {'pétoncle'},
 'vɛ̃ky': {'vaincre', 'vaincu'},
 'aʒiʁa': {'agir'},
 'ʁɛspiʁasjɔ̃': {'respiration'},
 'savwaʁfɛʁ': {'savoir-faire'},
 'pɛʁ': {'pair', 'paire', 'perdre', 'pers', 'père'},
 'mɑ̃sɔ̃ʒ': {'mensonge'},
 'tolɥɛn': {'toluène'},
 'pʁɛstatɛʁ': {'prestataire'},
 'iʁepaʁabl': {'irréparable'},
 'ʁəpaʁti': {'repartie', 'repartir'},
 'kloʃaʁ': {'clochard'},
 'sybʒɛktiv': {'subjectif'},
 'ne': {'naître', 'ney', 'nez', 'né'},
 'ɔ̃biliko': {'ombilical'},
 'damaʒ': {'damage'},
 'apœʁe': {'apeurer', 'apeuré'},
 'taʁt': {'tarte'},
 'videoklip': {'vidéo-clip', 'vidéoclip'},
 'epaʁ': {'épars'},
 'kalifiʁje': {'qualifier'},
 'plɑ̃ke': {'planquer', 'planqué'},
 'ʒɑ̃tijɔm': {'gentilhomme', 'gentilhommes'},
 'lav': {'lav', 'lave', 'laver'},
 'gɛ': {'gai', 'gay', 'guet'},
 'ɛ̃tɛʁpoze': {'interposer', 'interposé'},
 'ɛ̃tɛʁvju': {'interview', 'interviewer'},
 'ɔ̃gʁwa': {'hongrois'},
 'deboʃe': {'débaucher', 'débauché'},
 'diplomatik': {'diplomatique'},
 'sekstɑ̃': {'sextant'},
 'negʁijɔ̃': {'négrillon'},
 'aʒiʁɔ̃': {'agir'},
 'sityʁɛ': {'situer'},
 'fɛsɔ̃': {'fesser'},
 'ʁeɛ̃sɛʁsjɔ̃': {'réinsertion'},
 'ɛ̃sonoʁize': {'insonoriser'},
 'pʁomɛnəʁɛ': {'promener'},
 'epaʁɲe': {'épargner'},
 'evolɥe': {'évoluer', 'évolué'},
 'pʁɛskʁi': {'prescrire'},
 'ʁevizɑ̃': {'réviser'},
 'ɛ̃tɛʁpʁetɔ̃': {'interpréter'},
 'makijəʁɛ': {'maquiller'},
 'kalifiʁɛ': {'qualifier'},
 'bʁɑ̃': {'bran', 'brand'},
 'bʁosɛ': {'brosser'},
 'lise': {'lisser', 'lycée'},
 'kɔ̃fli': {'conflit'},
 'ɛskiʁ': {'esquire'},
 'paʁtaʒ': {'partage', 'partager'},
 'komɛʁsjal': {'commercial'},
 'pʁepaʁəʁɛ': {'préparer'},
 'ɛ̃dolɑ̃': {'indolent'},
 'soliv': {'solive'},
 'mɛnəʁɛ': {'mener'},
 'dɛsalmɑ̃': {'dessalement'},
 'maʁmonɛ': {'marmonner'},
 'devwalɛ': {'dévoiler'},
 'puʁisɛ': {'pourrir'},
 'etɛʁnɥɛ': {'éternuer'},
 'benefisjɛ': {'bénéficier'},
 'ɛksit': {'exciter'},
 'pyʁitɛn': {'puritain'},
 'ɛ̃kɔ̃sjɑ̃': {'inconscient'},
 'pʁepaʁasjɔ̃': {'préparation'},
 'piʁoman': {'pyromane'},
 'sapœʁpɔ̃pje': {'sapeur-pompier'},
 'asasina': {'assassinat', 'assassiner'},
 'dømiveʁite': {'demi-vérité'},
 'sœl': {'seul', 'seule'},
 'epɥize': {'épuiser', 'épuisé'},
 'ʁɛsplɑ̃dis': {'resplendir'},
 'ɛ̃spiʁe': {'inspirer', 'inspiré'},
 'ʁɑ̃fɔʁ': {'renfort'},
 'tapin': {'tapiner'},
 'ɑ̃kuʁaʒəʁɛ': {'encourager'},
 'sutʁɛt': {'sous-traiter'},
 'ob': {'aube'},
 'ɛ̃pʁesjonɑ̃': {'impressionnant', 'impressionner'},
 'ʁund': {'round'},
 'nekʁoz': {'nécrose', 'nécroser'},
 'ʁeʒjonal': {'régional'},
 'faʃist': {'fasciste'},
 'lemyʁjɛ̃': {'lémurien'},
 'manigɑ̃sɛ': {'manigancer'},
 'detɛʁɔ̃': {'déterrer'},
 'ʁamɛn': {'ramen', 'ramener'},
 'ipokʁit': {'hypocrite'},
 'detʁɛs': {'détresse', 'détresser'},
 'bagaʒist': {'bagagiste'},
 'matøz': {'matheux'},
 'ʁigɔl': {'rigole', 'rigoler'},
 'kik': {'kick', 'quick'},
 'ɛ̃dy': {'indu'},
 'pœnʃiŋbɔl': {'punching-ball'},
 'pozisjɔn': {'positionner'},
 'naftalɛn': {'naphtalène'},
 'ameljɔʁəʁɔ̃': {'améliorer'},
 'fʁɔ̃tjɛʁ': {'frontière'},
 'kuʁjɛl': {'courriel'},
 'ʁapɔʁte': {'rapporter', 'rapporté'},
 'baʁak': {'baraque', 'baraquer', 'barraque'},
 'ly': {'lire', 'lu', 'lut'},
 'kolostomi': {'colostomie'},
 'plije': {'plier', 'plié'},
 'akɔ̃paɲəʁa': {'accompagner'},
 'gaɲɑ̃': {'gagnant', 'gagner'},
 'menisk': {'ménisque'},
 'ɑ̃titɛz': {'antithèse'},
 'polɛn': {'pollen'},
 'ʁevɛje': {'réveiller'},
 'gʁɔ̃dəʁɛ': {'gronder'},
 'detaje': {'détailler', 'détaillé'},
 'atɛst': {'attester'},
 'ʁələvœʁ': {'releveur'},
 'pɑ̃sy': {'pansu'},
 'diktatœʁ': {'dictateur'},
 'ʁətapise': {'retapisser'},
 'ʁəkony': {'reconnaître', 'reconnu'},
 'ʁam': {'ram', 'rame', 'ramer', 'rams'},
 'bɛta': {'bêta'},
 'dəʁəʃɛf': {'derechef'},
 'ɑ̃bʁwazi': {'ambroisie'},
 'ʁədəmɑ̃de': {'redemander'},
 'aksɛdəʁa': {'accèdera'},
 'sɔnəʁɔ̃': {'sonner'},
 'apaʁtjɛ̃dʁɛ': {'appartenir'},
 'ʁəbwaʁ': {'reboire'},
 'pasjətəʁe': {'patienter'},
 'gygys': {'gugusse'},
 'ʁavaʒ': {'ravage', 'ravager'},
 'kɔ̃siste': {'consister'},
 'diʁiʒəʁje': {'diriger'},
 'djamɑ̃': {'diamant'},
 'gaɲəʁa': {'gagner'},
 'vwale': {'voiler', 'voilé'},
 'delisjøz': {'délicieux'},
 'ʁɑ̃vɛʁsəʁɛ': {'renverser'},
 'nɛʁvyʁ': {'nervure'},
 'fɔjl': {'foil'},
 'ʁøvɔle': {'revoler'},
 'pʁolo': {'prolo'},
 'fʁeʁo': {'frérot'},
 'syʁpʁɑ̃dʁa': {'surprendre'},
 'ʒoniʁ': {'jaunir'},
 'kɔ̃syltasjɔ̃': {'consultation'},
 'pozisjɔnəmɑ̃': {'positionnement'},
 'ʃiʁyʁʒi': {'chirurgie'},
 'sɑ̃gle': {'sangler'},
 'gaʁnityʁ': {'garniture'},
 'gloʁifi': {'glorifier'},
 'kɔ̃siljɑ̃t': {'conciliant'},
 'deminœʁ': {'démineur'},
 'gʁɑ̃d': {'grand'},
 'ɔ̃gl': {'ongle'},
 'muʁɛ': {'mourir'},
 'meʃɑ̃t': {'méchant'},
 'ɑ̃kuʁ': {'encourir', 'encours'},
 'pynisjɔ̃': {'punition'},
 'ɛgziʒe': {'exiger'},
 'ʃiʃitøz': {'chichiteux'},
 'ʁəbyte': {'rebuter'},
 'kʁonik': {'chronique', 'chroniquer'},
 'nɔbl': {'noble'},
 'ɑ̃tidulœʁ': {'anti-douleur', 'antidouleur'},
 'ʁadikalize': {'radicaliser'},
 'kɛlkəʃoz': {'qqch'},
 'pʁeistoʁik': {'préhistorique'},
 'aisɛ': {'haïr'},
 'dekupe': {'découper', 'découpé'},
 'ʃaʁpɑ̃te': {'charpenté'},
 'deb': {'déb'},
 'obwa': {'hautbois'},
 'kɔ̃tʁaʁgymɑ̃': {'contre-argument'},
 'tɛkstil': {'textile'},
 'dezastʁ': {'désastre'},
 'pʁedi': {'prédire', 'prédit'},
 'deziʁəʁɛ': {'désirer'},
 'lwajaləmɑ̃': {'loyalement'},
 'ekaje': {'écailler', 'écaillé'},
 'bɛsɛ': {'baisser'},
 'plasɛʁ': {'placer'},
 'kadɛ': {'cadet'},
 'alteʁofil': {'haltérophile'},
 'deglytisjɔ̃': {'déglutition'},
 'kaʃɛ': {'cacher', 'cachet'},
 'laʃ': {'lâche', 'lâcher'},
 'puʁsɥive': {'poursuivre'},
 'bɔʁde': {'border', 'bordé', 'bordée'},
 'kɔ̃disjɔnɛl': {'conditionnel'},
 'destʁyktœʁ': {'destructeur'},
 'sɥe': {'suer', 'suée'},
 'liʁɔ̃': {'lier', 'lire'},
 'sɛʁpɑ̃tɛ̃': {'serpentin'},
 'ʁɛvas': {'rêvasser'},
 'fʁenetik': {'frénétique'},
 'siɲifikativ': {'significatif'},
 'ʁeʃofəʁa': {'réchauffer'},
 'laʁgaʒ': {'largage', 'larguage'},
 'oʁjɑ̃tal': {'oriental'},
 'n': {'ne'},
 'kɔ̃t': {'compte', 'compter', 'comte', 'conte', 'conter'},
 'vɑ̃piʁize': {'vampiriser'},
 'konɛks': {'connexe'},
 'mitʁaje': {'mitrailler'},
 'sɛlɛ': {'sceller'},
 'ɛ̃kalkylabl': {'incalculable'},
 'abɛs': {'abaisser', 'abbesse'},
 'neozelɑ̃dɛ': {'néo-zélandais'},
 'fuʁʃɛt': {'fourchette'},
 'ʁədutɛ': {'redouter'},
 'melodjøz': {'mélodieux'},
 'niʃɔ̃': {'nicher', 'nichon'},
 'lɛʃky': {'lèche-cul', 'lèche-culs'},
 'ɛ̃flɛksjɔ̃': {'inflexion'},
 'aləmɑ̃d': {'allemand'},
 'ʁəʃɛʁʃəʁɛ': {'rechercher'},
 'ʒeʁəʁɛ': {'gérer'},
 'pɛʁsonalize': {'personnaliser', 'personnalisé'},
 'fil': {'fil', 'file', 'filer'},
 'pʁɛspapje': {'presse-papier', 'presse-papiers'},
 'evanwis': {'évanouir'},
 'ʃaʁibd': {'charybde'},
 'pineal': {'pinéal'},
 'tɛ̃tyʁje': {'teinturier'},
 'ʁasinɛʁ': {'racinaire'},
 'sulɛ': {'saouler', 'soûler'},
 'gʁavimetʁik': {'gravimétrique'},
 'vag': {'vague', 'vaguer'},
 'ʁəfyzɑ̃': {'refuser'},
 'seʁeal': {'céréale'},
 'divɔʁsəʁe': {'divorcer'},
 'idɑ̃tifjɛ': {'identifier'},
 'pikoʁe': {'picorer'},
 'dilatwaʁ': {'dilatoire'},
 'pyni': {'puni', 'punir'},
 'denyde': {'dénuder', 'dénudé'},
 'ɛ̃vite': {'inviter', 'invité'},
 'ɛ̃tɑ̃sifjɑ̃': {'intensifier'},
 'tisʁɛ̃': {'tisserin'},
 'gʁatuj': {'gratouiller'},
 'sɛʁmɔn': {'sermonner'},
 'ɛ̃sɛstɥø': {'incestueux'},
 'ɛkstʁɛməmɑ̃': {'extrêmement'},
 'kʁepit': {'crépiter'},
 'akʁ': {'acre', 'âcre'},
 'ʁɛskij': {'resquille', 'resquiller'},
 'tyb': {'tube', 'tuber'},
 'ʁoti': {'rôti', 'rôtie', 'rôtir'},
 'piliŋ': {'peeling'},
 'ɛ̃syltɑ̃': {'insultant', 'insulter'},
 'fɔsfɔsʁik': {'phosphorique'},
 'kɔ̃tʁe': {'contrer', 'contrée'},
 'utʁəpase': {'outrepasser'},
 'pʁedomin': {'prédominer'},
 'pase': {'passer', 'passè', 'passé'},
 'ʁyze': {'ruser', 'rusé'},
 'daktilogʁafje': {'dactylographier', 'dactylographié'},
 'polip': {'polype'},
 'apotʁ': {'apôtre'},
 'syʁegy': {'suraigu'},
 'malavize': {'malavisé'},
 'tatu': {'tatou', 'tatouer', 'tattoo', 'tattoos'},
 'pɛʁsəvɛ': {'percevoir'},
 'ajø': {'aïeul'},
 'ʁeʃofe': {'réchauffer', 'réchauffé'},
 'sabote': {'saboter'},
 'tab': {'tab'},
 'ʁɑ̃fɔʁse': {'renforcer'},
 'fwɛ̃': {'foin'},
 'kyʁatif': {'curatif'},
 'batifole': {'batifoler'},
 'tablɔid': {'tabloïd'},
 'pʁostɛʁnɔ̃': {'prosterner'},
 'ʁɛjɔn': {'rayonne', 'rayonner'},
 'ɑ̃viʁɔnəmɑ̃to': {'environnemental'},
 'tɛɲø': {'teigneux'},
 'ɑ̃bɛte': {'embêter', 'embêté'},
 'ʒeogʁaf': {'géographe'},
 'ɑ̃tʁəpɔ̃': {'entrepont'},
 'paʁtisipəʁɔ̃': {'participer'},
 'demaskəʁɔ̃': {'démasquer'},
 'stʁidylasjɔ̃': {'stridulation'},
 'tʁɑ̃sfɔʁməʁɔ̃': {'transformer'},
 'bʁikɛ': {'briquet'},
 'tɛʁjɛn': {'terrien'},
 'kʁøzəʁɔ̃': {'creuser'},
 'ɑ̃vizaʒɔ̃': {'envisager'},
 'ajwɛ': {'highway'},
 'ɛ̃ʃɑ̃ʒe': {'inchangé'},
 'okyltizm': {'occultisme'},
 'pipi': {'pipi'},
 'sjɛ̃': {'sien', 'siens'},
 'adoʁabl': {'adorable'},
 'syʁvivɛ': {'survivre'},
 'maʁʃøz': {'marcheur'},
 'disfɔ̃ksjɔn': {'dysfonctionner'},
 'glisəʁɔ̃': {'glisser'},
 'blœf': {'bluff', 'bluffer'},
 'ʒɥif': {'juif'},
 'abazuʁdi': {'abasourdi', 'abasourdir'},
 'likefi': {'liquéfier'},
 'posesif': {'possessif'},
 'apotikɛʁ': {'apothicaire'},
 'afliʒe': {'affliger', 'affligé'},
 'limite': {'limiter', 'limité'},
 'ʃapəlje': {'chapelier'},
 'ɛgzɛʁs': {'exercer'},
 'aspiʁɑ̃': {'aspirant', 'aspirer'},
 'tabl': {'table', 'tabler'},
 'tɔʁbwajo': {'tord-boyaux'},
 'ʃlɛ̃g': {'chlinguer', 'schlinguer'},
 'tʁavɛsti': {'travesti', 'travestir'},
 'ʁɑ̃pəʁɛ': {'ramper'},
 'maʁʃmalo': {'marshmallow'},
 'ɛ̃desi': {'indécis'},
 'vuly': {'vouloir', 'voulu'},
 'polaʁize': {'polariser'},
 'skutœʁ': {'scooter'},
 'gʁijəʁɛ': {'griller'},
 'ebʁɥitɛ': {'ébruiter'},
 'ɑ̃ʒɑ̃dʁa': {'engendrer'},
 'kaplɑ̃': {'caplan'},
 'nikab': {'niqab'},
 'tʁiʃɛ': {'tricher'},
 'siʁys': {'cirrus'},
 'telepɔʁtœʁ': {'téléporteur', 'téléporteurs'},
 'aʃətɛ': {'acheter'},
 'pʁovɛʁb': {'proverbe'},
 'favoʁiz': {'favoriser'},
 'tʁɛ̃bale': {'trimbaler', 'trimballer'},
 'ɛkstɔʁsjɔ̃': {'extorsion'},
 'fɔʁ': {'for', 'forer', 'fors', 'fort'},
 'adɔpta': {'adopter'},
 'taʁod': {'tarauder'},
 'ɑ̃baʁase': {'embarrasser', 'embarrassé'},
 'ʁamasa': {'ramasser'},
 'sukup': {'soucoupe'},
 'izole': {'isoler', 'isolé'},
 'l': {'l', "l'"},
 'abitəʁɛ': {'habiter'},
 'ʒaʁ': {'jar', 'jarre', 'jars'},
 'ɑ̃glɥe': {'engluer', 'englué'},
 'syʁvjɛ̃': {'survenir'},
 'ɑ̃tɛ': {'hanter'},
 'kɔ̃stitɥe': {'constituer', 'constitué'},
 'ʁazmɔt': {'rase-mottes'},
 'ɛ̃vɛstigatœʁ': {'investigateur'},
 'egliz': {'église'},
 'mutaʁd': {'moutarde'},
 'ʁeɲəʁɔ̃': {'régner'},
 'metabolit': {'métabolite'},
 'imitatʁis': {'imitateur'},
 'vɑ̃': {'vendre', 'vent'},
 'astʁ': {'astre'},
 'emɛʁvɛj': {'émerveiller'},
 'pjøte': {'pieuter'},
 'silabys': {'syllabus'},
 'pʁodɥi': {'produire', 'produit'},
 'puʁʃasəʁɛ': {'pourchasser'},
 'tɛʁminəʁe': {'terminer'},
 'sypɛʁvizœʁ': {'superviseur', 'superviseure'},
 'ʁydimɑ̃': {'rudiment'},
 'pleonasm': {'pléonasme'},
 'ɑ̃tisɛptik': {'antiseptique'},
 'abɛsəmɑ̃': {'abaissement'},
 'kɔ̃tʁəməzyʁ': {'contre-mesure'},
 'manjetɔ̃': {'magnéton'},
 'tʁɑ̃pe': {'tremper', 'trempé'},
 'asyʁe': {'assurer', 'assuré'},
 'ʁadjɔm': {'radium'},
 'pʁostɛʁnəʁa': {'prosterner'},
 'ʁədemenaʒe': {'redéménager'},
 'minovɑ̃bʁ': {'mi-novembre'},
 'pije': {'piller'},
 'nugatin': {'nougatine'},
 'ʁəkomɑ̃de': {'recommander', 'recommandé'},
 'ʁeɛl': {'réel'},
 'emuse': {'émousser', 'émoussé'},
 'ɑ̃ʁoləmɑ̃': {'enrôlement'},
 'gʁosisɛ': {'grossir'},
 'titʁa': {'titrer'},
 'buji': {'bouilli', 'bouillie', 'bouillir'},
 'peopeɛs': {'pop'},
 'kɔ̃ʒygal': {'conjugal'},
 'kaʁe': {'carrer', 'carré', 'carrée'},
 'ʁetʁogʁade': {'rétrograder'},
 'ʁəkɔ̃stʁyksjɔ̃': {'reconstruction'},
 'ɑ̃tuʁ': {'entour', 'entourer'},
 'ʁakɔ̃təʁɔ̃': {'raconter'},
 'iʁɛspɛktɥøz': {'irrespectueux'},
 'aeʁasjɔ̃': {'aération'},
 'devəlope': {'développer', 'développé'},
 'fɔʁtifje': {'fortifier', 'fortifié'},
 'dɔʁsal': {'dorsal', 'dorsale'},
 'tɛʁmit': {'termite', 'thermite'},
 'demɑ̃təle': {'démanteler'},
 'ɑ̃nɥije': {'ennuyer', 'ennuyé'},
 'otostopœʁ': {'auto-stoppeur'},
 'pʁodɥizɔ̃': {'produire'},
 'egaʁe': {'égarer', 'égaré'},
 'blaze': {'blaser', 'blasé'},
 'fuʁmij': {'fourmiller'},
 'bɔk': {'bock', 'buck', 'bucks'},
 'ʃɑ̃piɲɔ̃': {'champignon'},
 'tʁasaʒ': {'traçage'},
 'depɑ̃sɑ̃': {'dépenser'},
 'blɑ̃bɛk': {'blanc-bec'},
 'vʁɛsɑ̃blabləmɑ̃': {'vraisemblablement'},
 'ʁətʁɑ̃sfɔʁme': {'retransformer'},
 'opoze': {'opposer', 'opposé'},
 'ekʁazɛ': {'écraser'},
 'ɑ̃paje': {'empailler', 'empaillé'},
 'anɔsmi': {'anosmie'},
 'fokalize': {'focaliser'},
 'tɛ̃bʁ': {'timbre'},
 'ʁɑ̃buʁe': {'rembourrer'},
 'gʁibuje': {'gribouiller'},
 'kɔ̃pylse': {'compulser'},
 'aʒute': {'ajouter', 'ajouté'},
 'sɛʁkœj': {'cercueil'},
 'diminytif': {'diminutif'},
 'otomatikəmɑ̃': {'automatiquement'},
 'li': {'li', 'lie', 'lier', 'lire', 'lit'},
 'obɛʁʒ': {'auberge'},
 'pynitiv': {'punitif'},
 'fɔʁmidabl': {'formidable'},
 'ɔmnipotɑ̃s': {'omnipotence'},
 'flɑ̃be': {'flamber', 'flambé', 'flambée'},
 'loko': {'local', 'loco'},
 'bidu': {'bidou'},
 'anyləʁɔ̃': {'annuler'},
 'kʁwajɑ̃s': {'croyance'},
 'negʁije': {'négrier'},
 'kylpabilizɑ̃': {'culpabiliser'},
 'ʁate': {'rater', 'raté'},
 'lisɑ̃si': {'licencier'},
 'paʁapɛ': {'parapet'},
 'ʃkœlist': {'checklist'},
 'baləʁin': {'ballerine'},
 'tus': {'tousser', 'tout'},
 'aspaʁtam': {'aspartam', 'aspartame'},
 'ʁɛspɔ̃sabl': {'responsable'},
 'episea': {'épicéa'},
 'elaʁʒis': {'élargir'},
 'mɛʁ': {'maire', 'mer', 'mere', 'mère'},
 'atɑ̃sjɔ̃': {'attention'},
 'komemoʁatif': {'commémoratif'},
 'ʒimnaz': {'gymnase'},
 'ʃɔgi': {'shogi'},
 'diskysjɔ̃': {'discussion'},
 'ʁəpʁɔʃəʁɛ': {'reprocher'},
 'pʁije': {'prier'},
 'veje': {'veiller', 'veillé', 'veillée'},
 'pɔʁtik': {'portique'},
 'tɔʁpije': {'torpiller'},
 'onɔʁ': {'honorer'},
 'defɔ̃se': {'défoncer', 'défoncé'},
 'lynɛʁ': {'lunaire'},
 'kʁeditœʁ': {'créditeur'},
 'ɑ̃tʁasit': {'anthracite'},
 'kozɑ̃': {'causant', 'causer'},
 'ʁediʒɛ': {'rédiger'},
 'avwɛ': {'avouer'},
 'dyʁɑ̃': {'durant', 'durer'},
 'deliʁɛ': {'délirer'},
 'plɛɲɑ̃t': {'plaignant'},
 'kaʃotje': {'cachottier'},
 'mate': {'mater', 'matter', 'maté', 'mâter'},
 'lɛkɛl': {'lesquelles', 'lesquels'},
 'pøzɑ̃': {'pesant', 'peser'},
 'fɔʁmɛl': {'formel'},
 'ɑ̃vwa': {'envoi', 'envoye', 'envoyer'},
 'inɛkspeʁimɑ̃te': {'inexpérimenté'},
 'defiʁɛ': {'défier'},
 'pɑ̃da': {'panda'},
 'ɑ̃pale': {'empaler', 'empalé'},
 'detɛste': {'détester', 'détesté'},
 'ʃiʁikaua': {'chiricahua'},
 'ɑ̃tʁəlas': {'entrelacer'},
 'aeʁe': {'aérer', 'aéré'},
 'tiʁbuʃɔ̃': {'tire-bouchon'},
 'ʁəkylɛ': {'reculer'},
 'ɑ̃titəʁoʁizm': {'antiterrorisme'},
 'ɛ̃tɛʁoʒe': {'interroger'},
 'glɑ̃døz': {'glandeur'},
 'totɛm': {'totem'},
 'ɑ̃mele': {'emmêler', 'emmêlé'},
 'nɥizibl': {'nuisible'},
 'aʁʃidjosɛz': {'archidiocèse'},
 'aniile': {'annihiler'},
 'degutɑ̃': {'dégoutants', 'dégouttant', 'dégoûtant', 'dégoûter'},
 'etufɛ': {'étouffer'},
 'ɑ̃tʁɛnœʁ': {'entraineur', 'entraineurs', 'entraîneur'},
 'idɔl': {'idole'},
 'statin': {'statine'},
 'pʁovokatœʁ': {'provocateur'},
 'ɛgzasɛʁbe': {'exacerber', 'exacerbé'},
 'lyteʁjɛ̃': {'luthérien'},
 'slogɑ̃': {'slogan'},
 'sedɥize': {'séduire'},
 'øklidjɛn': {'euclidien'},
 'pʁatike': {'pratiquer'},
 'kamɑ̃bɛʁ': {'camembert'},
 'kina': {'kina'},
 'ipovɔlemi': {'hypovolémie'},
 'ʁəʃaʁʒ': {'recharge', 'recharger'},

In [208]:
headWords=dfHead4["3_Phono_IPA"].tolist()
headWords=[str(w) for w in headWords]
headWords

['dispʁopɔʁsjone',
 'akyzɔ̃',
 'ofisjɑ̃',
 'puʁɔ̃',
 'duv',
 'atiz',
 'desule',
 'efɛktɥe',
 'ʁəsɛʁ',
 'ʁesit',
 'mizɛ',
 'ʁəkupe',
 'fɔ̃səʁɛ',
 'ʁədiʁiʒe',
 'fɛso',
 'agʁavəʁa',
 'nitʃeɛn',
 'dekuvʁiʁɛ',
 'dekuvʁ',
 'dekole',
 'desy',
 'pozitif',
 'abatʁɛ',
 'pylyle',
 'kakawɛt',
 'ekaʁte',
 'ʁezɛʁv',
 'asɛje',
 'istɔʁi',
 'kalsɔ̃',
 'bʁoʃɛt',
 'sɛʁvɔ̃',
 'paʁɑ̃t',
 'ɛgmaʁin',
 'buʁiko',
 'kavɛʁnøz',
 'kʁijoʒenize',
 'mytine',
 'tyʁlypinɛ',
 'mɔtilite',
 'pʁezɑ̃tasjɔ̃',
 'fʁɛsk',
 'epinø',
 'bum',
 'ɑ̃ʃɑ̃təmɑ̃',
 'fʁijɑ̃',
 'fʁaktyʁe',
 'bɛɲ',
 'pwasɔ̃klun',
 'ʁəlɔkalize',
 'aleʒe',
 'ɛskabo',
 'distɑ̃se',
 'ʃasəʁa',
 'ʁuj',
 'ɛ̃pʁesjonabl',
 'debaʁa',
 'temwaɲe',
 'pɛləte',
 'atatɔ̃',
 'kɔsmos',
 'mɛ̃tna',
 'tɛʁminɛʁ',
 'filipɛ̃',
 'bufəʁɛ',
 'modyle',
 'deʃaʁʒɛ',
 'favoʁizɛ',
 'vjabl',
 'ʒɔʁdanjɛ̃',
 'kʁijɛ',
 'najtklœb',
 'leʒislatœʁ',
 'lɛmiŋ',
 'vɛ̃',
 'apsɔʁbe',
 'pufjas',
 'vizitɛ',
 'wuʃu',
 'dɑ̃təle',
 'etydje',
 'minim',
 'ʁɛptil',
 'pʁezyme',
 'mask',
 'ɑ̃bʁasɛʁ',
 'ʁəmɔ̃tɛ',
 'syksedɛʁ',
 'bavaʁd',
 'otoʁize',
 'ɛ̃tɛʁsɛpsjɔ̃',
 'pilote',
 'ʁəpɑ̃tiʁ',
 'pɔʁtəfœj',
 'lu',
 'dedikas',
 'buʁ',
 'batəlje',
 'aleʃɑ̃',
 'sivilize',
 'bloke',
 'tasit',
 'ɔʁganizm',
 'ʁefleʃiʁ',
 'ɑ̃pʁœtœʁ',
 'ɛ̃tybe',
 'degutɛ',
 'dʁɛsœʁ',
 'blɛ̃de',
 'sɥivi',
 'swaɲɑ̃',
 'kaʁa',
 'ekut',
 'ajaj',
 'kɔʁsɛʁ',
 'ʁəliʒjø',
 'sɔʁ',
 'disimyle',
 'debʁujɔ̃',
 'kato',
 'imynoloʒi',
 'ʁɔdjɔm',
 'avuʁa',
 'degutɑ̃t',
 'akɔ̃pli',
 'aleluja',
 'twit',
 'kɔ̃sym',
 'fotogʁafi',
 'tʁɔ̃pɛt',
 'kuvʁiʁɛ',
 'vjɛ̃dʁijɔ̃',
 'apaʁɛs',
 'apaʁɛtʁɛ',
 'maɲ',
 'abyze',
 'ɑ̃pɔʁtɛ',
 'nykleɔtid',
 'tɑ̃te',
 'bʁuje',
 'anyle',
 'sinonim',
 'seksolɔg',
 'ʁaləbɔl',
 'ʁegʁɛs',
 'tiʁəʁɔ̃',
 'kaʃətɔ̃',
 'ʃuʁe',
 'dinɛ',
 'devalize',
 'kɔ̃fiʁɛ',
 'ɔʁbit',
 'flo',
 'njɛs',
 'sufʁɑ̃t',
 'kɔ̃plis',
 'nɔʁm',
 'tɛʁe',
 'aksidɑ̃te',
 'buma',
 'asfiksjɑ̃',
 'petɔ̃kl',
 'vɛ̃ky',
 'aʒiʁa',
 'ʁɛspiʁasjɔ̃',
 'savwaʁfɛʁ',
 'pɛʁ',
 'mɑ̃sɔ̃ʒ',
 'tolɥɛn',
 'pʁɛstatɛʁ',
 'iʁepaʁabl',
 'ʁəpaʁti',
 'kloʃaʁ',
 'sybʒɛktiv',
 'ne',
 'ɔ̃biliko',
 'damaʒ',
 'apœʁe',
 'taʁt',
 'videoklip',
 'epaʁ',
 'kalifiʁje',
 'plɑ̃ke',
 'ʒɑ̃tijɔm',
 'lav',
 'gɛ',
 'ɛ̃tɛʁpoze',
 'ɛ̃tɛʁvju',
 'ɔ̃gʁwa',
 'deboʃe',
 'diplomatik',
 'sekstɑ̃',
 'negʁijɔ̃',
 'aʒiʁɔ̃',
 'sityʁɛ',
 'fɛsɔ̃',
 'ʁeɛ̃sɛʁsjɔ̃',
 'ɛ̃sonoʁize',
 'pʁomɛnəʁɛ',
 'epaʁɲe',
 'evolɥe',
 'pʁɛskʁi',
 'ʁevizɑ̃',
 'ɛ̃tɛʁpʁetɔ̃',
 'makijəʁɛ',
 'kalifiʁɛ',
 'bʁɑ̃',
 'bʁosɛ',
 'lise',
 'kɔ̃fli',
 'ɛskiʁ',
 'paʁtaʒ',
 'komɛʁsjal',
 'pʁepaʁəʁɛ',
 'ɛ̃dolɑ̃',
 'soliv',
 'mɛnəʁɛ',
 'dɛsalmɑ̃',
 'maʁmonɛ',
 'devwalɛ',
 'puʁisɛ',
 'etɛʁnɥɛ',
 'benefisjɛ',
 'ɛksit',
 'pyʁitɛn',
 'ɛ̃kɔ̃sjɑ̃',
 'pʁepaʁasjɔ̃',
 'piʁoman',
 'sapœʁpɔ̃pje',
 'asasina',
 'dømiveʁite',
 'sœl',
 'epɥize',
 'ʁɛsplɑ̃dis',
 'ɛ̃spiʁe',
 'ʁɑ̃fɔʁ',
 'tapin',
 'ɑ̃kuʁaʒəʁɛ',
 'sutʁɛt',
 'ob',
 'ɛ̃pʁesjonɑ̃',
 'ʁund',
 'nekʁoz',
 'ʁeʒjonal',
 'faʃist',
 'lemyʁjɛ̃',
 'manigɑ̃sɛ',
 'detɛʁɔ̃',
 'ʁamɛn',
 'ipokʁit',
 'detʁɛs',
 'bagaʒist',
 'matøz',
 'ʁigɔl',
 'kik',
 'ɛ̃dy',
 'pœnʃiŋbɔl',
 'pozisjɔn',
 'naftalɛn',
 'ameljɔʁəʁɔ̃',
 'fʁɔ̃tjɛʁ',
 'kuʁjɛl',
 'ʁapɔʁte',
 'baʁak',
 'ly',
 'kolostomi',
 'plije',
 'akɔ̃paɲəʁa',
 'gaɲɑ̃',
 'menisk',
 'ɑ̃titɛz',
 'polɛn',
 'ʁevɛje',
 'gʁɔ̃dəʁɛ',
 'detaje',
 'atɛst',
 'ʁələvœʁ',
 'pɑ̃sy',
 'diktatœʁ',
 'ʁətapise',
 'ʁəkony',
 'ʁam',
 'bɛta',
 'dəʁəʃɛf',
 'ɑ̃bʁwazi',
 'ʁədəmɑ̃de',
 'aksɛdəʁa',
 'sɔnəʁɔ̃',
 'apaʁtjɛ̃dʁɛ',
 'ʁəbwaʁ',
 'pasjətəʁe',
 'gygys',
 'ʁavaʒ',
 'kɔ̃siste',
 'diʁiʒəʁje',
 'djamɑ̃',
 'gaɲəʁa',
 'vwale',
 'delisjøz',
 'ʁɑ̃vɛʁsəʁɛ',
 'nɛʁvyʁ',
 'fɔjl',
 'ʁøvɔle',
 'pʁolo',
 'fʁeʁo',
 'syʁpʁɑ̃dʁa',
 'ʒoniʁ',
 'kɔ̃syltasjɔ̃',
 'pozisjɔnəmɑ̃',
 'ʃiʁyʁʒi',
 'sɑ̃gle',
 'gaʁnityʁ',
 'gloʁifi',
 'kɔ̃siljɑ̃t',
 'deminœʁ',
 'aleʒe',
 'gʁɑ̃d',
 'ɔ̃gl',
 'muʁɛ',
 'meʃɑ̃t',
 'ɑ̃kuʁ',
 'pynisjɔ̃',
 'ɛgziʒe',
 'ʃiʃitøz',
 'ʁəbyte',
 'kʁonik',
 'nɔbl',
 'ɑ̃tidulœʁ',
 'ʁadikalize',
 'kɛlkəʃoz',
 'pʁeistoʁik',
 'aisɛ',
 'dekupe',
 'ʃaʁpɑ̃te',
 'deb',
 'obwa',
 'kɔ̃tʁaʁgymɑ̃',
 'tɛkstil',
 'dezastʁ',
 'pʁedi',
 'deziʁəʁɛ',
 'lwajaləmɑ̃',
 'ekaje',
 'bɛsɛ',
 'plasɛʁ',
 'kadɛ',
 'alteʁofil',
 'deglytisjɔ̃',
 'kaʃɛ',
 'laʃ',
 'puʁsɥive',
 'bɔʁde',
 'kɔ̃disjɔnɛl',
 'destʁyktœʁ',
 'sɥe',
 'liʁɔ̃',
 'sɛʁpɑ̃tɛ̃',
 'ʁɛvas',
 'fʁenetik',
 'siɲifikativ',
 'ʁeʃofəʁa',
 'laʁgaʒ',
 'oʁjɑ̃tal',
 'n',
 'kɔ̃t',
 'vɑ̃piʁize',
 'konɛks',
 'mitʁaje',
 'sɛlɛ',
 'ɛ̃kalkylabl',
 'abɛs',
 'neozelɑ̃dɛ',
 'fuʁʃɛt',
 'ʁədutɛ',
 'melodjøz',
 'niʃɔ̃',
 'lɛʃky',
 'ɛ̃flɛksjɔ̃',
 'aləmɑ̃d',
 'ʁəʃɛʁʃəʁɛ',
 'ʒeʁəʁɛ',
 'pɛʁsonalize',
 'fil',
 'pʁɛspapje',
 'evanwis',
 'ʃaʁibd',
 'pineal',
 'tɛ̃tyʁje',
 'ʁasinɛʁ',
 'sulɛ',
 'gʁavimetʁik',
 'vag',
 'ʁəfyzɑ̃',
 'seʁeal',
 'divɔʁsəʁe',
 'idɑ̃tifjɛ',
 'pikoʁe',
 'dilatwaʁ',
 'pyni',
 'denyde',
 'ɛ̃vite',
 'ɛ̃tɑ̃sifjɑ̃',
 'tisʁɛ̃',
 'gʁatuj',
 'sɛʁmɔn',
 'ɛ̃sɛstɥø',
 'ɛkstʁɛməmɑ̃',
 'kʁepit',
 'akʁ',
 'ʁɛskij',
 'tyb',
 'ʁoti',
 'piliŋ',
 'ɛ̃syltɑ̃',
 'fɔsfɔsʁik',
 'kɔ̃tʁe',
 'utʁəpase',
 'pʁedomin',
 'pase',
 'ʁyze',
 'daktilogʁafje',
 'polip',
 'apotʁ',
 'syʁegy',
 'malavize',
 'tatu',
 'najtklœb',
 'pɛʁsəvɛ',
 'ajø',
 'ʁeʃofe',
 'sabote',
 'tab',
 'ʁɑ̃fɔʁse',
 'fwɛ̃',
 'kyʁatif',
 'batifole',
 'tablɔid',
 'pʁostɛʁnɔ̃',
 'ʁɛjɔn',
 'ɑ̃viʁɔnəmɑ̃to',
 'tɛɲø',
 'ɑ̃bɛte',
 'ʒeogʁaf',
 'ɑ̃tʁəpɔ̃',
 'paʁtisipəʁɔ̃',
 'demaskəʁɔ̃',
 'stʁidylasjɔ̃',
 'tʁɑ̃sfɔʁməʁɔ̃',
 'bʁikɛ',
 'tɛʁjɛn',
 'kʁøzəʁɔ̃',
 'ɑ̃vizaʒɔ̃',
 'ajwɛ',
 'ɛ̃ʃɑ̃ʒe',
 'okyltizm',
 'pipi',
 'sjɛ̃',
 'adoʁabl',
 'syʁvivɛ',
 'maʁʃøz',
 'disfɔ̃ksjɔn',
 'glisəʁɔ̃',
 'blœf',
 'ʒɥif',
 'abazuʁdi',
 'likefi',
 'posesif',
 'apotikɛʁ',
 'afliʒe',
 'limite',
 'ʃapəlje',
 'ɛgzɛʁs',
 'aspiʁɑ̃',
 'tabl',
 'tɔʁbwajo',
 'ʃlɛ̃g',
 'tʁavɛsti',
 'ʁɑ̃pəʁɛ',
 'maʁʃmalo',
 'ɛ̃desi',
 'vuly',
 'polaʁize',
 'skutœʁ',
 'gʁijəʁɛ',
 'ebʁɥitɛ',
 'ɑ̃ʒɑ̃dʁa',
 'kaplɑ̃',
 'nikab',
 'tʁiʃɛ',
 'siʁys',
 'telepɔʁtœʁ',
 'aʃətɛ',
 'pʁovɛʁb',
 'favoʁiz',
 'tʁɛ̃bale',
 'ɛkstɔʁsjɔ̃',
 'fɔʁ',
 'adɔpta',
 'taʁod',
 'ɑ̃baʁase',
 'ʁamasa',
 'sukup',
 'izole',
 'l',
 'abitəʁɛ',
 'ʒaʁ',
 'ɑ̃glɥe',
 'syʁvjɛ̃',
 'ɑ̃tɛ',
 'kɔ̃stitɥe',
 'ʁazmɔt',
 'ɛ̃vɛstigatœʁ',
 'egliz',
 'mutaʁd',
 'ʁeɲəʁɔ̃',
 'metabolit',
 'imitatʁis',
 'vɑ̃',
 'astʁ',
 'emɛʁvɛj',
 'pjøte',
 'silabys',
 'pʁodɥi',
 'puʁʃasəʁɛ',
 'tɛʁminəʁe',
 'sypɛʁvizœʁ',
 'ʁydimɑ̃',
 'pleonasm',
 'ɑ̃tisɛptik',
 'abɛsəmɑ̃',
 'kɔ̃tʁəməzyʁ',
 'manjetɔ̃',
 'tʁɑ̃pe',
 'asyʁe',
 'ʁadjɔm',
 'pʁostɛʁnəʁa',
 'ʁədemenaʒe',
 'minovɑ̃bʁ',
 'pije',
 'nugatin',
 'ʁəkomɑ̃de',
 'ʁeɛl',
 'emuse',
 'ɑ̃ʁoləmɑ̃',
 'gʁosisɛ',
 'titʁa',
 'buji',
 'peopeɛs',
 'kɔ̃ʒygal',
 'kaʁe',
 'ʁetʁogʁade',
 'ʁəkɔ̃stʁyksjɔ̃',
 'ɑ̃tuʁ',
 'ʁakɔ̃təʁɔ̃',
 'iʁɛspɛktɥøz',
 'aeʁasjɔ̃',
 'devəlope',
 'fɔʁtifje',
 'dɔʁsal',
 'tɛʁmit',
 'deboʃe',
 'demɑ̃təle',
 'ɑ̃nɥije',
 'otostopœʁ',
 'pʁodɥizɔ̃',
 'egaʁe',
 'blaze',
 'fuʁmij',
 'bɔk',
 'ʃɑ̃piɲɔ̃',
 'tʁasaʒ',
 'depɑ̃sɑ̃',
 'blɑ̃bɛk',
 'vʁɛsɑ̃blabləmɑ̃',
 'ʁətʁɑ̃sfɔʁme',
 'opoze',
 'ekʁazɛ',
 'ɑ̃paje',
 'anɔsmi',
 'fokalize',
 'tɛ̃bʁ',
 'ʁɑ̃buʁe',
 'kɔ̃t',
 'gʁibuje',
 'kɔ̃pylse',
 'aʒute',
 'sɛʁkœj',
 'diminytif',
 'otomatikəmɑ̃',
 'li',
 'obɛʁʒ',
 'pynitiv',
 'fɔʁmidabl',
 'ɔmnipotɑ̃s',
 'flɑ̃be',
 'loko',
 'bidu',
 'anyləʁɔ̃',
 'kʁwajɑ̃s',
 'negʁije',
 'kylpabilizɑ̃',
 'ʁate',
 'lisɑ̃si',
 'paʁapɛ',
 'ʃkœlist',
 'baləʁin',
 'tus',
 'aspaʁtam',
 'ʁɛspɔ̃sabl',
 'episea',
 'elaʁʒis',
 'mɛʁ',
 'atɑ̃sjɔ̃',
 'komemoʁatif',
 'ʒimnaz',
 'ʃɔgi',
 'diskysjɔ̃',
 'ʁəpʁɔʃəʁɛ',
 'pʁije',
 'veje',
 'pɔʁtik',
 'tɔʁpije',
 'onɔʁ',
 'defɔ̃se',
 'lynɛʁ',
 'kʁeditœʁ',
 'ɑ̃tʁasit',
 'kozɑ̃',
 'ʁediʒɛ',
 'avwɛ',
 'dyʁɑ̃',
 'deliʁɛ',
 'plɛɲɑ̃t',
 'kaʃotje',
 'mate',
 'lɛkɛl',
 'pøzɑ̃',
 'fɔʁmɛl',
 'ɑ̃vwa',
 'inɛkspeʁimɑ̃te',
 'defiʁɛ',
 'pɑ̃da',
 'ɑ̃pale',
 'detɛste',
 'ʃiʁikaua',
 'ɑ̃tʁəlas',
 'aeʁe',
 'etydje',
 'tiʁbuʃɔ̃',
 'ʁəkylɛ',
 'ɑ̃titəʁoʁizm',
 'ɛ̃tɛʁoʒe',
 'glɑ̃døz',
 'totɛm',
 'ɑ̃mele',
 'nɥizibl',
 'aʁʃidjosɛz',
 'aniile',
 'degutɑ̃',
 'etufɛ',
 'ɑ̃tʁɛnœʁ',
 'idɔl',
 'statin',
 'pʁovokatœʁ',
 'ɛgzasɛʁbe',
 'lyteʁjɛ̃',
 'slogɑ̃',
 'sedɥize',
 'øklidjɛn',
 'pʁatike',
 'denyde',
 'kamɑ̃bɛʁ',
 'kina',
 'ipovɔlemi',
 'ʁəʃaʁʒ',
 'poʃe',
 'deklaʁasjɔ̃',
 'deʁivatif',
 'ɛstima',
 'epaʁpije',
 'banis',
 'kaʃe',
 'dekoloʁɑ̃',
 'plœʁɑ̃',
 'ʁəbif',
 'ʒɛte',
 'poli',
 'sodomit',
 'pɔk',
 'pʁevjɛ̃',
 'ataʃɑ̃',
 'maʁmɔn',
 'memo',
 'malnytʁisjɔ̃',
 'tjɛ̃dʁijɔ̃',
 'kɔ̃tʁaʁjɑ̃t',
 'bekas',
 'alʃimist',
 'paʁke',
 'aʃabe',
 'vaʁjɑ̃s',
 'oze',
 'bʁɛtœʁ',
 'plastʁɔ̃',
 'z',
 'koʁegʁaf',
 'knikœʁs',
 'ʁapɛləʁa',
 'komynike',
 'ʒɛʁme',
 'pikote',
 'paʁ',
 'eʒakyl',
 'mwajɛn',
 'otoʒeʁe',
 'ʒibje',
 'ʁepɔ̃',
 'amwɛ̃dʁi',
 'pɛ̃tad',
 'desidəʁa',
 'ʁaze',
 'debɔʁdɛ',
 'tʁuj',
 'bul',
 'ʃaʁɔ̃',
 'plɛ̃dʁa',
 'mule',
 'ʁeveʁɑ̃',
 'ʁəbuʃe',
 'kuvʁe',
 'ʁɑ̃do',
 'ɛksklyzivəmɑ̃',
 'simylakʁ',
 'kaʃɛʁ',
 'ʁətuʃe',
 'ʁealizɛ',
 'ɛkspylse',
 'fɔʁtɥi',
 'ɑ̃tas',
 'sɛ̃tte',
 'ʁədemaʁ',
 'ɛgzɛʁsɛ',
 'epuzəʁje',
 'sɔ̃ʒ',
 'dɛɲ',
 'ɛ̃tityle',
 'etydjɛ',
 'mustaʃ',
 'ɔʁbitɑ̃',
 'ɛ̃fɔʁmatʁis',
 'kafe',
 'skubidu',
 'stoik',
 'dada',
 'toleʁɛ',
 'bjɛ̃',
 'pikœp',
 'taze',
 'aliteʁasjɔ̃',
 'pɔstdate',
 'tisɔ̃',
 'gʁezije',
 'sufle',
 'ɑ̃guʁdi',
 'syʁvi',
 'bedwɛ̃',
 'kolɛ̃majaʁ',
 'ʒezɥit',
 'nɔʁmal',
 'galɑ̃t',
 'aʒitɛ',
 'ʁyʒisɑ̃',
 'abʁi',
 'ɑ̃bɛtəʁɛ',
 'fuʁbəʁi',
 'ɑ̃peʃe',
 'kʁakəlyʁ',
 'ʁɑ̃buʁsəʁa',
 'aʁnika',
 'emɑ̃sipe',
 'bʁɑ̃dise',
 'kuʁɔnəmɑ̃',
 'odəvi',
 'ʁitm',
 'ipoteke',
 'devɛʁsɔ̃',
 'tʁɛ̃bal',
 'buʃɛ',
 'flɑ̃ʃ',
 'taoist',
 'bjɛ̃neme',
 'diminɥɔ̃',
 'ʁagajaʁdi',
 'ʒenitœʁ',
 'ʒeneʁal',
 'delimite',
 'ɛstime',
 'sizo',
 'etʁɑ̃gləʁɛ',
 'ɑ̃dyʁsi',
 'ɛgzɔʁsiz',
 'adɔʁəʁɛ',
 'fʁystʁe',
 'ʁətiʁe',
 'ɔpte',
 'niilist',
 'otoʁitɛʁ',
 'depɑ̃se',
 'ʁikan',
 'ɛkspɛʁt',
 'buʁdɔnəmɑ̃',
 'defetist',
 'siʁo',
 'sɛ̃dikal',
 'nɥizɛ',
 'pløvʁa',
 'valsøz',
 'fuʁyʁ',
 'devastatʁis',
 'tiʁamizy',
 'veky',
 'ʁepɑ̃dʁɛ',
 'apetisɑ̃t',
 'asiɲasjɔ̃',
 'ɑ̃tiameʁikɛ̃',
 'gaʁgɑ̃tɥɛsk',
 'fiʃe',
 'nøtʁalizɑ̃',
 'inɛgzakt',
 'vizigo',
 'pʁesiŋ',
 'ʁiʒid',
 'pilyl',
 'tisəʁɑ̃d',
 'ʁasjonalizasjɔ̃',
 'ɑ̃flame',
 'opeʁatʁis',
 'ʁəkole',
 'ʁəbatʁ',
 'salybʁ',
 'pʁotɛst',
 'demateʁjaliz',
 'kɔ̃tinɥɛl',
 'fysje',
 'dɛlafʁɑ̃sɛska',
 'ɑ̃pwazɔnəʁɛ',
 'ɛ̃diʁɛktəmɑ̃',
 'kuʁʒɛt',
 'afly',
 'ʁenɔvɔ̃',
 'dɛʁmatit',
 'kɔ̃ble',
 'blœf',
 'fizikəmɑ̃',
 'dyvɛ',
 'apaʁɛsɔ̃',
 'gɑ̃gʁene',
 'syʁvɛjəʁɛ',
 'ɔst',
 'suʁiʁe',
 'ʁasist',
 'petʁifje',
 'minœʁ',
 'puʁvwajøz',
 'ʁakle',
 'djapazɔ̃',
 'ɑ̃vwaje',
 'begœl',
 'nøtʁɔ̃',
 'belje',
 'ʁavitaje',
 'aʃɛs',
 'nɔ̃ʁøtuʁ',
 'blɑ̃ʃisəmɑ̃',
 'saltɛ̃bɑ̃k',
 'fʁystʁe',
 'blam',
 'ideo',
 'libeʁal',
 'tʁudyk',
 'debaʁasəʁɔ̃',
 'note',
 'kalkyl',
 'ɛskaʁpɛ̃',
 'pɛʁpetɥɛl',
 'dezɑ̃paʁe',
 'emisɛʁ',
 'kɛstjonɔ̃',
 'ʒaʁdinɛ',
 'kadastʁ',
 'ale',
 'djafan',
 'ʁapœʁ',
 'mas',
 'pɛʁsɑ̃',
 'pɛʁmɛt',
 'pʁovidɑ̃sjɛl',
 'ʁepete',
 'sɛʁfœj',
 'ʁezistəʁa',
 'some',
 'kapyʃɔ̃',
 'ba',
 'pʁɔspɛktœʁ',
 'tu',
 'ʁɛjonɑ̃t',
 'kamjɔ̃',
 'ʁamɛt',
 'pʁɔsɛdəʁɔ̃',
 'ɑ̃bwate',
 'vʁɛmɑ̃',
 'dømidoz',
 'ɛ̃pɛʁtinɑ̃t',
 'ɛ̃dik',
 'fla',
 'ɔʁpist',
 'dezistəmɑ̃',
 'stiʁɔmus',
 'ʁeysisɑ̃',
 'osøz',
 'ʒybilasjɔ̃',
 'aksjɔn',
 'ɑ̃ʃ',
 'syʁvɛ',
 'bag',
 'pynisɛ',
 'aʁɔ̃disɔ̃',
 'bʁɛf',
 'fabʁikɑ̃t',
 'koʁeɛ̃',
 'fʁemi',
 'ʁəkuʁbe',
 'ʁənɔ̃sɛ',
 'aʁtefakt',
 'ɛm',
 'ɛ̃kaʁseʁe',
 'tane',
 'fele',
 'pjɛʒ',
 'efʁejɛ',
 'kaʃɔtjɛʁ',
 'plɑ̃te',
 'akɔ̃paɲəmɑ̃',
 'ʁəpɑ̃sje',
 'aʁbɔʁetɔm',
 'sɑ̃ti',
 'apsyʁdəmɑ̃',
 'kʁɛ̃t',
 'ɛ̃fɛstasjɔ̃',
 'lɛd',
 'aklamasjɔ̃',
 'nɔʁameʁikɛn',
 'mɔ̃taʒ',
 'pɑ̃dyl',
 'ɛ̃teʁese',
 'komɑ̃',
 'apɥiʁɛ',
 'ɛsɥije',
 'mɑ̃daʁin',
 'syʁpʁizpaʁti',
 'ʁəʒwɛ̃t',
 'ʁetʁogʁad',
 'siʁote',
 'kʁyote',
 'ʁɛktifjɔ̃',
 'kʁɑ̃pɔn',
 'ʃuflœʁ',
 'admiʁjɔ̃',
 'salaʁjal',
 'ʁezistəʁɔ̃',
 'malvəny',
 'anyle',
 'ʁapʁoʃe',
 'klue',
 'yni',
 'epise',
 'litɥanjɛ̃',
 'bɔ̃',
 'liʁizm',
 'sekylɛʁ',
 'kɔ̃disjonœʁ',
 'paʁsi',
 'flate',
 'kɔ̃tʁaktɥɛl',
 'aniv',
 'apʁuv',
 'iɲoʁɛ',
 'apeze',
 'skon',
 'ʁɔ̃dəkɥiʁ',
 'ʁekypeʁɔ̃',
 'ipnɔteʁapi',
 'tʁɑ̃ʃɛ',
 'ɛkspylse',
 'tɑ̃tjɔ̃',
 'ʁəmaʁkjɔ̃',
 'paʁwasjal',
 'detɛʁœʁ',
 'spa',
 'kʁwaʁɛ',
 ...]

In [209]:
headVerbs=dfHead4.loc[dfHead4["5_Cgram"]=="VER"]["3_Phono_IPA"].tolist()
headVerbs=[str(w) for w in headVerbs]
headVerbs

['dispʁopɔʁsjone',
 'akyzɔ̃',
 'puʁɔ̃',
 'atiz',
 'desule',
 'efɛktɥe',
 'ʁəsɛʁ',
 'ʁesit',
 'mizɛ',
 'ʁəkupe',
 'fɔ̃səʁɛ',
 'ʁədiʁiʒe',
 'agʁavəʁa',
 'dekuvʁiʁɛ',
 'dekuvʁ',
 'dekole',
 'abatʁɛ',
 'pylyle',
 'ʁezɛʁv',
 'asɛje',
 'istɔʁi',
 'sɛʁvɔ̃',
 'tyʁlypinɛ',
 'fʁaktyʁe',
 'bɛɲ',
 'aleʒe',
 'distɑ̃se',
 'ʃasəʁa',
 'temwaɲe',
 'tɛʁminɛʁ',
 'bufəʁɛ',
 'modyle',
 'deʃaʁʒɛ',
 'favoʁizɛ',
 'kʁijɛ',
 'apsɔʁbe',
 'vizitɛ',
 'dɑ̃təle',
 'etydje',
 'pʁezyme',
 'mask',
 'ɑ̃bʁasɛʁ',
 'ʁəmɔ̃tɛ',
 'syksedɛʁ',
 'otoʁize',
 'pilote',
 'ʁəpɑ̃tiʁ',
 'lu',
 'dedikas',
 'ʁefleʃiʁ',
 'ɛ̃tybe',
 'degutɛ',
 'blɛ̃de',
 'sɥivi',
 'ekut',
 'disimyle',
 'debʁujɔ̃',
 'avuʁa',
 'kɔ̃sym',
 'tʁɔ̃pɛt',
 'kuvʁiʁɛ',
 'vjɛ̃dʁijɔ̃',
 'apaʁɛs',
 'maɲ',
 'ɑ̃pɔʁtɛ',
 'tɑ̃te',
 'bʁuje',
 'ʁegʁɛs',
 'tiʁəʁɔ̃',
 'ʃuʁe',
 'dinɛ',
 'devalize',
 'kɔ̃fiʁɛ',
 'tɛʁe',
 'buma',
 'asfiksjɑ̃',
 'aʒiʁa',
 'ʁəpaʁti',
 'apœʁe',
 'kalifiʁje',
 'ɛ̃tɛʁpoze',
 'ɛ̃tɛʁvju',
 'deboʃe',
 'aʒiʁɔ̃',
 'sityʁɛ',
 'fɛsɔ̃',
 'ɛ̃sonoʁize',
 'pʁomɛnəʁɛ',
 'epaʁɲe',
 'pʁɛskʁi',
 'ʁevizɑ̃',
 'ɛ̃tɛʁpʁetɔ̃',
 'makijəʁɛ',
 'kalifiʁɛ',
 'bʁosɛ',
 'lise',
 'paʁtaʒ',
 'pʁepaʁəʁɛ',
 'mɛnəʁɛ',
 'maʁmonɛ',
 'devwalɛ',
 'puʁisɛ',
 'etɛʁnɥɛ',
 'benefisjɛ',
 'ɛksit',
 'ʁɛsplɑ̃dis',
 'tapin',
 'ɑ̃kuʁaʒəʁɛ',
 'sutʁɛt',
 'ɛ̃pʁesjonɑ̃',
 'manigɑ̃sɛ',
 'detɛʁɔ̃',
 'ʁamɛn',
 'pozisjɔn',
 'ameljɔʁəʁɔ̃',
 'baʁak',
 'plije',
 'akɔ̃paɲəʁa',
 'ʁevɛje',
 'gʁɔ̃dəʁɛ',
 'detaje',
 'atɛst',
 'ʁətapise',
 'ʁəkony',
 'ʁədəmɑ̃de',
 'sɔnəʁɔ̃',
 'apaʁtjɛ̃dʁɛ',
 'ʁəbwaʁ',
 'pasjətəʁe',
 'kɔ̃siste',
 'diʁiʒəʁje',
 'gaɲəʁa',
 'ʁɑ̃vɛʁsəʁɛ',
 'ʁøvɔle',
 'syʁpʁɑ̃dʁa',
 'ʒoniʁ',
 'sɑ̃gle',
 'gloʁifi',
 'aleʒe',
 'muʁɛ',
 'ɑ̃kuʁ',
 'ɛgziʒe',
 'ʁəbyte',
 'ʁadikalize',
 'aisɛ',
 'dekupe',
 'deziʁəʁɛ',
 'ekaje',
 'bɛsɛ',
 'kaʃɛ',
 'puʁsɥive',
 'bɔʁde',
 'liʁɔ̃',
 'ʁɛvas',
 'ʁeʃofəʁa',
 'kɔ̃t',
 'vɑ̃piʁize',
 'mitʁaje',
 'sɛlɛ',
 'abɛs',
 'ʁədutɛ',
 'niʃɔ̃',
 'ʁəʃɛʁʃəʁɛ',
 'ʒeʁəʁɛ',
 'pɛʁsonalize',
 'fil',
 'evanwis',
 'sulɛ',
 'ʁəfyzɑ̃',
 'divɔʁsəʁe',
 'idɑ̃tifjɛ',
 'pikoʁe',
 'pyni',
 'ɛ̃tɑ̃sifjɑ̃',
 'gʁatuj',
 'sɛʁmɔn',
 'kʁepit',
 'ʁɛskij',
 'tyb',
 'ʁoti',
 'ɛ̃syltɑ̃',
 'kɔ̃tʁe',
 'utʁəpase',
 'pʁedomin',
 'tatu',
 'pɛʁsəvɛ',
 'ʁeʃofe',
 'sabote',
 'ʁɑ̃fɔʁse',
 'batifole',
 'pʁostɛʁnɔ̃',
 'ʁɛjɔn',
 'ɑ̃bɛte',
 'paʁtisipəʁɔ̃',
 'demaskəʁɔ̃',
 'tʁɑ̃sfɔʁməʁɔ̃',
 'kʁøzəʁɔ̃',
 'ɑ̃vizaʒɔ̃',
 'syʁvivɛ',
 'disfɔ̃ksjɔn',
 'glisəʁɔ̃',
 'blœf',
 'abazuʁdi',
 'likefi',
 'limite',
 'ɛgzɛʁs',
 'tabl',
 'ʃlɛ̃g',
 'tʁavɛsti',
 'ʁɑ̃pəʁɛ',
 'polaʁize',
 'gʁijəʁɛ',
 'ebʁɥitɛ',
 'ɑ̃ʒɑ̃dʁa',
 'tʁiʃɛ',
 'aʃətɛ',
 'favoʁiz',
 'tʁɛ̃bale',
 'adɔpta',
 'taʁod',
 'ɑ̃baʁase',
 'ʁamasa',
 'abitəʁɛ',
 'ɑ̃glɥe',
 'syʁvjɛ̃',
 'ɑ̃tɛ',
 'ʁeɲəʁɔ̃',
 'emɛʁvɛj',
 'pjøte',
 'pʁodɥi',
 'puʁʃasəʁɛ',
 'tɛʁminəʁe',
 'tʁɑ̃pe',
 'pʁostɛʁnəʁa',
 'ʁədemenaʒe',
 'pije',
 'ʁəkomɑ̃de',
 'emuse',
 'gʁosisɛ',
 'titʁa',
 'buji',
 'kaʁe',
 'ʁetʁogʁade',
 'ɑ̃tuʁ',
 'ʁakɔ̃təʁɔ̃',
 'devəlope',
 'fɔʁtifje',
 'demɑ̃təle',
 'ɑ̃nɥije',
 'pʁodɥizɔ̃',
 'blaze',
 'fuʁmij',
 'depɑ̃sɑ̃',
 'ʁətʁɑ̃sfɔʁme',
 'ekʁazɛ',
 'ɑ̃paje',
 'fokalize',
 'ʁɑ̃buʁe',
 'gʁibuje',
 'kɔ̃pylse',
 'li',
 'anyləʁɔ̃',
 'kylpabilizɑ̃',
 'lisɑ̃si',
 'tus',
 'elaʁʒis',
 'ʁəpʁɔʃəʁɛ',
 'pʁije',
 'veje',
 'tɔʁpije',
 'onɔʁ',
 'kozɑ̃',
 'ʁediʒɛ',
 'avwɛ',
 'dyʁɑ̃',
 'deliʁɛ',
 'mate',
 'pøzɑ̃',
 'defiʁɛ',
 'ɑ̃pale',
 'ɑ̃tʁəlas',
 'aeʁe',
 'etydje',
 'ʁəkylɛ',
 'ɛ̃tɛʁoʒe',
 'aniile',
 'etufɛ',
 'ɛgzasɛʁbe',
 'sedɥize',
 'pʁatike',
 'ʁəʃaʁʒ',
 'poʃe',
 'ɛstima',
 'epaʁpije',
 'banis',
 'kaʃe',
 'ʁəbif',
 'pʁevjɛ̃',
 'maʁmɔn',
 'tjɛ̃dʁijɔ̃',
 'paʁke',
 'ʁapɛləʁa',
 'komynike',
 'pikote',
 'paʁ',
 'eʒakyl',
 'ʁepɔ̃',
 'amwɛ̃dʁi',
 'desidəʁa',
 'ʁaze',
 'debɔʁdɛ',
 'bul',
 'plɛ̃dʁa',
 'ʁəbuʃe',
 'kuvʁe',
 'ʁətuʃe',
 'ʁealizɛ',
 'ɑ̃tas',
 'ʁədemaʁ',
 'ɛgzɛʁsɛ',
 'epuzəʁje',
 'dɛɲ',
 'ɛ̃tityle',
 'etydjɛ',
 'ɔʁbitɑ̃',
 'toleʁɛ',
 'pɔstdate',
 'tisɔ̃',
 'gʁezije',
 'sufle',
 'ɑ̃guʁdi',
 'aʒitɛ',
 'ɑ̃bɛtəʁɛ',
 'ɑ̃peʃe',
 'ʁɑ̃buʁsəʁa',
 'emɑ̃sipe',
 'bʁɑ̃dise',
 'ipoteke',
 'devɛʁsɔ̃',
 'tʁɛ̃bal',
 'buʃɛ',
 'flɑ̃ʃ',
 'diminɥɔ̃',
 'ʁagajaʁdi',
 'delimite',
 'ɛstime',
 'etʁɑ̃gləʁɛ',
 'ɑ̃dyʁsi',
 'ɛgzɔʁsiz',
 'adɔʁəʁɛ',
 'ʁətiʁe',
 'ɔpte',
 'depɑ̃se',
 'ʁikan',
 'nɥizɛ',
 'pløvʁa',
 'ʁepɑ̃dʁɛ',
 'fiʃe',
 'ɑ̃flame',
 'ʁəkole',
 'ʁəbatʁ',
 'pʁotɛst',
 'demateʁjaliz',
 'fysje',
 'ɑ̃pwazɔnəʁɛ',
 'ʁenɔvɔ̃',
 'kɔ̃ble',
 'blœf',
 'apaʁɛsɔ̃',
 'syʁvɛjəʁɛ',
 'suʁiʁe',
 'ɑ̃vwaje',
 'ʁavitaje',
 'debaʁasəʁɔ̃',
 'note',
 'kalkyl',
 'dezɑ̃paʁe',
 'kɛstjonɔ̃',
 'ʒaʁdinɛ',
 'ale',
 'mas',
 'pɛʁsɑ̃',
 'pɛʁmɛt',
 'ʁezistəʁa',
 'some',
 'tu',
 'ɑ̃bwate',
 'ʁeysisɑ̃',
 'aksjɔn',
 'pynisɛ',
 'aʁɔ̃disɔ̃',
 'fʁemi',
 'ʁənɔ̃sɛ',
 'fele',
 'pjɛʒ',
 'efʁejɛ',
 'ʁəpɑ̃sje',
 'sɑ̃ti',
 'kʁɛ̃t',
 'ɛ̃teʁese',
 'apɥiʁɛ',
 'ɛsɥije',
 'ʁəʒwɛ̃t',
 'ʁetʁogʁad',
 'siʁote',
 'ʁɛktifjɔ̃',
 'kʁɑ̃pɔn',
 'admiʁjɔ̃',
 'ʁezistəʁɔ̃',
 'anyle',
 'ʁapʁoʃe',
 'klue',
 'epise',
 'flate',
 'apʁuv',
 'iɲoʁɛ',
 'apeze',
 'ʁekypeʁɔ̃',
 'tʁɑ̃ʃɛ',
 'tɑ̃tjɔ̃',
 'ʁəmaʁkjɔ̃',
 'kʁwaʁɛ',
 'gʁezij',
 'ʁəkalibʁe',
 'demɑ̃te',
 'abatʁ',
 'tʁavɛʁsɛ',
 'eplyʃɛ',
 'ɛ̃plikəʁa',
 'gaʁdɛʁ',
 'tʁɑ̃sfɔʁm',
 'ɑ̃majote',
 'kame',
 'dizɛ',
 'eliminəʁɛ',
 'difɛʁ',
 'abutiʁɛ',
 'sufle',
 'detaʃɛ',
 'aneɑ̃tisɔ̃',
 'aleʃe',
 'tʁepas',
 'flɑ̃bɑ̃',
 'difyzəʁɔ̃',
 'ɑ̃dɔʁmi',
 'sɔ̃ʒəʁɛ',
 'deʒeneʁɛ',
 'fofiləʁa',
 'ʁɛstɔʁəʁɔ̃',
 'liʁje',
 'avwe',
 'defigyʁe',
 'ɛ̃skʁivɛ',
 'sɛ̃plifjɛ',
 'pʁezɛʁvəʁe',
 'duʃɛ',
 'ʁatʁapa',
 'afɛblisɛ',
 'syʁplɔ̃bɑ̃',
 'apstʁɛ',
 'pʁɑ̃dʁɛ',
 'ʁədemaʁe',
 'ʁəgaʁdəʁɛ',
 'tɑ̃pɛʁ',
 'kɔ̃paʁtimɑ̃t',
 'delɔkalize',
 'vwajaʒəʁɛ',
 'planɛ',
 'ɑ̃piʁ',
 'ʁɑ̃pəʁa',
 'uspije',
 'efɔ̃dʁ',
 'beni',
 'sɔʁti',
 'eʃwe',
 'dekɔ̃pɔz',
 'lɑ̃s',
 'sideʁe',
 'tɔ̃bɔ̃',
 'aʒi',
 'kɔ̃poz',
 'efʁɛje',
 'degʁɛ̃gɔl',
 'otɑ̃tifje',
 'tiʁɑ̃',
 'fwinɛ',
 'ekulɛ',
 'plɔ̃be',
 'deʃiʁəʁa',
 'ʁətʁuvɛ',
 'ɑ̃tʁave',
 'ʁəkɔ̃te',
 'obliteʁe',
 'eliʁ',
 'peɲe',
 'ʃɑ̃te',
 'leʃuj',
 'blage',
 'kupje',
 'mɛləʁa',
 'akude',
 'onɔʁəʁa',
 'kɔ̃tɑ̃ple',
 'negliʒe',
 'yʁine',
 'asfiksje',
 'dəvinɑ̃',
 'ʁəmaʁiʁɛ',
 'ɑ̃guʁdi',
 'pʁomɛnəʁɔ̃',
 'medi',
 'taʃ',
 'komemoʁe',
 'alɛ',
 'ɑ̃tʁave',
 'mizɛ',
 'amidone',
 'ʃɔpəʁa',
 'ʁakɔ̃paɲe',
 'etufe',
 'ʁeetydje',
 'gut',
 'suvjɛ̃dʁɛ',
 'tɛstəʁɛ',
 'gidəʁɛ',
 'makyle',
 'ʁakɔʁde',
 'gʁasje',
 'ataʁdɔ̃',
 'miz',
 'ɑ̃tɑ̃di',
 'pliʁa',
 'ɑ̃baʁke',
 'flɔtəʁe',
 'tajəʁɛ',
 'nipe',
 'ɔksiʒene',
 'ʁəsɛʁ',
 'vokalize',
 'degɛnɑ̃',
 'selebʁəʁɔ̃',
 'ɑ̃guʁdi',
 'ɑ̃menaʒe',
 'kɔ̃dɥiz',
 'epaʁɲəʁɔ̃',
 'suflɛ',
 'ɛ̃poze',
 'pɛɲe',
 'kɔ̃fɔ̃',
 'ytilize',
 'ʁapɔʁtəʁɛ',
 'ʁaməne',
 'ʁətɑ̃tisɑ̃',
 'maltʁɛt',
 'ɛ̃pɔʁtɑ̃',
 'patise',
 'oskylt',
 'okylte',
 'ʃytɔ̃',
 'eʃap',
 'ʁəlaks',
 'asyʁje',
 'fʁite',
 'ʒɔ̃gl',
 'ʁəpʁɑ̃dʁɛ',
 'fʁaktyʁɑ̃',
 'etiʁɛ',
 'ʁesitəʁe',
 'eklatɛʁ',
 'atiʁəʁɛ',
 'kʁiʁɔ̃',
 'ʁɥinɔ̃',
 'epɛl',
 'detɑ̃dʁɛ',
 'tɛʁminje',
 'planifjɛ',
 'ɑ̃vaisɛ',
 'ayʁi',
 'ɛ̃vitəʁɛ',
 'alam',
 'pʁogʁɛsɛ',
 'ʁivalize',
 'admɛtʁe',
 'ɛ̃syltəʁɛ',
 'ɑ̃dikape',
 'emɛʁʒ',
 'pasjonɛ',
 'debal',
 'depuʁvy',
 'stope',
 'ʃɑ̃tjɔ̃',
 'efʁɛje',
 'bʁøvəte',
 'flœʁiʁa',
 'dekyple',
 'paʁɛtʁ',
 'ɑ̃gʁɑ̃ʒe',
 'ʁɑ̃kɔ̃tʁəʁjɔ̃',
 'aʁɛta',
 'ʁezɛʁvɔ̃',
 'akɔsta',
 'ʁakʁoʃe',
 'vomiʁa',
 'kapt',
 'blɛ̃de',
 'afiʃɔ̃',
 'pasa',
 'patine',
 'kɔ̃sakʁe',
 'libeʁe',
 'suvənɛ',
 'viʁəʁɛ',
 'devaloʁize',
 'fɑ̃tasmɛ',
 'degʁafe',
 'kʁije',
 'ɛgzaminɛ',
 'kalməʁɛ',
 'sɛʁvɛ',
 'myltiplijɛ',
 'ʁeɛgzamine',
 'pʁeokypje',
 'ʃasa',
 'motiv',
 'libeʁɑ̃',
 'deʁape',
 'ʁəlaʃ',
 'ʁekizisjɔn',
 'lase',
 'kɔ̃vɛ̃kɑ̃',
 'ʁabɔt',
 'bʁytalize',
 'tʁɑ̃spɔʁtəʁa',
 'mizɛ',
 'onɔʁəʁe',
 'diʁ',
 'ʁɑ̃sone',
 'konɛsɑ̃',
 'ʁealize',
 'ɛ̃kaʁne',
 'sɛ̃kʁɔniz',
 'sɔm',
 'dedikase',
 'ɛ̃pɔʁtynəʁɛ',
 'ʁeuvʁɔ̃',
 'kɔ̃tuʁne',
 'lege',
 'afʁɔ̃təʁɔ̃',
 'nuʁi',
 'kɔ̃fiske',
 'ɛgzist',
 'galvanize',
 'paʁvjɛ̃dʁɛ',
 'pɛʁɛ',
 'apʁɑ̃dʁɛ',
 'fiksəʁɛ',
 'ʁəpɛʁ',
 'fɔʁʒɔ̃',
 'bʁijɛ',
 'avɑ̃taʒe',
 'kɔ̃plɔt',
 'kɔ̃danəʁje',
 'vɑ̃ʒe',
 'ʁevoke',
 'komyte',
 'ʁeʃapəʁa',
 'kʁole',
 'opeʁe',
 'ɑ̃bal',
 'kɔ̃sɑ̃tʁ',
 'ekutəʁa',
 'kotwaje',
 'ʃoke',
 'egʁatiɲ',
 'poza',
 'tʁɑ̃sfeʁe',
 'dʁogɛ',
 'baʁatinɛ',
 'dezapʁuve',
 'ɛ̃kjete',
 'ʁɑ̃vwa',
 'adub',
 'ʁəgaɲəʁɔ̃',
 'elɛvəʁa',
 'ozɛ',
 'syʁvekyʁ',
 'ʁeʒeneʁe',
 'ʁealizəʁɛ',
 'ʁɛspiʁjɔ̃',
 'ʁəsɑ̃tiʁɛ',
 'ʁupije',
 'pɛʃəʁɛ',
 'ʁəmyʁa',
 'pyʁʒɔ̃',
 'ɑ̃mɛʁdəʁa',
 'emi',
 'akabl',
 'elɑ̃s',
 'fɛsɛ',
 'debaty',
 'ɛgzibɛ',
 'asuvi',
 'iʁite',
 'aʒiʁɛ',
 'diktəʁa',
 'vɛ̃kɔ̃',
 'inɔ̃d',
 'vulɛ',
 'ɑ̃pifʁe',
 'alysinɑ̃',
 'sytyʁe',
 'dʁajv',
 'ʁɛspiʁ',
 'tʁafikɛ',
 'vadʁuje',
 'amnistje',
 'eʃɑ̃ʒəʁe',
 'dyʁsiʁa',
 'domɛstike',
 'vwale',
 'eflœʁ',
 'bʁikole',
 'avizəʁe',
 'ʁɥine',
 'ezite',
 'eklɛʁje',
 'ʃik',
 'kup',
 'depʁime',
 'ʁeysiʁɛ',
 'dəvjɛn',
 'depɛʃəʁe',
 'ɑ̃mɛʁdəʁɔ̃',
 'ʁamase',
 'deɲe',
 'ʁətʁus',
 'atiʁe',
 'dezonoʁe',
 'ibɛʁne',
 'pʁɔstitɥe',
 'kɔ̃fɔ̃dy',
 'paʁad',
 'etabli',
 'degɛʁpis',
 'ʁakɔ̃te',
 'etufe',
 'sotjɔ̃',
 'vole',
 'buskyle',
 'imaʒinɔ̃',
 'degaʒe',
 'ɛstiməʁɛ',
 'demisjɔnəʁɛ',
 'ɑ̃tuʁɛ',
 'ʁatəʁɔ̃',
 'flœʁt',
 'modisɛ',
 'ʁiskəʁɛ',
 'kɔ̃spiʁɑ̃',
 'amɛ̃si',
 'vulwaʁ',
 'kɛstjɔn',
 'syʁpʁiz',
 'ʁəgaʁdɔ̃',
 'pɛʁpetɥe',
 'ɑ̃tam',
 'ɑ̃paʁəʁɔ̃',
 'desɑ̃dɑ̃',
 'deʁivɔ̃',
 'vɛʁsa',
 'apʁoʃe',
 'ləve',
 'ʁepetəʁa',
 'ʁalɑ̃tiʁɛ',
 'ʁekypeʁe',
 'bʁɥis',
 'syblime',
 'ɛksplikəʁɛ',
 'kʁwazɔ̃',
 'maʁkəʁɛ',
 'plastifje',
 'lɛsəʁɔ̃',
 'sɛʁviʁɛ',
 'deʁegle',
 'ʁɔ̃p',
 'geʁis',
 'ɛksplikɔ̃',
 'ʁaplik',
 'ɔbʒɛktiv',
 'epaʁɲəʁɛ',
 'ɛ̃fiʁme',
 'ɑ̃piʁe',
 'ɛ̃tɛʁpoze',
 'ʁəpʁɑ̃dʁa',
 'buskyləʁɛ',
 'vomi',
 'dəmœʁe',
 'tajəʁɛ',
 'aleʒe',
 'diminɥɛ',
 'afliʒ',
 'kɔ̃tʁibɥe',
 'ʁaswa',
 'ɛgzamine',
 'maʁʃɛ',
 'navʁe',
 'kɔ̃tyzjone',
 'mikse',
 'ʁoti',
 'ʃɑ̃t',
 'detʁɥi',
 'pʁofitəʁɛ',
 'ɛ̃tʁodɥize',
 'pʁuv',
 'ɛ̃kjete',
 'metʁize',
 'ɛ̃spiʁəʁa',
 'ʁefleʃisɛ',
 'kʁupis',
 'depane',
 'denwe',
 'buʒəʁɛ',
 'satisfɛ',
 'ɛləve',
 'ʁəkɛt',
 'kɔ̃pʁomɛt',
 'eklɛʁsisɔ̃',
 'ɛ̃difɛʁ',
 'milite',
 'kaptjɔ̃',
 'ʁeklam',
 'nata',
 'enɛʁve',
 'kɔ̃bləʁɔ̃',
 'bœʁe',
 'kɑ̃kane',
 'paʁkuʁɔ̃',
 'lizɑ̃',
 'dezist',
 'kʁakɛ',
 'kɔ̃sylte',
 'ɑ̃fɑ̃təʁa',
 'plase',
 'manœvʁe',
 'fʁime',
 'syʁpas',
 'kuʁyʁ',
 'ʁəsikle',
 'kylpabilize',
 'ɛgzamine',
 'pɛlte',
 'ʁɛstoʁɑ̃',
 'pasəʁe',
 'sovgaʁde',
 'ʁɑ̃tʁe',
 'paʁkuʁjɔ̃',
 'aʁtikyle',
 'oktyple',
 'seviʁ',
 'kɔ̃sakʁe',
 'demolis',
 'foʁɑ̃',
 'pʁɛtəʁɔ̃',
 'asɔ̃bʁis',
 'tuʁmɑ̃təʁa',
 'aʒise',
 'mɛtʁɛ',
 'epje',
 'ɑ̃ketɔ̃',
 'klasəʁɛ',
 'deklin',
 'ʁɑ̃buʁse',
 'dezɛ̃fɛkte',
 'tɑ̃g',
 'imaʒinəʁje',
 'efaʁuʃ',
 'paʁtisip',
 'pɛʁsistɑ̃',
 'fys',
 'dəvəny',
 'konɛktəʁe',
 'pɥis',
 'kanibalize',
 'kʁitike',
 'defənɛstʁe',
 'aməna',
 'pɔ̃dʁɛ',
 'kɔ̃ta',
 'pʁeʃje',
 'ɛ̃kjetɛ',
 'tʁafik',
 'avwɔ̃',
 'sit',
 'kʁwazjɔ̃',
 'abwaje',
 'abijɑ̃',
 'ɛ̃pʁovize',
 'pʁevwa',
 'ɔptənɛ',
 'ʁəpʁodɥiʁɔ̃',
 'blɑ̃ʃiʁɔ̃',
 'tʁɑ̃spɔʁtəʁɛ',
 'kɔ̃tɛstɛ',
 'stɔpəʁɔ̃',
 'sekɛstʁe',
 'ʒɛne',
 'tisɛ',
 'tʁadɥiʁɛ',
 'duʃ',
 'ʁəkonɛtʁa',
 'pɑ̃səʁɔ̃',
 'ʁəʃyt',
 'fleʃiʁa',
 'kʁule',
 'ʁɑ̃plasəʁje',
 'ʁɔ̃ʁonɑ̃',
 'klopin',
 'ɔʁdonɑ̃',
 'difeʁe',
 'kotʃɛ',
 'adeʁe',
 'elɛktʁokyte',
 'tʁuble',
 'taʃe',
 'ʁamasəʁa',
 'legalize',
 'ʁɔ̃p',
 'valide',
 'dʁogɛ',
 'dɔnəʁa',
 'dezɛspeʁe',
 'kɔ̃tʁəvəniʁ',
 'ʁuvʁiʁɛ',
 'felisitəʁa',
 'ʁapɔʁte',
 'faʃe',
 'avɛʁtiʁɔ̃',
 'tɛ̃te',
 'fjɑ̃s',
 'lapa',
 'ɛ̃pʁeɲe',
 'bɛʁse',
 'familjaʁize',
 'slajs',
 'esɥiʁe',
 'desinje',
 'ʁeyniʁɔ̃',
 'kɔləʁa',
 'ʁɛstoʁe',
 'blame',
 'fɔ̃diʁ',
 'ʁijɔ̃',
 'bʁizəʁɔ̃',
 'dezonɔʁəʁa',
 'pepi',
 'ɑ̃ta',
 'suzɛstime',
 'ʃwaziʁe',
 'ibɛʁnɛ',
 'ʁətʁete',
 'pʁolɔ̃ʒəʁɛ',
 'ʁəpas',
 'kuple',
 'pɥɛ',
 'dɔʁmɛ',
 'kyb',
 'depuʁvy',
 'tɛ̃te',
 'bipe',
 'ʁətʁavaje',
 'blese',
 'distʁɛ',
 'fofilɛ',
 'aksɑ̃ty',
 'kwin',
 'oʁifje',
 'apɛləʁa',
 'fofilɑ̃',
 'ɛ̃pʁesjone',
 'sɔ̃bʁe',
 'deʁatize',
 'deplasəʁɛ',
 'kɔ̃sɛʁte',
 'paʁi',
 'ɑ̃fʁɛ̃t',
 'psalmodi',
 'fʁekɑ̃təʁɛ',
 'maʃe',
 'maʁʃe',
 'pʁodig',
 'asyme',
 'ɑ̃ʃɑ̃t',
 'ʁekɔltje',
 'opsɛd',
 'kɔ̃vɛ̃kʁɛ',
 'fɥijje',
 'pjetine',
 'flote',
 'koʁiʒəʁɛ',
 'dedɥiʁɔ̃',
 ...]

In [210]:
# 2. Load the list into Linguistica
# 'morpheme_min_len' and 'affix_min_len' can be adjusted based on word length
dHeadLxa = lxa.from_wordlist(headWords)

# 3. Run morphological analysis
# Extract signatures (prefix/suffix patterns like NULL-ed-ing-s)
headSignatures = dHeadLxa.signatures()
# signatures

In [211]:
lHeadWords=dHeadLxa.wordlist()
headAffixs=dHeadLxa.affixes()
headStems=dHeadLxa.stems()

In [214]:
word="kaʁnasje"
if word in lHeadWords:
    print(word,"is in the head")
else:
    print(word,"is not in the head")
    if word in lWords:
        print(word,"is in the lexicon")
    else:
        print(word,"is not in the lexicon")

for s in headStems:
    if s in word:
        affixes=[a for a in word.split(s) if a!=""]
        print(s,affixes)
        analysable=True
        for affixe in affixes:
            if affixe not in headAffixs:
                analysable=False
                break
        if analysable:
            print("=>",s,affixes)
            # print("stem in",dLxa.stems_to_words()[s])
            print("stem in",", ".join(set.union(*[head2Lex[x] for x in dHeadLxa.stems_to_words()[s]])))
            # for affixe in affixes:
            #     print("affix in",dLxa.affixes_to_signatures()[affixe])

kaʁnasje is in the head
kaʁnasj ['e']
=> kaʁnasj ['e']
stem in carnassier, carnation
kaʁn ['asje']
kaʁna ['sje']
asje ['kaʁn']
aʁna ['k', 'sje']